<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $session->entity_type }} export</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #111; }
        .brand { margin-bottom: 12px; border-bottom: 1px solid #ccc; padding-bottom: 8px; }
        .brand h1 { margin: 0; font-size: 16px; }
        .meta { color: #555; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th, td { border: 1px solid #ddd; padding: 4px 6px; text-align: left; vertical-align: top; }
        th { background: #f3f4f6; font-weight: bold; }
        .footer { margin-top: 16px; font-size: 9px; color: #666; border-top: 1px solid #ccc; padding-top: 6px; }
    </style>
</head>
<body>
    <div class="brand">
        @php
            $logoSrc = $organization->logo_url;
            if (! $logoSrc) {
                $logoFile = public_path(ltrim((string) config('branding.logo', 'konnect-logo.png'), '/'));
                $logoSrc = is_file($logoFile) ? $logoFile : null;
            }
        @endphp
        @if ($logoSrc)
            <img src="{{ $logoSrc }}" alt="" style="max-height: 40px; margin-bottom: 6px;">
        @endif
        <h1>{{ $organization->name }}</h1>
        <div class="meta">
            {{ __('Export') }}: {{ ucfirst(str_replace('_', ' ', $session->entity_type)) }}
            · {{ strtoupper($session->format) }}
            · {{ __('Generated by') }}: {{ $actor?->name ?? '—' }}
            · {{ $generatedAt->format('Y-m-d H:i') }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                @foreach ($headers as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach ($rows as $row)
                <tr>
                    @foreach ($row as $cell)
                        <td>{{ $cell }}</td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        {{ __('Record count') }}: {{ count($rows) }}
        · {{ __('Confidential — organization data. Do not share outside authorized channels.') }}
    </div>
</body>
</html>
