<?php

return [

    'cache_ttl' => (int) env('DASHBOARD_CACHE_TTL', 300),

    'modules' => [
        'common',
        'crm',
        'hrms',
        'recruitment',
        'projects',
        'finance',
        'support',
        'workflow',
        'notifications',
        'calendar',
    ],

    'plan_modules' => [
        'starter' => [
            'common', 'crm', 'tasks', 'notifications', 'calendar',
        ],
        'professional' => [
            'common', 'crm', 'hrms', 'recruitment', 'projects', 'finance',
            'support', 'workflow', 'notifications', 'calendar', 'tasks',
        ],
        'enterprise' => '*',
    ],

    'sections' => [
        [
            'slug' => 'overview',
            'name' => 'Overview',
            'description' => 'Welcome and activity overview',
            'sort_order' => 10,
        ],
        [
            'slug' => 'crm',
            'name' => 'CRM',
            'description' => 'Sales and pipeline widgets',
            'sort_order' => 20,
        ],
        [
            'slug' => 'hrms',
            'name' => 'HRMS',
            'description' => 'Human resources widgets',
            'sort_order' => 30,
        ],
        [
            'slug' => 'recruitment',
            'name' => 'Recruitment',
            'description' => 'Hiring and candidate widgets',
            'sort_order' => 40,
        ],
        [
            'slug' => 'projects',
            'name' => 'Projects',
            'description' => 'Project and task widgets',
            'sort_order' => 50,
        ],
        [
            'slug' => 'finance',
            'name' => 'Finance',
            'description' => 'Financial widgets',
            'sort_order' => 60,
        ],
        [
            'slug' => 'support',
            'name' => 'Support',
            'description' => 'Support ticket widgets',
            'sort_order' => 70,
        ],
        [
            'slug' => 'workflow',
            'name' => 'Workflow',
            'description' => 'Approval and workflow widgets',
            'sort_order' => 80,
        ],
    ],

    'widgets' => [
        'welcome' => [
            'section' => 'overview',
            'module' => 'common',
            'name' => 'Welcome',
            'description' => 'Personalized welcome message',
            'icon' => 'heroicon-o-home',
            'permission_slug' => null,
            'subscription_module' => 'common',
            'default_width' => 12,
            'default_height' => 2,
            'default_position' => 0,
            'data_provider' => \App\Services\Dashboard\Widgets\WelcomeWidgetProvider::class,
        ],
        'notifications' => [
            'section' => 'overview',
            'module' => 'notifications',
            'name' => 'Recent Notifications',
            'description' => 'Latest notifications for the current user',
            'icon' => 'heroicon-o-bell',
            'permission_slug' => null,
            'subscription_module' => 'notifications',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 1,
            'data_provider' => \App\Services\Dashboard\Widgets\NotificationsWidgetProvider::class,
        ],
        'calendar' => [
            'section' => 'overview',
            'module' => 'calendar',
            'name' => 'Upcoming Events',
            'description' => 'Calendar events and deadlines',
            'icon' => 'heroicon-o-calendar',
            'permission_slug' => 'tasks.view',
            'subscription_module' => 'calendar',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 2,
            'data_provider' => \App\Services\Dashboard\Widgets\CalendarWidgetProvider::class,
        ],
        'recent_activities' => [
            'section' => 'overview',
            'module' => 'common',
            'name' => 'Recent Activities',
            'description' => 'Recent actions and assigned work',
            'icon' => 'heroicon-o-clock',
            'permission_slug' => 'audit.view',
            'subscription_module' => 'common',
            'default_width' => 12,
            'default_height' => 4,
            'default_position' => 3,
            'data_provider' => \App\Services\Dashboard\Widgets\RecentActivitiesWidgetProvider::class,
        ],
        'my_leads' => [
            'section' => 'crm',
            'module' => 'crm',
            'name' => 'My Leads',
            'description' => 'Leads assigned to you',
            'icon' => 'heroicon-o-user-group',
            'permission_slug' => 'leads.view',
            'subscription_module' => 'crm',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 0,
            'data_provider' => \App\Services\Dashboard\Widgets\MyLeadsWidgetProvider::class,
        ],
        'pipeline' => [
            'section' => 'crm',
            'module' => 'crm',
            'name' => 'Pipeline',
            'description' => 'Opportunity pipeline summary',
            'icon' => 'heroicon-o-funnel',
            'permission_slug' => 'opportunities.view',
            'subscription_module' => 'crm',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 1,
            'data_provider' => \App\Services\Dashboard\Widgets\PipelineWidgetProvider::class,
        ],
        'mark_attendance' => [
            'section' => 'hrms',
            'module' => 'hrms',
            'name' => 'Mark Attendance',
            'description' => 'Quick attendance status',
            'icon' => 'heroicon-o-finger-print',
            'permission_slug' => 'ess.access',
            'subscription_module' => 'hrms',
            'default_width' => 4,
            'default_height' => 3,
            'default_position' => 0,
            'data_provider' => \App\Services\Dashboard\Widgets\MarkAttendanceWidgetProvider::class,
        ],
        'leave_balance' => [
            'section' => 'hrms',
            'module' => 'hrms',
            'name' => 'Leave Balance',
            'description' => 'Available leave balances',
            'icon' => 'heroicon-o-sun',
            'permission_slug' => 'leave.view',
            'subscription_module' => 'hrms',
            'default_width' => 4,
            'default_height' => 3,
            'default_position' => 1,
            'data_provider' => \App\Services\Dashboard\Widgets\LeaveBalanceWidgetProvider::class,
        ],
        'interviews_today' => [
            'section' => 'recruitment',
            'module' => 'recruitment',
            'name' => 'Interviews Today',
            'description' => 'Scheduled interviews for today',
            'icon' => 'heroicon-o-video-camera',
            'permission_slug' => 'recruitment.interview.view',
            'subscription_module' => 'recruitment',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 0,
            'data_provider' => \App\Services\Dashboard\Widgets\InterviewsTodayWidgetProvider::class,
        ],
        'my_tasks' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'My Tasks',
            'description' => 'Tasks assigned to you',
            'icon' => 'heroicon-o-clipboard-document-list',
            'permission_slug' => 'tasks.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 0,
            'data_provider' => \App\Services\Dashboard\Widgets\MyTasksWidgetProvider::class,
        ],
        'tasks_due_today' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Tasks Due Today',
            'description' => 'Open tasks due today',
            'icon' => 'heroicon-o-calendar-days',
            'permission_slug' => 'tasks.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 1,
            'data_provider' => \App\Services\Dashboard\Widgets\TasksDueTodayWidgetProvider::class,
        ],
        'overdue_tasks' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Overdue Tasks',
            'description' => 'Open tasks past their due date',
            'icon' => 'heroicon-o-exclamation-triangle',
            'permission_slug' => 'tasks.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 2,
            'data_provider' => \App\Services\Dashboard\Widgets\OverdueTasksWidgetProvider::class,
        ],
        'recently_updated_tasks' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Recently Updated Tasks',
            'description' => 'Tasks updated recently',
            'icon' => 'heroicon-o-arrow-path',
            'permission_slug' => 'tasks.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 3,
            'data_provider' => \App\Services\Dashboard\Widgets\RecentlyUpdatedTasksWidgetProvider::class,
        ],
        'time_logged_today' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Time Logged Today',
            'description' => 'Time logged against tasks today',
            'icon' => 'heroicon-o-clock',
            'permission_slug' => 'tasks.time-log',
            'subscription_module' => 'projects',
            'default_width' => 4,
            'default_height' => 3,
            'default_position' => 4,
            'data_provider' => \App\Services\Dashboard\Widgets\TimeLoggedTodayWidgetProvider::class,
        ],
        'team_task_summary' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Team Task Summary',
            'description' => 'Open and overdue task counts for the team',
            'icon' => 'heroicon-o-users',
            'permission_slug' => 'tasks.manage',
            'subscription_module' => 'projects',
            'default_width' => 8,
            'default_height' => 4,
            'default_position' => 5,
            'data_provider' => \App\Services\Dashboard\Widgets\TeamTaskSummaryWidgetProvider::class,
        ],
        'my_projects' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'My Projects',
            'description' => 'Projects you own, manage, or belong to',
            'icon' => 'heroicon-o-folder',
            'permission_slug' => 'projects.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 6,
            'data_provider' => \App\Services\Dashboard\Widgets\MyProjectsWidgetProvider::class,
        ],
        'active_projects' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Active Projects',
            'description' => 'Projects currently in active status',
            'icon' => 'heroicon-o-play',
            'permission_slug' => 'projects.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 7,
            'data_provider' => \App\Services\Dashboard\Widgets\ActiveProjectsWidgetProvider::class,
        ],
        'project_deadlines' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Project Deadlines',
            'description' => 'Upcoming project end dates',
            'icon' => 'heroicon-o-calendar-days',
            'permission_slug' => 'projects.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 8,
            'data_provider' => \App\Services\Dashboard\Widgets\ProjectDeadlinesWidgetProvider::class,
        ],
        'project_milestones' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Project Milestones',
            'description' => 'Upcoming project milestones',
            'icon' => 'heroicon-o-flag',
            'permission_slug' => 'projects.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 9,
            'data_provider' => \App\Services\Dashboard\Widgets\ProjectMilestonesWidgetProvider::class,
        ],
        'team_workload' => [
            'section' => 'projects',
            'module' => 'resources',
            'name' => 'Team Workload',
            'description' => 'Team utilization and capacity overview',
            'icon' => 'heroicon-o-chart-bar',
            'permission_slug' => 'resources.view',
            'subscription_module' => 'projects',
            'default_width' => 8,
            'default_height' => 4,
            'default_position' => 10,
            'data_provider' => \App\Services\Dashboard\Widgets\TeamWorkloadWidgetProvider::class,
        ],
        'resource_availability' => [
            'section' => 'projects',
            'module' => 'resources',
            'name' => 'Resource Availability',
            'description' => 'Employees with available capacity',
            'icon' => 'heroicon-o-user-plus',
            'permission_slug' => 'resources.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 11,
            'data_provider' => \App\Services\Dashboard\Widgets\ResourceAvailabilityWidgetProvider::class,
        ],
        'overallocated_employees' => [
            'section' => 'projects',
            'module' => 'resources',
            'name' => 'Overallocated Employees',
            'description' => 'Employees over planned capacity',
            'icon' => 'heroicon-o-exclamation-triangle',
            'permission_slug' => 'resources.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 12,
            'data_provider' => \App\Services\Dashboard\Widgets\OverallocatedEmployeesWidgetProvider::class,
        ],
        'upcoming_capacity_risks' => [
            'section' => 'projects',
            'module' => 'resources',
            'name' => 'Upcoming Capacity Risks',
            'description' => 'Forecast capacity risks in the coming days',
            'icon' => 'heroicon-o-bolt',
            'permission_slug' => 'resources.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 13,
            'data_provider' => \App\Services\Dashboard\Widgets\UpcomingCapacityRisksWidgetProvider::class,
        ],
        'project_health' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Project Health',
            'description' => 'Portfolio health status summary',
            'icon' => 'heroicon-o-heart',
            'permission_slug' => 'projects.health.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 14,
            'data_provider' => \App\Services\Dashboard\Widgets\ProjectHealthWidgetProvider::class,
        ],
        'projects_at_risk' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Projects at Risk',
            'description' => 'Projects flagged as at risk or delayed',
            'icon' => 'heroicon-o-exclamation-circle',
            'permission_slug' => 'projects.health.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 15,
            'data_provider' => \App\Services\Dashboard\Widgets\ProjectsAtRiskWidgetProvider::class,
        ],
        'recently_updated_projects' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Recently Updated Projects',
            'description' => 'Projects with recent progress updates',
            'icon' => 'heroicon-o-arrow-trending-up',
            'permission_slug' => 'projects.progress.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 16,
            'data_provider' => \App\Services\Dashboard\Widgets\RecentlyUpdatedProjectsWidgetProvider::class,
        ],
        'completion_trend' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Completion Trend',
            'description' => 'Task completion trends over time',
            'icon' => 'heroicon-o-chart-bar-square',
            'permission_slug' => 'projects.statistics.view',
            'subscription_module' => 'projects',
            'default_width' => 8,
            'default_height' => 4,
            'default_position' => 17,
            'data_provider' => \App\Services\Dashboard\Widgets\CompletionTrendWidgetProvider::class,
        ],
        'team_velocity' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Team Velocity',
            'description' => 'Tasks completed in the recent period',
            'icon' => 'heroicon-o-rocket-launch',
            'permission_slug' => 'projects.statistics.view',
            'subscription_module' => 'projects',
            'default_width' => 4,
            'default_height' => 3,
            'default_position' => 18,
            'data_provider' => \App\Services\Dashboard\Widgets\TeamVelocityWidgetProvider::class,
        ],
        'watching_projects' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'My Watching',
            'description' => 'Projects and tasks you are watching',
            'icon' => 'heroicon-o-eye',
            'permission_slug' => 'projects.watchers.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 19,
            'data_provider' => \App\Services\Dashboard\Widgets\WatchingWidgetProvider::class,
        ],
        'project_mentions' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Mentions',
            'description' => 'Recent mentions of you in projects and tasks',
            'icon' => 'heroicon-o-at-symbol',
            'permission_slug' => 'projects.mentions.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 20,
            'data_provider' => \App\Services\Dashboard\Widgets\MentionsWidgetProvider::class,
        ],
        'recent_collaboration' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Recent Collaboration',
            'description' => 'Pinned discussion and recent collaboration activity',
            'icon' => 'heroicon-o-chat-bubble-left-right',
            'permission_slug' => 'projects.collaboration.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 21,
            'data_provider' => \App\Services\Dashboard\Widgets\RecentCollaborationWidgetProvider::class,
        ],
        'project_calendar' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Project Calendar',
            'description' => 'Upcoming synced project calendar events',
            'icon' => 'heroicon-o-calendar',
            'permission_slug' => 'projects.calendar.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 22,
            'data_provider' => \App\Services\Dashboard\Widgets\ProjectCalendarWidgetProvider::class,
        ],
        'template_usage' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Template Usage',
            'description' => 'Most used project templates',
            'icon' => 'heroicon-o-document-duplicate',
            'permission_slug' => 'projects.templates.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 23,
            'data_provider' => \App\Services\Dashboard\Widgets\TemplateUsageWidgetProvider::class,
        ],
        'recurring_tasks' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Recurring Tasks',
            'description' => 'Active recurring task schedules',
            'icon' => 'heroicon-o-arrow-path',
            'permission_slug' => 'projects.recurrence.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 24,
            'data_provider' => \App\Services\Dashboard\Widgets\RecurringTasksWidgetProvider::class,
        ],
        'portfolio_overview' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Portfolio Overview',
            'description' => 'Portfolios by status and recent portfolios',
            'icon' => 'heroicon-o-briefcase',
            'permission_slug' => 'projects.portfolios.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 26,
            'data_provider' => \App\Services\Dashboard\Widgets\PortfolioOverviewWidgetProvider::class,
        ],
        'program_overview' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Program Overview',
            'description' => 'Programs by status and recent programs',
            'icon' => 'heroicon-o-squares-2x2',
            'permission_slug' => 'projects.programs.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 27,
            'data_provider' => \App\Services\Dashboard\Widgets\ProgramOverviewWidgetProvider::class,
        ],
        'portfolio_health_epm' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Portfolio Health (EPM)',
            'description' => 'Portfolio-level health and risk rollups',
            'icon' => 'heroicon-o-heart',
            'permission_slug' => 'projects.portfolios.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 28,
            'data_provider' => \App\Services\Dashboard\Widgets\PortfolioHealthEpmWidgetProvider::class,
        ],
        'risk_heatmap' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Risk Heatmap',
            'description' => 'Probability vs impact risk matrix',
            'icon' => 'heroicon-o-fire',
            'permission_slug' => 'projects.risks.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 29,
            'data_provider' => \App\Services\Dashboard\Widgets\RiskHeatmapWidgetProvider::class,
        ],
        'budget_health' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Budget Health',
            'description' => 'Planned vs actual vs forecast budget totals',
            'icon' => 'heroicon-o-banknotes',
            'permission_slug' => 'projects.budgets.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 30,
            'data_provider' => \App\Services\Dashboard\Widgets\BudgetHealthWidgetProvider::class,
        ],
        'portfolio_forecast' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Portfolio Forecast',
            'description' => 'Delivery and budget forecast summary',
            'icon' => 'heroicon-o-chart-bar',
            'permission_slug' => 'projects.forecasts.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 31,
            'data_provider' => \App\Services\Dashboard\Widgets\PortfolioForecastWidgetProvider::class,
        ],
        'executive_summary' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Executive Summary',
            'description' => 'Organization-wide executive KPIs',
            'icon' => 'heroicon-o-presentation-chart-line',
            'permission_slug' => 'projects.executive.view',
            'subscription_module' => 'projects',
            'default_width' => 8,
            'default_height' => 4,
            'default_position' => 32,
            'data_provider' => \App\Services\Dashboard\Widgets\ExecutiveSummaryWidgetProvider::class,
        ],
        'upcoming_risks' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Upcoming Risks',
            'description' => 'Open risks approaching due dates',
            'icon' => 'heroicon-o-exclamation-triangle',
            'permission_slug' => 'projects.risks.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 33,
            'data_provider' => \App\Services\Dashboard\Widgets\UpcomingRisksWidgetProvider::class,
        ],
        'budget_variance' => [
            'section' => 'projects',
            'module' => 'projects',
            'name' => 'Budget Variance',
            'description' => 'Budgets with the largest variance',
            'icon' => 'heroicon-o-scale',
            'permission_slug' => 'projects.budgets.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 34,
            'data_provider' => \App\Services\Dashboard\Widgets\BudgetVarianceWidgetProvider::class,
        ],
        'resource_utilization_summary' => [
            'section' => 'projects',
            'module' => 'resources',
            'name' => 'Resource Utilization Summary',
            'description' => 'Team utilization status overview',
            'icon' => 'heroicon-o-presentation-chart-line',
            'permission_slug' => 'resources.view',
            'subscription_module' => 'projects',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 25,
            'data_provider' => \App\Services\Dashboard\Widgets\ResourceUtilizationSummaryWidgetProvider::class,
        ],
        'pending_expenses' => [
            'section' => 'finance',
            'module' => 'finance',
            'name' => 'Pending Expenses',
            'description' => 'Outstanding expense items',
            'icon' => 'heroicon-o-banknotes',
            'permission_slug' => 'finance.view',
            'subscription_module' => 'finance',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 0,
            'data_provider' => \App\Services\Dashboard\Widgets\PendingExpensesWidgetProvider::class,
        ],
        'open_tickets' => [
            'section' => 'support',
            'module' => 'support',
            'name' => 'Open Tickets',
            'description' => 'Open support tickets',
            'icon' => 'heroicon-o-lifebuoy',
            'permission_slug' => 'tasks.view',
            'subscription_module' => 'support',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 0,
            'data_provider' => \App\Services\Dashboard\Widgets\OpenTicketsWidgetProvider::class,
        ],
        'pending_approvals' => [
            'section' => 'workflow',
            'module' => 'workflow',
            'name' => 'Pending Approvals',
            'description' => 'Items awaiting your approval',
            'icon' => 'heroicon-o-check-badge',
            'permission_slug' => 'workflows.view',
            'subscription_module' => 'workflow',
            'default_width' => 6,
            'default_height' => 4,
            'default_position' => 0,
            'data_provider' => \App\Services\Dashboard\Widgets\PendingApprovalsWidgetProvider::class,
        ],
    ],

    'quick_actions' => [
        'mark_attendance' => [
            'module' => 'hrms',
            'name' => 'Mark Attendance',
            'icon' => 'heroicon-o-finger-print',
            'route' => 'ess.attendance.index',
            'permission_slug' => 'ess.access',
            'subscription_module' => 'hrms',
            'sort_order' => 10,
        ],
        'apply_leave' => [
            'module' => 'hrms',
            'name' => 'Apply Leave',
            'icon' => 'heroicon-o-sun',
            'route' => 'ess.leave.index',
            'permission_slug' => 'ess.access',
            'subscription_module' => 'hrms',
            'sort_order' => 20,
        ],
        'view_payslip' => [
            'module' => 'hrms',
            'name' => 'View Payslip',
            'icon' => 'heroicon-o-document-text',
            'route' => 'ess.payroll.payslips',
            'permission_slug' => 'payslip.view',
            'subscription_module' => 'hrms',
            'sort_order' => 30,
        ],
        'my_tasks' => [
            'module' => 'projects',
            'name' => 'My Tasks',
            'icon' => 'heroicon-o-clipboard-document-list',
            'route' => 'tasks.index',
            'permission_slug' => 'tasks.view',
            'subscription_module' => 'projects',
            'sort_order' => 40,
        ],
        'create_task' => [
            'module' => 'projects',
            'name' => 'Create Task',
            'icon' => 'heroicon-o-plus-circle',
            'route' => 'tasks.create',
            'permission_slug' => 'tasks.create',
            'subscription_module' => 'projects',
            'sort_order' => 40.5,
        ],
        'log_time' => [
            'module' => 'projects',
            'name' => 'Log Time',
            'icon' => 'heroicon-o-clock',
            'route' => 'tasks.index',
            'permission_slug' => 'tasks.time-log',
            'subscription_module' => 'projects',
            'sort_order' => 40.6,
        ],
        'create_project' => [
            'module' => 'projects',
            'name' => 'Create Project',
            'icon' => 'heroicon-o-plus-circle',
            'route' => 'projects.create',
            'permission_slug' => 'projects.create',
            'subscription_module' => 'projects',
            'sort_order' => 41,
        ],
        'view_projects' => [
            'module' => 'projects',
            'name' => 'View Projects',
            'icon' => 'heroicon-o-folder',
            'route' => 'projects.index',
            'permission_slug' => 'projects.view',
            'subscription_module' => 'projects',
            'sort_order' => 42,
        ],
        'project_calendar' => [
            'module' => 'projects',
            'name' => 'Project Calendar',
            'icon' => 'heroicon-o-calendar-days',
            'route' => 'projects.dashboard',
            'permission_slug' => 'projects.calendar.view',
            'subscription_module' => 'projects',
            'sort_order' => 43,
        ],
        'create_template' => [
            'module' => 'projects',
            'name' => 'Create Template',
            'icon' => 'heroicon-o-document-duplicate',
            'route' => 'projects.templates.create',
            'permission_slug' => 'projects.templates.create',
            'subscription_module' => 'projects',
            'sort_order' => 43.1,
        ],
        'watch_project' => [
            'module' => 'projects',
            'name' => 'Watch Project',
            'icon' => 'heroicon-o-eye',
            'route' => 'projects.index',
            'permission_slug' => 'projects.watchers.manage',
            'subscription_module' => 'projects',
            'sort_order' => 43.2,
        ],
        'create_recurring_task' => [
            'module' => 'projects',
            'name' => 'Create Recurring Task',
            'icon' => 'heroicon-o-arrow-path',
            'route' => 'tasks.create',
            'permission_slug' => 'projects.recurrence.manage',
            'subscription_module' => 'projects',
            'sort_order' => 43.3,
        ],
        'mention_user' => [
            'module' => 'projects',
            'name' => 'Mention User',
            'icon' => 'heroicon-o-at-symbol',
            'route' => 'projects.dashboard',
            'permission_slug' => 'projects.mentions.view',
            'subscription_module' => 'projects',
            'sort_order' => 43.4,
        ],
        'create_portfolio' => [
            'module' => 'projects',
            'name' => 'Create Portfolio',
            'icon' => 'heroicon-o-briefcase',
            'route' => 'portfolios.create',
            'permission_slug' => 'projects.portfolios.create',
            'subscription_module' => 'projects',
            'sort_order' => 43.5,
        ],
        'create_program' => [
            'module' => 'projects',
            'name' => 'Create Program',
            'icon' => 'heroicon-o-squares-2x2',
            'route' => 'programs.create',
            'permission_slug' => 'projects.programs.create',
            'subscription_module' => 'projects',
            'sort_order' => 43.6,
        ],
        'create_risk' => [
            'module' => 'projects',
            'name' => 'Create Risk',
            'icon' => 'heroicon-o-exclamation-triangle',
            'route' => 'project-risks.create',
            'permission_slug' => 'projects.risks.create',
            'subscription_module' => 'projects',
            'sort_order' => 43.7,
        ],
        'capture_baseline' => [
            'module' => 'projects',
            'name' => 'Capture Baseline',
            'icon' => 'heroicon-o-camera',
            'route' => 'project-baselines.create',
            'permission_slug' => 'projects.baselines.create',
            'subscription_module' => 'projects',
            'sort_order' => 43.8,
        ],
        'generate_portfolio_report' => [
            'module' => 'projects',
            'name' => 'Generate Portfolio Report',
            'icon' => 'heroicon-o-document-chart-bar',
            'route' => 'portfolio-reports.create',
            'permission_slug' => 'projects.portfolio_reports.generate',
            'subscription_module' => 'projects',
            'sort_order' => 43.9,
        ],
        'view_forecast' => [
            'module' => 'projects',
            'name' => 'View Forecast',
            'icon' => 'heroicon-o-chart-bar',
            'route' => 'forecasts.index',
            'permission_slug' => 'projects.forecasts.view',
            'subscription_module' => 'projects',
            'sort_order' => 43.95,
        ],
        'executive_dashboard' => [
            'module' => 'projects',
            'name' => 'Executive Dashboard',
            'icon' => 'heroicon-o-presentation-chart-line',
            'route' => 'projects.executive',
            'permission_slug' => 'projects.executive.view',
            'subscription_module' => 'projects',
            'sort_order' => 43.96,
        ],
        'allocate_resource' => [
            'module' => 'resources',
            'name' => 'Allocate Resource',
            'icon' => 'heroicon-o-user-plus',
            'route' => 'resources.allocations.create',
            'permission_slug' => 'resources.allocate',
            'subscription_module' => 'projects',
            'sort_order' => 44,
        ],
        'view_team_capacity' => [
            'module' => 'resources',
            'name' => 'View Team Capacity',
            'icon' => 'heroicon-o-chart-bar',
            'route' => 'resources.capacity',
            'permission_slug' => 'resources.view',
            'subscription_module' => 'projects',
            'sort_order' => 45,
        ],
        'approve_leave' => [
            'module' => 'hrms',
            'name' => 'Approve Leave',
            'icon' => 'heroicon-o-check-circle',
            'route' => 'hrms.leave-applications.approval-queue',
            'permission_slug' => 'leave.approve',
            'subscription_module' => 'hrms',
            'sort_order' => 50,
        ],
        'team_attendance' => [
            'module' => 'hrms',
            'name' => 'Team Attendance',
            'icon' => 'heroicon-o-users',
            'route' => 'hrms.attendance.index',
            'permission_slug' => 'attendance.view',
            'subscription_module' => 'hrms',
            'sort_order' => 60,
        ],
        'team_tasks' => [
            'module' => 'projects',
            'name' => 'Team Tasks',
            'icon' => 'heroicon-o-user-group',
            'route' => 'tasks.index',
            'permission_slug' => 'tasks.manage',
            'subscription_module' => 'projects',
            'sort_order' => 70,
        ],
        'project_dashboard' => [
            'module' => 'projects',
            'name' => 'Project Dashboard',
            'icon' => 'heroicon-o-chart-bar',
            'route' => 'projects.dashboard',
            'permission_slug' => 'projects.view',
            'subscription_module' => 'projects',
            'sort_order' => 80,
        ],
        'update_progress' => [
            'module' => 'projects',
            'name' => 'Update Progress',
            'icon' => 'heroicon-o-arrow-trending-up',
            'route' => 'projects.dashboard',
            'permission_slug' => 'projects.progress.create',
            'subscription_module' => 'projects',
            'sort_order' => 81,
        ],
        'add_progress_note' => [
            'module' => 'projects',
            'name' => 'Add Progress Note',
            'icon' => 'heroicon-o-pencil-square',
            'route' => 'projects.dashboard',
            'permission_slug' => 'projects.progress.create',
            'subscription_module' => 'projects',
            'sort_order' => 82,
        ],
        'generate_report' => [
            'module' => 'projects',
            'name' => 'Generate Report',
            'icon' => 'heroicon-o-document-chart-bar',
            'route' => 'projects.executive',
            'permission_slug' => 'projects.reports.generate',
            'subscription_module' => 'projects',
            'sort_order' => 83,
        ],
        'view_timeline' => [
            'module' => 'projects',
            'name' => 'View Timeline',
            'icon' => 'heroicon-o-calendar',
            'route' => 'projects.dashboard',
            'permission_slug' => 'projects.timeline.view',
            'subscription_module' => 'projects',
            'sort_order' => 84,
        ],
        'view_gantt' => [
            'module' => 'projects',
            'name' => 'View Gantt',
            'icon' => 'heroicon-o-view-columns',
            'route' => 'projects.dashboard',
            'permission_slug' => 'projects.gantt.view',
            'subscription_module' => 'projects',
            'sort_order' => 85,
        ],
        'export_report' => [
            'module' => 'projects',
            'name' => 'Export Report',
            'icon' => 'heroicon-o-arrow-down-tray',
            'route' => 'projects.executive',
            'permission_slug' => 'projects.reports.generate',
            'subscription_module' => 'projects',
            'sort_order' => 86,
        ],
        'create_lead' => [
            'module' => 'crm',
            'name' => 'Create Lead',
            'icon' => 'heroicon-o-plus-circle',
            'route' => 'leads.create',
            'permission_slug' => 'leads.create',
            'subscription_module' => 'crm',
            'sort_order' => 90,
        ],
        'schedule_follow_up' => [
            'module' => 'crm',
            'name' => 'Schedule Follow-up',
            'icon' => 'heroicon-o-calendar-days',
            'route' => 'tasks.create',
            'permission_slug' => 'tasks.create',
            'subscription_module' => 'crm',
            'sort_order' => 100,
        ],
        'create_opportunity' => [
            'module' => 'crm',
            'name' => 'Create Opportunity',
            'icon' => 'heroicon-o-briefcase',
            'route' => 'opportunities.create',
            'permission_slug' => 'opportunities.create',
            'subscription_module' => 'crm',
            'sort_order' => 110,
        ],
        'add_employee' => [
            'module' => 'hrms',
            'name' => 'Add Employee',
            'icon' => 'heroicon-o-user-plus',
            'route' => 'hrms.employees.create',
            'permission_slug' => 'hrms.create',
            'subscription_module' => 'hrms',
            'sort_order' => 120,
        ],
        'recruitment' => [
            'module' => 'recruitment',
            'name' => 'Recruitment',
            'icon' => 'heroicon-o-briefcase',
            'route' => 'hrms.recruitment.dashboard',
            'permission_slug' => 'recruitment.view',
            'subscription_module' => 'recruitment',
            'sort_order' => 130,
        ],
        'attendance_review' => [
            'module' => 'hrms',
            'name' => 'Attendance Review',
            'icon' => 'heroicon-o-clock',
            'route' => 'hrms.attendance.index',
            'permission_slug' => 'attendance.manage',
            'subscription_module' => 'hrms',
            'sort_order' => 140,
        ],
        'record_expense' => [
            'module' => 'finance',
            'name' => 'Record Expense',
            'icon' => 'heroicon-o-receipt-percent',
            'route' => 'invoices.index',
            'permission_slug' => 'finance.view',
            'subscription_module' => 'finance',
            'sort_order' => 150,
        ],
        'create_invoice' => [
            'module' => 'finance',
            'name' => 'Create Invoice',
            'icon' => 'heroicon-o-document-currency-dollar',
            'route' => 'invoices.create',
            'permission_slug' => 'invoices.create',
            'subscription_module' => 'finance',
            'sort_order' => 160,
        ],
        'payment_collection' => [
            'module' => 'finance',
            'name' => 'Payment Collection',
            'icon' => 'heroicon-o-credit-card',
            'route' => 'payments.create',
            'permission_slug' => 'payments.create',
            'subscription_module' => 'finance',
            'sort_order' => 170,
        ],
    ],

];
