<?php

return [
    'actions' => [
        'view',
        'create',
        'edit',
        'delete',
        'restore',
        'archive',
        'approve',
        'reject',
        'export',
        'import',
        'assign',
        'manage',
        'configure',
    ],

    'permission_groups' => [
        ['name' => 'CRM', 'slug' => 'crm', 'sort_order' => 1],
        ['name' => 'Marketing', 'slug' => 'marketing', 'sort_order' => 2],
        ['name' => 'Customers', 'slug' => 'customers', 'sort_order' => 3],
        ['name' => 'Leads', 'slug' => 'leads', 'sort_order' => 4],
        ['name' => 'Opportunities', 'slug' => 'opportunities', 'sort_order' => 5],
        ['name' => 'Quotations', 'slug' => 'quotations', 'sort_order' => 6],
        ['name' => 'Invoices', 'slug' => 'invoices', 'sort_order' => 7],
        ['name' => 'Payments', 'slug' => 'payments', 'sort_order' => 8],
        ['name' => 'Products', 'slug' => 'products', 'sort_order' => 9],
        ['name' => 'Projects', 'slug' => 'projects', 'sort_order' => 10],
        ['name' => 'Tasks', 'slug' => 'tasks', 'sort_order' => 11],
        ['name' => 'HRMS', 'slug' => 'hrms', 'sort_order' => 12],
        ['name' => 'Recruitment', 'slug' => 'recruitment', 'sort_order' => 13],
        ['name' => 'Finance', 'slug' => 'finance', 'sort_order' => 14],
        ['name' => 'Inventory', 'slug' => 'inventory', 'sort_order' => 15],
        ['name' => 'Support', 'slug' => 'support', 'sort_order' => 16],
        ['name' => 'Reports', 'slug' => 'reports', 'sort_order' => 17],
        ['name' => 'Settings', 'slug' => 'settings', 'sort_order' => 18],
        ['name' => 'Integrations', 'slug' => 'integrations', 'sort_order' => 19],
        ['name' => 'Workflow', 'slug' => 'workflow', 'sort_order' => 20],
        ['name' => 'AI', 'slug' => 'ai', 'sort_order' => 21],
        ['name' => 'Administration', 'slug' => 'administration', 'sort_order' => 22],
    ],

    'module_group_map' => [
        'users' => 'administration',
        'leads' => 'leads',
        'customers' => 'customers',
        'opportunities' => 'opportunities',
        'quotations' => 'quotations',
        'invoices' => 'invoices',
        'payments' => 'payments',
        'products' => 'products',
        'reports' => 'reports',
        'finance' => 'finance',
        'tasks' => 'tasks',
        'audit' => 'administration',
        'attachments' => 'crm',
        'api' => 'integrations',
        'metadata' => 'settings',
        'settings' => 'settings',
        'imports' => 'crm',
        'assignments' => 'workflow',
        'workflows' => 'workflow',
        'hrms' => 'hrms',
        'attendance' => 'hrms',
        'leave' => 'hrms',
        'ess' => 'hrms',
        'payroll' => 'hrms',
        'recruitment' => 'recruitment',
        'performance' => 'hrms',
        'projects' => 'projects',
        'resources' => 'projects',
        'inventory' => 'inventory',
        'support' => 'support',
        'integrations' => 'integrations',
        'marketing' => 'marketing',
        'rbac' => 'administration',
    ],

    'system_roles' => [
        'platform-administrator' => [
            'name' => 'Platform Administrator',
            'description' => 'Full platform-level access within the organization.',
            'color' => '#6366f1',
            'hierarchy_level' => 100,
            'permissions' => '*',
        ],
        'organization-administrator' => [
            'name' => 'Organization Administrator',
            'description' => 'Full access to all organization features and settings.',
            'color' => '#4f46e5',
            'hierarchy_level' => 90,
            'permissions' => '*',
            'legacy_slug' => 'organization-owner',
        ],
        'department-manager' => [
            'name' => 'Department Manager',
            'description' => 'Manage teams, reports, and departmental operations.',
            'color' => '#0ea5e9',
            'hierarchy_level' => 70,
            'permissions' => 'manager',
            'legacy_slug' => 'manager',
        ],
        'project-manager' => [
            'name' => 'Project Manager',
            'description' => 'Manage projects, tasks, and team assignments.',
            'color' => '#14b8a6',
            'hierarchy_level' => 60,
            'permissions' => [
                'projects.view', 'projects.create', 'projects.edit', 'projects.delete',
                'projects.archive', 'projects.restore', 'projects.manage',
                'projects.assign-members', 'projects.manage-milestones',
                'projects.view-budget', 'projects.manage-budget',
                'projects.export', 'projects.import',
                'projects.progress.view', 'projects.progress.create', 'projects.progress.update', 'projects.progress.delete',
                'projects.health.view', 'projects.reports.view', 'projects.reports.generate',
                'projects.timeline.view', 'projects.gantt.view', 'projects.statistics.view',
                'resources.view', 'resources.allocate', 'resources.manage', 'resources.export',
                'tasks.view', 'tasks.create', 'tasks.edit', 'tasks.update', 'tasks.delete',
                'tasks.archive', 'tasks.restore', 'tasks.assign', 'tasks.comment', 'tasks.attachments',
                'tasks.time-log', 'tasks.manage-status', 'tasks.manage-priority',
                'tasks.manage-dependencies', 'tasks.manage-checklists',
                'tasks.export', 'tasks.import', 'tasks.manage',
                'dashboard.view', 'dashboard.customize',
            ],
        ],
        'team-lead' => [
            'name' => 'Team Lead',
            'description' => 'Lead team members with elevated task and user permissions.',
            'color' => '#22c55e',
            'hierarchy_level' => 50,
            'permissions' => [
                'users.view',
                'projects.view', 'projects.create', 'projects.edit', 'projects.assign-members', 'projects.manage-milestones',
                'projects.progress.view', 'projects.progress.create', 'projects.progress.update',
                'projects.health.view', 'projects.reports.view', 'projects.timeline.view', 'projects.gantt.view', 'projects.statistics.view',
                'resources.view', 'resources.allocate',
                'tasks.view', 'tasks.create', 'tasks.edit', 'tasks.update', 'tasks.delete',
                'tasks.assign', 'tasks.comment', 'tasks.attachments', 'tasks.time-log',
                'tasks.manage-checklists', 'tasks.manage-dependencies', 'tasks.manage',
                'leads.view', 'leads.create', 'leads.update',
                'customers.view', 'customers.update',
                'dashboard.view', 'dashboard.customize',
            ],
        ],
        'hr-manager' => [
            'name' => 'HR Manager',
            'description' => 'Manage HRMS, payroll, and employee operations.',
            'color' => '#f97316',
            'hierarchy_level' => 65,
            'permissions' => 'hr',
            'legacy_slug' => 'hr',
        ],
        'recruiter' => [
            'name' => 'Recruiter',
            'description' => 'Manage recruitment pipeline and candidate operations.',
            'color' => '#a855f7',
            'hierarchy_level' => 45,
            'permissions' => ['recruitment.view', 'recruitment.create', 'recruitment.edit', 'recruitment.manage', 'recruitment.interview.view', 'recruitment.interview.create', 'recruitment.interview.edit', 'recruitment.evaluate', 'recruitment.offer.view', 'recruitment.offer.create', 'recruitment.offer.edit'],
        ],
        'finance-manager' => [
            'name' => 'Finance Manager',
            'description' => 'Manage invoices, payments, and financial reports.',
            'color' => '#eab308',
            'hierarchy_level' => 65,
            'permissions' => ['invoices.view', 'invoices.create', 'invoices.edit', 'invoices.manage', 'payments.view', 'payments.create', 'payments.edit', 'payments.manage', 'finance.view', 'reports.view', 'reports.export'],
        ],
        'sales-manager' => [
            'name' => 'Sales Manager',
            'description' => 'Manage sales pipeline and team performance.',
            'color' => '#ec4899',
            'hierarchy_level' => 60,
            'permissions' => 'sales-executive',
            'legacy_slug' => 'sales-executive',
        ],
        'support-manager' => [
            'name' => 'Support Manager',
            'description' => 'Manage customer support operations.',
            'color' => '#64748b',
            'hierarchy_level' => 55,
            'permissions' => 'support',
            'legacy_slug' => 'support',
        ],
        'employee' => [
            'name' => 'Employee',
            'description' => 'Basic read access to CRM and self-service features.',
            'color' => '#94a3b8',
            'hierarchy_level' => 20,
            'permissions' => 'employee',
            'legacy_slug' => 'employee',
            'is_default' => true,
        ],
        'viewer' => [
            'name' => 'Viewer',
            'description' => 'Read-only access across permitted modules.',
            'color' => '#cbd5e1',
            'hierarchy_level' => 10,
            'permissions' => ['leads.view', 'customers.view', 'products.view', 'tasks.view', 'reports.view'],
        ],
    ],

    'rbac_permissions' => [
        'rbac.view' => ['Administration', 'View roles, permissions, and access control settings'],
        'rbac.manage' => ['Administration', 'Manage organization access control settings'],
        'rbac.roles.view' => ['Administration', 'View organization roles'],
        'rbac.roles.manage' => ['Administration', 'Create and manage organization roles'],
        'rbac.permissions.view' => ['Administration', 'View organization permissions'],
        'rbac.permissions.manage' => ['Administration', 'Manage organization permission assignments'],
        'rbac.templates.view' => ['Administration', 'View permission templates'],
        'rbac.templates.manage' => ['Administration', 'Install and manage permission templates'],
    ],

    'templates' => [
        'corporate' => [
            'name' => 'Corporate',
            'description' => 'Standard enterprise permissions with full hierarchy.',
            'is_default' => true,
            'roles' => [
                ['role_slug' => 'organization-administrator', 'hierarchy_level' => 90],
                ['role_slug' => 'department-manager', 'hierarchy_level' => 70],
                ['role_slug' => 'finance-manager', 'hierarchy_level' => 65],
                ['role_slug' => 'hr-manager', 'hierarchy_level' => 65],
                ['role_slug' => 'sales-manager', 'hierarchy_level' => 60],
                ['role_slug' => 'project-manager', 'hierarchy_level' => 60],
                ['role_slug' => 'employee', 'hierarchy_level' => 20, 'is_default' => true],
                ['role_slug' => 'viewer', 'hierarchy_level' => 10],
            ],
        ],
        'startup' => [
            'name' => 'Startup',
            'description' => 'Minimal management hierarchy for small teams.',
            'roles' => [
                ['role_slug' => 'organization-administrator', 'hierarchy_level' => 90],
                ['role_slug' => 'project-manager', 'hierarchy_level' => 60],
                ['role_slug' => 'team-lead', 'hierarchy_level' => 50],
                ['role_slug' => 'employee', 'hierarchy_level' => 20, 'is_default' => true],
            ],
        ],
        'agency' => [
            'name' => 'Agency',
            'description' => 'Project-focused permissions for client delivery teams.',
            'roles' => [
                ['role_slug' => 'organization-administrator', 'hierarchy_level' => 90],
                ['role_slug' => 'project-manager', 'hierarchy_level' => 60],
                ['role_slug' => 'team-lead', 'hierarchy_level' => 50],
                ['role_slug' => 'employee', 'hierarchy_level' => 20, 'is_default' => true],
            ],
        ],
        'healthcare' => [
            'name' => 'Healthcare',
            'description' => 'Department-based permissions for healthcare organizations.',
            'roles' => [
                ['role_slug' => 'organization-administrator', 'hierarchy_level' => 90],
                ['role_slug' => 'department-manager', 'hierarchy_level' => 70],
                ['role_slug' => 'hr-manager', 'hierarchy_level' => 65],
                ['role_slug' => 'project-manager', 'hierarchy_level' => 60],
                ['role_slug' => 'support-manager', 'hierarchy_level' => 55],
                ['role_slug' => 'employee', 'hierarchy_level' => 20, 'is_default' => true],
            ],
        ],
        'education' => [
            'name' => 'Education',
            'description' => 'Role-based academic permissions for educational institutions.',
            'roles' => [
                ['role_slug' => 'organization-administrator', 'hierarchy_level' => 90],
                ['role_slug' => 'department-manager', 'hierarchy_level' => 70],
                ['role_slug' => 'project-manager', 'hierarchy_level' => 60],
                ['role_slug' => 'team-lead', 'hierarchy_level' => 50],
                ['role_slug' => 'employee', 'hierarchy_level' => 20, 'is_default' => true],
                ['role_slug' => 'viewer', 'hierarchy_level' => 10],
            ],
        ],
    ],
];
