<?php

/**
 * Workspace navigation configuration (Phase 13.1 / 14.1).
 *
 * Items are filtered at runtime by MenuBuilder using permissions.
 * Routes must exist; missing routes are skipped safely.
 */
return [
    'workspaces' => [
        'home' => [
            'id' => 'home',
            'label' => 'Home',
            'icon' => 'home',
            'order' => 10,
            'route' => 'dashboard',
            'module' => null,
            'match' => ['dashboard', 'dashboard.*'],
        ],
        'crm' => [
            'id' => 'crm',
            'label' => 'CRM',
            'icon' => 'users',
            'order' => 20,
            'route' => 'crm.home',
            'module' => 'crm',
            'match' => ['crm.*', 'leads.*', 'customers.*', 'contacts.*', 'tickets.*', 'pipeline.*', 'products.*', 'quotations.*', 'sales-orders.*', 'invoices.*', 'payments.*', 'credit-notes.*', 'debit-notes.*', 'price-lists.*', 'receivables.*'],
            'any_permissions' => [
                'leads.view', 'customers.view', 'opportunities.view', 'products.view',
                'quotations.view', 'sales_orders.view', 'invoices.view', 'payments.view',
                'adjustment_notes.view', 'price_lists.view', 'finance.view',
            ],
        ],
        'projects' => [
            'id' => 'projects',
            'label' => 'Projects',
            'icon' => 'task',
            'order' => 30,
            'route' => 'projects.home',
            'module' => 'projects',
            'match' => [
                'projects.*', 'project-*', 'portfolios.*', 'programs.*', 'resources.*',
                'risks.*', 'issues.*', 'portfolio-reports.*',
            ],
            'any_permissions' => ['projects.view', 'resources.view', 'projects.portfolios.view', 'projects.programs.view', 'tasks.view'],
        ],
        'hr' => [
            'id' => 'hr',
            'label' => 'HRMS',
            'icon' => 'hr',
            'order' => 40,
            'route' => 'hrms.home',
            'module' => 'hrms',
            'match' => ['hrms.*', 'ess.*'],
            'any_permissions' => [
                'hrms.view', 'ess.access', 'hr.dashboard', 'manager.dashboard',
                'employee.directory', 'attendance.view', 'leave.view',
                'payroll.view', 'performance.view',
            ],
        ],
        'recruitment' => [
            'id' => 'recruitment',
            'label' => 'Recruitment',
            'icon' => 'users',
            'order' => 45,
            'route' => 'hrms.recruitment.dashboard',
            'module' => 'recruitment',
            'match' => ['hrms.recruitment.*'],
            'any_permissions' => ['recruitment.view'],
        ],
        'marketing' => [
            'id' => 'marketing',
            'label' => 'Marketing',
            'icon' => 'chart',
            'order' => 50,
            'route' => 'marketing.home',
            'module' => 'marketing',
            'any_permissions' => ['marketing.view', 'marketing.manage', 'integrations.view', 'integrations.manage'],
            'hide_when_empty' => true,
            'match' => ['marketing.*'],
        ],
        'operations' => [
            'id' => 'operations',
            'label' => 'Operations',
            'icon' => 'task',
            'order' => 60,
            'route' => 'operations.home',
            'module' => 'tasks',
            'any_permissions' => ['tasks.view'],
            'match' => ['operations.*', 'tasks.*'],
        ],
        'analytics' => [
            'id' => 'analytics',
            'label' => 'Reports',
            'icon' => 'chart',
            'order' => 70,
            'route' => 'analytics.home',
            'module' => 'analytics',
            'any_permissions' => ['reports.view', 'finance.view', 'audit.view', 'projects.reports.view', 'recruitment.reports.view'],
            'match' => ['analytics.*', 'reports.*'],
        ],
        'administration' => [
            'id' => 'administration',
            'label' => 'Administration',
            'icon' => 'cog',
            'order' => 80,
            'route' => 'administration.home',
            'module' => null,
            'match' => [
                'administration.*',
                'organization.settings.*',
                'organization.edit',
                'team.*',
                'rbac.*',
                'workflows.*',
                'metadata-fields.*',
                'integrations.*',
                'api-tokens.*',
                'audit-logs.*',
            ],
            'any_permissions' => [
                'settings.manage', 'users.view', 'rbac.view', 'workflows.view',
                'metadata.view', 'metadata.manage', 'integrations.view', 'integrations.manage',
                'api.tokens', 'audit.view', 'assignments.view',
            ],
            'footer' => true,
        ],
    ],

    'menus' => [
        'home' => [
            [
                'label' => 'Dashboard',
                'route' => 'dashboard',
                'match' => ['dashboard'],
                'icon' => 'home',
                'permission' => null,
            ],
        ],
        'crm' => [
            [
                'label' => 'Dashboard',
                'route' => 'crm.home',
                'match' => ['crm.home'],
                'icon' => 'home',
                'any_permissions' => [
                    'leads.view', 'customers.view', 'opportunities.view', 'products.view',
                    'quotations.view', 'sales_orders.view', 'invoices.view', 'payments.view',
                    'adjustment_notes.view', 'price_lists.view', 'finance.view',
                ],
            ],
            [
                'label' => 'Leads',
                'route' => 'leads.index',
                'match' => ['leads.*'],
                'icon' => 'users',
                'permission' => 'leads.view',
                'term' => 'leads',
            ],
            [
                'label' => 'Customers',
                'route' => 'customers.index',
                'match' => ['customers.*'],
                'icon' => 'building',
                'permission' => 'customers.view',
                'term' => 'customers',
            ],
            [
                'label' => 'Contacts',
                'route' => 'contacts.index',
                'match' => ['contacts.*'],
                'icon' => 'users',
                'permission' => 'customers.view',
            ],
            [
                'label' => 'Tickets',
                'route' => 'tickets.index',
                'match' => ['tickets.*'],
                'icon' => 'task',
                'permission' => 'customers.view',
            ],
            [
                'label' => 'Pipeline',
                'route' => 'pipeline.index',
                'match' => ['pipeline.*'],
                'icon' => 'chart',
                'permission' => 'opportunities.view',
                'term' => 'pipeline',
            ],
            [
                'label' => 'Activities',
                'route' => 'crm.activities',
                'match' => ['crm.activities', 'crm.activities.*'],
                'icon' => 'task',
                'any_permissions' => ['customers.view', 'leads.view', 'opportunities.view'],
            ],
            [
                'label' => 'Communications',
                'route' => 'crm.communications.index',
                'match' => ['crm.communications.*'],
                'icon' => 'receipt',
                'any_permissions' => ['crm_email.view', 'customers.view'],
            ],
            [
                'label' => 'Products',
                'route' => 'products.index',
                'match' => ['products.*'],
                'icon' => 'box',
                'permission' => 'products.view',
                'term' => 'products',
            ],
            [
                'label' => 'Sales Orders',
                'route' => 'sales-orders.index',
                'match' => ['sales-orders.*'],
                'icon' => 'receipt',
                'permission' => 'sales_orders.view',
                'term' => 'sales_orders',
            ],
            [
                'label' => 'Invoices',
                'route' => 'invoices.index',
                'match' => ['invoices.*'],
                'icon' => 'receipt',
                'permission' => 'invoices.view',
                'term' => 'invoices',
            ],
            [
                'label' => 'Payments',
                'route' => 'payments.index',
                'match' => ['payments.*'],
                'icon' => 'payment',
                'permission' => 'payments.view',
                'term' => 'payments',
            ],
            [
                'label' => 'Receivables',
                'route' => 'receivables.index',
                'match' => ['receivables.*'],
                'icon' => 'chart',
                'any_permissions' => ['finance.view', 'invoices.view'],
            ],
            [
                'label' => 'Credit Notes',
                'route' => 'credit-notes.index',
                'match' => ['credit-notes.*'],
                'icon' => 'receipt',
                'permission' => 'adjustment_notes.view',
                'term' => 'credit_notes',
            ],
            [
                'label' => 'Debit Notes',
                'route' => 'debit-notes.index',
                'match' => ['debit-notes.*'],
                'icon' => 'receipt',
                'permission' => 'adjustment_notes.view',
                'term' => 'debit_notes',
            ],
            [
                'label' => 'Price Lists',
                'route' => 'price-lists.index',
                'match' => ['price-lists.*'],
                'icon' => 'box',
                'permission' => 'price_lists.view',
                'term' => 'price_lists',
            ],
            [
                'label' => 'Quotations',
                'route' => 'quotations.index',
                'match' => ['quotations.*'],
                'icon' => 'receipt',
                'permission' => 'quotations.view',
                'term' => 'quotations',
                'tier' => 'extended',
            ],
            [
                'label' => 'Revenue',
                'route' => 'crm.revenue',
                'match' => ['crm.revenue'],
                'icon' => 'chart',
                'any_permissions' => ['quotations.view', 'sales_orders.view', 'invoices.view', 'payments.view'],
                'tier' => 'extended',
            ],
            [
                'label' => 'Reports',
                'route' => 'crm.reports',
                'match' => ['crm.reports', 'reports.index', 'reports.finance', 'reports.export.*'],
                'icon' => 'chart',
                'permission' => 'reports.view',
            ],
            [
                'label' => 'Imports',
                'route' => 'leads.import.create',
                'match' => ['leads.import.*', 'customers.import.*'],
                'icon' => 'box',
                'permission' => 'imports.create',
                'tier' => 'extended',
            ],
            [
                'label' => 'Exports',
                'route' => 'crm.exports',
                'match' => ['crm.exports'],
                'icon' => 'box',
                'any_permissions' => ['reports.view', 'invoices.view', 'customers.view'],
                'tier' => 'extended',
            ],
            [
                'label' => 'Saved Views',
                'route' => 'crm.saved-views',
                'match' => ['crm.saved-views'],
                'icon' => 'fields',
                'any_permissions' => ['leads.view', 'customers.view', 'opportunities.view'],
                'tier' => 'extended',
            ],
        ],
        'projects' => [
            [
                'label' => 'Dashboard',
                'route' => 'projects.home',
                'match' => ['projects.home'],
                'icon' => 'home',
                'any_permissions' => [
                    'projects.view', 'resources.view', 'projects.portfolios.view', 'projects.programs.view', 'tasks.view',
                ],
            ],
            [
                'label' => 'Projects',
                'route' => 'projects.index',
                'match' => ['projects.index', 'projects.create', 'projects.store', 'projects.show', 'projects.edit', 'projects.update', 'projects.destroy', 'projects.archive', 'projects.restore', 'projects.dashboard', 'projects.executive', 'projects.watching', 'projects.automation', 'project-*'],
                'icon' => 'task',
                'permission' => 'projects.view',
            ],
            [
                'label' => 'Tasks',
                'route' => 'tasks.index',
                'match' => ['tasks.*'],
                'icon' => 'task',
                'permission' => 'tasks.view',
            ],
            [
                'label' => 'Milestones',
                'route' => 'projects.milestones.hub',
                'match' => ['projects.milestones.hub', 'projects.milestones.*'],
                'icon' => 'chart',
                'permission' => 'projects.view',
            ],
            [
                'label' => 'Calendar',
                'route' => 'projects.calendar',
                'match' => ['projects.calendar', 'projects.calendar.*'],
                'icon' => 'task',
                'permission' => 'projects.view',
            ],
            [
                'label' => 'Resources',
                'icon' => 'chart',
                'permission' => 'resources.view',
                'tier' => 'extended',
                'children' => [
                    [
                        'label' => 'Planner',
                        'route' => 'resources.planner',
                        'match' => ['resources.planner'],
                        'permission' => 'resources.view',
                    ],
                    [
                        'label' => 'Capacity',
                        'route' => 'resources.capacity',
                        'match' => ['resources.capacity'],
                        'permission' => 'resources.view',
                    ],
                    [
                        'label' => 'Workload',
                        'route' => 'resources.timeline',
                        'match' => ['resources.timeline', 'resources.employees.workload'],
                        'permission' => 'resources.view',
                    ],
                    [
                        'label' => 'Allocations',
                        'route' => 'resources.allocations.index',
                        'match' => ['resources.allocations.*'],
                        'permission' => 'resources.view',
                    ],
                    [
                        'label' => 'Resource Calendars',
                        'route' => 'resources.calendars.index',
                        'match' => ['resources.calendars.*'],
                        'permission' => 'resources.view',
                    ],
                ],
            ],
            [
                'label' => 'Portfolios',
                'route' => 'portfolios.index',
                'match' => ['portfolios.*'],
                'icon' => 'chart',
                'permission' => 'projects.portfolios.view',
            ],
            [
                'label' => 'Programs',
                'route' => 'programs.index',
                'match' => ['programs.*'],
                'icon' => 'chart',
                'permission' => 'projects.programs.view',
            ],
            [
                'label' => 'Risks',
                'route' => 'risks.index',
                'match' => ['risks.*', 'projects.risks.*'],
                'icon' => 'shield',
                'permission' => 'projects.view',
                'tier' => 'extended',
            ],
            [
                'label' => 'Issues',
                'route' => 'issues.index',
                'match' => ['issues.*', 'projects.issues.*'],
                'icon' => 'shield',
                'permission' => 'projects.view',
                'tier' => 'extended',
            ],
            [
                'label' => 'Budgets',
                'route' => 'projects.budgets.hub',
                'match' => ['projects.budgets.hub', 'projects.budgets.*'],
                'icon' => 'receipt',
                'permission' => 'projects.view',
                'tier' => 'extended',
            ],
            [
                'label' => 'Forecasts',
                'route' => 'portfolios.forecasts.index',
                'match' => ['portfolios.forecasts.*', 'resources.forecast'],
                'icon' => 'chart',
                'any_permissions' => ['projects.portfolios.view', 'resources.view'],
                'tier' => 'extended',
            ],
            [
                'label' => 'Reports',
                'route' => 'projects.reports.hub',
                'match' => ['projects.reports.hub', 'portfolio-reports.*', 'projects.reports.*'],
                'icon' => 'chart',
                'any_permissions' => ['projects.view', 'reports.view', 'projects.portfolios.view'],
            ],
        ],
        'hr' => [
            [
                'label' => 'Dashboard',
                'route' => 'hrms.home',
                'match' => ['hrms.home', 'hrms.dashboard'],
                'icon' => 'home',
                'any_permissions' => [
                    'hrms.view', 'ess.access', 'hr.dashboard', 'manager.dashboard',
                    'employee.directory', 'attendance.view', 'leave.view',
                    'recruitment.view', 'payroll.view', 'performance.view',
                ],
            ],
            [
                'label' => 'Employees',
                'route' => 'hrms.employees.index',
                'match' => ['hrms.employees.*', 'hrms.directory.*'],
                'icon' => 'users',
                'any_permissions' => ['hrms.view', 'employee.directory'],
                'children' => [
                    [
                        'label' => 'Directory',
                        'route' => 'hrms.directory.index',
                        'match' => ['hrms.directory.*'],
                        'permission' => 'employee.directory',
                    ],
                    [
                        'label' => 'Employees',
                        'route' => 'hrms.employees.index',
                        'match' => ['hrms.employees.*'],
                        'permission' => 'hrms.view',
                    ],
                    [
                        'label' => 'Teams',
                        'route' => 'hrms.teams.index',
                        'match' => ['hrms.teams.*'],
                        'permission' => 'hrms.view',
                    ],
                    [
                        'label' => 'Departments',
                        'route' => 'hrms.departments.index',
                        'match' => ['hrms.departments.*'],
                        'permission' => 'hrms.view',
                    ],
                    [
                        'label' => 'Branches',
                        'route' => 'hrms.branches.index',
                        'match' => ['hrms.branches.*'],
                        'permission' => 'hrms.view',
                    ],
                    [
                        'label' => 'Designations',
                        'route' => 'hrms.designations.index',
                        'match' => ['hrms.designations.*'],
                        'permission' => 'hrms.view',
                    ],
                ],
            ],
            [
                'label' => 'Attendance',
                'route' => 'hrms.attendance.index',
                'match' => ['hrms.attendance.*'],
                'icon' => 'hr',
                'permission' => 'attendance.view',
                'children' => [
                    [
                        'label' => 'Calendar',
                        'route' => 'hrms.attendance.index',
                        'match' => ['hrms.attendance.index'],
                        'permission' => 'attendance.view',
                    ],
                    [
                        'label' => 'Records',
                        'route' => 'hrms.attendance.records',
                        'match' => ['hrms.attendance.records', 'hrms.attendance.show'],
                        'permission' => 'attendance.view',
                    ],
                    [
                        'label' => 'Daily Summary',
                        'route' => 'hrms.attendance.summary',
                        'match' => ['hrms.attendance.summary'],
                        'permission' => 'attendance.view',
                    ],
                    [
                        'label' => 'Reports',
                        'route' => 'hrms.attendance.reports.index',
                        'match' => ['hrms.attendance.reports.*'],
                        'permission' => 'attendance.view',
                    ],
                    [
                        'label' => 'Corrections',
                        'route' => 'hrms.attendance.corrections.index',
                        'match' => ['hrms.attendance.corrections.*'],
                        'permission' => 'attendance.view',
                    ],
                    [
                        'label' => 'Geofences',
                        'route' => 'hrms.attendance.geofences.index',
                        'match' => ['hrms.attendance.geofences.*'],
                        'permission' => 'attendance.view',
                    ],
                ],
            ],
            [
                'label' => 'WFH',
                'route' => 'hrms.wfh.requests.index',
                'match' => ['hrms.wfh.*'],
                'icon' => 'hr',
                'permission' => 'wfh.view',
                'children' => [
                    [
                        'label' => 'WFH Requests',
                        'route' => 'hrms.wfh.requests.index',
                        'match' => ['hrms.wfh.requests.*'],
                        'permission' => 'wfh.view',
                    ],
                    [
                        'label' => 'Approval Queue',
                        'route' => 'hrms.wfh.requests.approval-queue',
                        'match' => ['hrms.wfh.requests.approval-queue'],
                        'permission' => 'wfh.approve',
                    ],
                    [
                        'label' => 'Assignments',
                        'route' => 'hrms.wfh.assignments.index',
                        'match' => ['hrms.wfh.assignments.*'],
                        'permission' => 'wfh.manage',
                    ],
                ],
            ],
            [
                'label' => 'Leave',
                'route' => 'hrms.leave.dashboard',
                'match' => ['hrms.leave.*', 'hrms.leave-applications.*', 'hrms.leave-balances.*', 'hrms.leave-types.*', 'hrms.holidays.*'],
                'icon' => 'hr',
                'permission' => 'leave.view',
                'children' => [
                    [
                        'label' => 'Leave Dashboard',
                        'route' => 'hrms.leave.dashboard',
                        'match' => ['hrms.leave.dashboard'],
                        'permission' => 'leave.view',
                    ],
                    [
                        'label' => 'Leave Requests',
                        'route' => 'hrms.leave-applications.index',
                        'match' => ['hrms.leave-applications.*'],
                        'permission' => 'leave.view',
                    ],
                    [
                        'label' => 'Approval Queue',
                        'route' => 'hrms.leave-applications.approval-queue',
                        'match' => ['hrms.leave-applications.approval-queue'],
                        'permission' => 'leave.approve',
                    ],
                    [
                        'label' => 'Leave Balances',
                        'route' => 'hrms.leave-balances.index',
                        'match' => ['hrms.leave-balances.*'],
                        'permission' => 'leave.view',
                    ],
                    [
                        'label' => 'Leave Types',
                        'route' => 'hrms.leave-types.index',
                        'match' => ['hrms.leave-types.*'],
                        'permission' => 'leave.view',
                    ],
                    [
                        'label' => 'Holidays',
                        'route' => 'hrms.holidays.index',
                        'match' => ['hrms.holidays.*'],
                        'permission' => 'leave.view',
                    ],
                ],
            ],
            [
                'label' => 'Shifts',
                'route' => 'hrms.shifts.index',
                'match' => ['hrms.shifts.*', 'hrms.shift-assignments.*'],
                'icon' => 'hr',
                'permission' => 'attendance.view',
                'children' => [
                    [
                        'label' => 'Shifts',
                        'route' => 'hrms.shifts.index',
                        'match' => ['hrms.shifts.*'],
                        'permission' => 'attendance.view',
                    ],
                    [
                        'label' => 'Shift Assignments',
                        'route' => 'hrms.shift-assignments.index',
                        'match' => ['hrms.shift-assignments.*'],
                        'permission' => 'attendance.view',
                    ],
                ],
            ],
            [
                'label' => 'Payroll',
                'route' => 'hrms.payroll.index',
                'match' => ['hrms.payroll.*'],
                'icon' => 'payment',
                'permission' => 'payroll.view',
            ],
            [
                'label' => 'Performance',
                'route' => 'hrms.performance.index',
                'match' => ['hrms.performance.*'],
                'icon' => 'hr',
                'any_permissions' => ['performance.view', 'performance.goal.view', 'performance.review.view'],
            ],
            [
                'label' => 'Assets',
                'route' => 'hrms.assets.index',
                'match' => ['hrms.assets.*'],
                'icon' => 'box',
                'permission' => 'assets.view',
            ],
            [
                'label' => 'Documents',
                'route' => 'hrms.employees.index',
                'match' => ['hrms.employees.documents.*'],
                'icon' => 'fields',
                'permission' => 'hrms.view',
                'tier' => 'extended',
            ],
            [
                'label' => 'Reports',
                'route' => 'hrms.payroll.index',
                'match' => ['hrms.payroll.reports.*'],
                'icon' => 'chart',
                'any_permissions' => ['payroll.view', 'reports.view'],
                'tier' => 'extended',
            ],
            [
                'label' => 'Configuration',
                'icon' => 'settings',
                'tier' => 'extended',
                'any_permissions' => ['hrms.view', 'leave.view', 'attendance.view'],
                'children' => [
                    [
                        'label' => 'Departments',
                        'route' => 'hrms.departments.index',
                        'match' => ['hrms.departments.*'],
                        'permission' => 'hrms.view',
                    ],
                    [
                        'label' => 'Branches',
                        'route' => 'hrms.branches.index',
                        'match' => ['hrms.branches.*'],
                        'permission' => 'hrms.view',
                    ],
                    [
                        'label' => 'Designations',
                        'route' => 'hrms.designations.index',
                        'match' => ['hrms.designations.*'],
                        'permission' => 'hrms.view',
                    ],
                    [
                        'label' => 'Holiday Calendar',
                        'route' => 'hrms.holidays.index',
                        'match' => ['hrms.holidays.*'],
                        'permission' => 'leave.view',
                    ],
                    [
                        'label' => 'Leave Types',
                        'route' => 'hrms.leave-types.index',
                        'match' => ['hrms.leave-types.*'],
                        'permission' => 'leave.view',
                    ],
                    [
                        'label' => 'Shift Management',
                        'route' => 'hrms.shifts.index',
                        'match' => ['hrms.shifts.*'],
                        'permission' => 'attendance.view',
                    ],
                ],
            ],
            [
                'label' => 'My HR',
                'icon' => 'user',
                'any_permissions' => ['ess.access'],
                'children' => [
                    [
                        'label' => 'My Dashboard',
                        'route' => 'ess.dashboard',
                        'match' => ['ess.dashboard'],
                        'permission' => 'ess.access',
                    ],
                    [
                        'label' => 'My Profile',
                        'route' => 'ess.profile',
                        'match' => ['ess.profile*'],
                        'permission' => 'ess.access',
                    ],
                    [
                        'label' => 'My Documents',
                        'route' => 'ess.documents.index',
                        'match' => ['ess.documents.*'],
                        'permission' => 'ess.access',
                    ],
                    [
                        'label' => 'My Attendance',
                        'route' => 'ess.attendance.index',
                        'match' => ['ess.attendance.*'],
                        'permission' => 'ess.access',
                    ],
                    [
                        'label' => 'My Leave',
                        'route' => 'ess.leave.index',
                        'match' => ['ess.leave.*'],
                        'permission' => 'ess.access',
                    ],
                    [
                        'label' => 'Work From Home',
                        'route' => 'ess.wfh.index',
                        'match' => ['ess.wfh.*'],
                        'permission' => 'ess.access',
                    ],
                    [
                        'label' => 'My Payroll',
                        'route' => 'ess.payroll.index',
                        'match' => ['ess.payroll.*'],
                        'permission' => 'ess.access',
                    ],
                ],
            ],
            [
                'label' => 'More',
                'icon' => 'hr',
                'tier' => 'extended',
                'children' => [
                    [
                        'label' => 'Announcements',
                        'route' => 'hrms.announcements.index',
                        'match' => ['hrms.announcements.*'],
                        'permission' => 'announcements.manage',
                    ],
                    [
                        'label' => 'Exit Processes',
                        'route' => 'hrms.exit-processes.index',
                        'match' => ['hrms.exit-processes.*'],
                        'permission' => 'employee.exit.manage',
                    ],
                    [
                        'label' => 'Calendar',
                        'route' => 'hrms.calendar',
                        'match' => ['hrms.calendar'],
                        'permission' => 'organization.calendar',
                    ],
                    [
                        'label' => 'Manager Dashboard',
                        'route' => 'hrms.manager.dashboard',
                        'match' => ['hrms.manager.dashboard'],
                        'permission' => 'manager.dashboard',
                    ],
                    [
                        'label' => 'Legacy HR Dashboard',
                        'route' => 'hrms.dashboard',
                        'match' => ['hrms.dashboard'],
                        'permission' => 'hr.dashboard',
                    ],
                ],
            ],
        ],
        'marketing' => [
            [
                'label' => 'Overview',
                'route' => 'marketing.home',
                'match' => ['marketing.home'],
                'icon' => 'home',
                'any_permissions' => ['marketing.view', 'marketing.manage', 'integrations.view', 'integrations.manage'],
            ],
            [
                'label' => 'Campaigns',
                'route' => 'marketing.campaigns.index',
                'match' => ['marketing.campaigns.*'],
                'icon' => 'chart',
                'any_permissions' => ['marketing.view', 'marketing.manage', 'integrations.view', 'integrations.manage'],
            ],
            [
                'label' => 'Attribution',
                'route' => 'marketing.attribution.index',
                'match' => ['marketing.attribution.*'],
                'icon' => 'chart',
                'any_permissions' => ['marketing.view', 'marketing.manage', 'integrations.view', 'integrations.manage'],
            ],
            [
                'label' => 'Providers',
                'route' => 'marketing.providers.index',
                'match' => ['marketing.providers.*'],
                'icon' => 'shield',
                'any_permissions' => ['marketing.view', 'marketing.manage', 'integrations.view', 'integrations.manage'],
            ],
            [
                'label' => 'Integrations',
                'route' => 'integrations.index',
                'match' => ['integrations.*'],
                'icon' => 'shield',
                'any_permissions' => ['integrations.view', 'integrations.manage', 'marketing.view'],
            ],
        ],
        'recruitment' => [
            [
                'label' => 'Recruitment Home',
                'route' => 'hrms.recruitment.dashboard',
                'match' => ['hrms.recruitment.dashboard', 'hrms.recruitment.executive', 'hrms.recruitment.analytics'],
                'icon' => 'home',
                'permission' => 'recruitment.view',
            ],
            [
                'label' => 'Job Openings',
                'route' => 'hrms.recruitment.openings.index',
                'match' => ['hrms.recruitment.openings.*'],
                'icon' => 'task',
                'permission' => 'recruitment.view',
            ],
            [
                'label' => 'Candidates',
                'route' => 'hrms.recruitment.candidates.index',
                'match' => ['hrms.recruitment.candidates.*'],
                'icon' => 'users',
                'permission' => 'recruitment.view',
            ],
            [
                'label' => 'Applications',
                'route' => 'hrms.recruitment.applications.index',
                'match' => ['hrms.recruitment.applications.*'],
                'icon' => 'doc',
                'permission' => 'recruitment.view',
            ],
            [
                'label' => 'Interviews',
                'route' => 'hrms.recruitment.interview-rounds.index',
                'match' => ['hrms.recruitment.interview-rounds.*'],
                'icon' => 'hr',
                'permission' => 'recruitment.view',
            ],
            [
                'label' => 'Reports',
                'route' => 'hrms.recruitment.reports.index',
                'match' => ['hrms.recruitment.reports.*', 'hrms.recruitment.exports.*'],
                'icon' => 'chart',
                'permission' => 'recruitment.view',
                'tier' => 'extended',
            ],
        ],
        'operations' => [
            [
                'label' => 'Tasks',
                'route' => 'tasks.index',
                'match' => ['tasks.*'],
                'icon' => 'task',
                'permission' => 'tasks.view',
            ],
        ],
        'analytics' => [
            [
                'label' => 'Overview',
                'route' => 'analytics.home',
                'match' => ['analytics.home'],
                'icon' => 'home',
                'any_permissions' => ['reports.view', 'finance.view', 'audit.view', 'projects.reports.view', 'recruitment.reports.view'],
            ],
            [
                'label' => 'Executive',
                'route' => 'analytics.executive',
                'match' => ['analytics.executive'],
                'icon' => 'chart',
                'any_permissions' => ['reports.view', 'projects.executive.view', 'finance.view'],
            ],
            [
                'label' => 'CRM Analytics',
                'route' => 'analytics.crm',
                'match' => ['analytics.crm'],
                'icon' => 'chart',
                'permission' => 'reports.view',
            ],
            [
                'label' => 'Project Analytics',
                'route' => 'analytics.projects',
                'match' => ['analytics.projects'],
                'icon' => 'chart',
                'any_permissions' => ['reports.view', 'projects.reports.view'],
            ],
            [
                'label' => 'HR Analytics',
                'route' => 'analytics.hr',
                'match' => ['analytics.hr'],
                'icon' => 'chart',
                'any_permissions' => ['reports.view', 'recruitment.reports.view', 'hrms.view'],
            ],
            [
                'label' => 'AI Insights',
                'route' => 'analytics.ai-insights',
                'match' => ['analytics.ai-insights'],
                'icon' => 'chart',
                'any_permissions' => ['reports.view', 'finance.view'],
            ],
            [
                'label' => 'Dashboards',
                'route' => 'analytics.dashboards.index',
                'match' => ['analytics.dashboards.*'],
                'icon' => 'chart',
                'permission' => 'reports.view',
            ],
            [
                'label' => 'KPI Library',
                'route' => 'analytics.kpis.index',
                'match' => ['analytics.kpis.*'],
                'icon' => 'chart',
                'permission' => 'reports.view',
            ],
            [
                'label' => 'Reports Center',
                'route' => 'analytics.reports.index',
                'match' => ['analytics.reports.*'],
                'icon' => 'chart',
                'permission' => 'reports.view',
            ],
            [
                'label' => 'Sales Reports',
                'route' => 'reports.index',
                'match' => ['reports.index'],
                'icon' => 'chart',
                'permission' => 'reports.view',
            ],
            [
                'label' => 'Finance',
                'route' => 'reports.finance',
                'match' => ['reports.finance'],
                'icon' => 'chart',
                'any_permissions' => ['reports.view', 'finance.view'],
            ],
            [
                'label' => 'Audit Log',
                'route' => 'audit-logs.index',
                'match' => ['audit-logs.*'],
                'icon' => 'shield',
                'permission' => 'audit.view',
            ],
        ],
        'administration' => [
            [
                'label' => 'Overview',
                'route' => 'administration.home',
                'match' => ['administration.home'],
                'icon' => 'home',
                'any_permissions' => [
                    'settings.manage', 'users.view', 'rbac.view', 'workflows.view',
                    'metadata.view', 'metadata.manage', 'integrations.view', 'integrations.manage',
                    'api.tokens', 'audit.view', 'assignments.view',
                ],
            ],
            [
                'label' => 'Users',
                'route' => 'team.index',
                'match' => ['team.*'],
                'icon' => 'users',
                'permission' => 'users.view',
            ],
            [
                'label' => 'Roles',
                'route' => 'rbac.roles.index',
                'match' => ['rbac.*'],
                'icon' => 'shield',
                'permission' => 'rbac.view',
            ],
            [
                'label' => 'Configuration Hub',
                'route' => 'organization.settings.hub',
                'match' => ['organization.settings.*', 'organization.edit'],
                'icon' => 'cog',
                'permission' => 'settings.manage',
            ],
            [
                'label' => 'Assignment Settings',
                'route' => 'organization.settings.assignments.index',
                'match' => ['organization.settings.assignments.*'],
                'icon' => 'users',
                'permission' => 'assignments.view',
            ],
            [
                'label' => 'Modules',
                'route' => 'administration.modules.index',
                'match' => ['administration.modules.*'],
                'icon' => 'fields',
                'permission' => 'settings.manage',
            ],
            [
                'label' => 'Branding',
                'route' => 'administration.branding.edit',
                'match' => ['administration.branding.*'],
                'icon' => 'cog',
                'permission' => 'settings.manage',
            ],
            [
                'label' => 'Email Templates',
                'route' => 'organization.settings.email-templates.index',
                'match' => ['organization.settings.email-templates.*'],
                'icon' => 'cog',
                'any_permissions' => ['settings.manage', 'email_templates.manage'],
            ],
            [
                'label' => 'Import Center',
                'route' => 'administration.imports.index',
                'match' => ['administration.imports.*'],
                'icon' => 'fields',
                'any_permissions' => ['imports.view', 'imports.create', 'imports.manage'],
            ],
            [
                'label' => 'Export Center',
                'route' => 'administration.exports.index',
                'match' => ['administration.exports.*'],
                'icon' => 'fields',
                'any_permissions' => ['exports.view', 'exports.create', 'exports.manage'],
            ],
            [
                'label' => 'Bulk Operations',
                'route' => 'administration.bulk.index',
                'match' => ['administration.bulk.*'],
                'icon' => 'fields',
                'any_permissions' => ['bulk.view', 'bulk.manage'],
            ],
            [
                'label' => 'Integrations',
                'route' => 'integrations.index',
                'match' => ['integrations.*'],
                'icon' => 'shield',
                'any_permissions' => ['integrations.view', 'integrations.manage'],
            ],
            [
                'label' => 'Developer',
                'route' => 'administration.developer.index',
                'match' => ['administration.developer.*', 'api-tokens.*'],
                'icon' => 'shield',
                'any_permissions' => ['settings.manage', 'api.tokens'],
            ],
            [
                'label' => 'Security',
                'route' => 'administration.security.index',
                'match' => ['administration.security.*'],
                'icon' => 'shield',
                'permission' => 'settings.manage',
            ],
            [
                'label' => 'Audit Logs',
                'route' => 'audit-logs.index',
                'match' => ['audit-logs.*'],
                'icon' => 'shield',
                'permission' => 'audit.view',
            ],
            [
                'label' => 'Workflows',
                'route' => 'workflows.index',
                'match' => ['workflows.*'],
                'icon' => 'workflow',
                'permission' => 'workflows.view',
            ],
            [
                'label' => 'Metadata Fields',
                'route' => 'metadata-fields.index',
                'match' => ['metadata-fields.*'],
                'icon' => 'fields',
                'any_permissions' => ['metadata.view', 'metadata.manage'],
            ],
        ],
    ],

    'route_workspace_map' => [
        'dashboard' => 'home',
        'dashboard.*' => 'home',
        'crm.*' => 'crm',
        'leads.*' => 'crm',
        'customers.*' => 'crm',
        'contacts.*' => 'crm',
        'tickets.*' => 'crm',
        'pipeline.*' => 'crm',
        'products.*' => 'crm',
        'quotations.*' => 'crm',
        'sales-orders.*' => 'crm',
        'invoices.*' => 'crm',
        'payments.*' => 'crm',
        'receivables.*' => 'crm',
        'credit-notes.*' => 'crm',
        'debit-notes.*' => 'crm',
        'price-lists.*' => 'crm',
        'projects.*' => 'projects',
        'project-*' => 'projects',
        'portfolios.*' => 'projects',
        'programs.*' => 'projects',
        'resources.*' => 'projects',
        'project-risks.*' => 'projects',
        'project-issues.*' => 'projects',
        'risks.*' => 'projects',
        'issues.*' => 'projects',
        'portfolio-reports.*' => 'projects',
        'hrms.recruitment.*' => 'recruitment',
        'hrms.*' => 'hr',
        'ess.*' => 'hr',
        'tasks.*' => 'operations',
        'operations.*' => 'operations',
        'reports.finance' => 'crm',
        'reports.export.outstanding' => 'crm',
        'reports.export.revenue' => 'crm',
        'reports.*' => 'analytics',
        'analytics.*' => 'analytics',
        'marketing.*' => 'marketing',
        'audit-logs.*' => 'administration',
        'administration.*' => 'administration',
        'organization.settings.*' => 'administration',
        'organization.edit' => 'administration',
        'team.*' => 'administration',
        'rbac.*' => 'administration',
        'workflows.*' => 'administration',
        'metadata-fields.*' => 'administration',
        'integrations.*' => 'administration',
        'api-tokens.*' => 'administration',
        'knowledge.*' => 'home',
        'profile.*' => 'home',
        'notifications.*' => 'home',
        'search.*' => 'home',
    ],

    'recents' => [
        'max' => 10,
        'record_patterns' => [
            'crm.*',
            'leads.*',
            'customers.*',
            'contacts.*',
            'tickets.*',
            'pipeline.*',
            'projects.*',
            'tasks.*',
            'operations.*',
            'hrms.*',
            'ess.*',
            'administration.*',
            'analytics.*',
            'marketing.*',
        ],
        'skip_patterns' => [
            'shell.*',
            'dashboard.api',
            'dashboard.widgets.*',
            'dashboard.preferences.*',
            'dashboard.quick-actions.*',
            'dashboard.recent-activities',
        ],
        'route_labels' => [
            'crm.home' => 'CRM Home',
            'projects.home' => 'Projects Home',
            'hrms.home' => 'HR Home',
            'operations.home' => 'Operations Home',
            'administration.home' => 'Administration Home',
            'marketing.home' => 'Marketing Home',
            'analytics.home' => 'Analytics Home',
            'ess.dashboard' => 'ESS Dashboard',
            'hrms.manager.dashboard' => 'Manager Dashboard',
            'leads.index' => 'Leads',
            'customers.index' => 'Customers',
            'tasks.index' => 'Tasks',
            'tasks.board' => 'Task Board',
            'tasks.list' => 'Task List',
        ],
    ],

    'persona_landing_pages' => [
        'default' => 'crm.home',
        'owner' => 'crm.home',
        'sales' => 'crm.home',
        'employee' => 'ess.dashboard',
        'manager' => 'hrms.manager.dashboard',
        'hr' => 'hrms.home',
        'project_manager' => 'projects.home',
        'admin' => 'administration.home',
        'reports' => 'analytics.home',
    ],

    'persona_default_workspaces' => [
        'default' => 'crm',
        'owner' => 'crm',
        'sales' => 'crm',
        'employee' => 'hr',
        'manager' => 'hr',
        'hr' => 'hr',
        'project_manager' => 'projects',
        'admin' => 'administration',
        'reports' => 'analytics',
    ],

    'workspace_search_scopes' => [
        'crm' => 'leads',
        'projects' => 'projects',
        'hr' => 'employees',
        'recruitment' => 'employees',
        'operations' => 'tasks',
        'administration' => 'users',
        'marketing' => 'marketing_campaigns',
        'analytics' => 'all',
        'home' => 'all',
    ],

    'quick_action_limits' => [
        'primary' => 5,
        'tablet' => 3,
        'mobile' => 0,
    ],

    'quick_actions' => [
        'home' => [
            ['label' => 'Create Task', 'route' => 'tasks.create', 'permission' => 'tasks.create', 'variant' => 'primary', 'priority' => 10, 'group' => 'primary'],
            ['label' => 'Create Lead', 'route' => 'leads.create', 'permission' => 'leads.create', 'priority' => 20, 'group' => 'primary'],
            ['label' => 'Mark Attendance', 'route' => 'ess.attendance.index', 'permission' => 'ess.access', 'priority' => 30, 'group' => 'primary'],
            ['label' => 'Apply Leave', 'route' => 'ess.leave.index', 'permission' => 'ess.access', 'priority' => 40, 'group' => 'secondary'],
        ],
        'crm' => [
            ['label' => 'Create Lead', 'route' => 'leads.create', 'permission' => 'leads.create', 'variant' => 'primary', 'priority' => 10, 'group' => 'primary'],
            ['label' => 'Create Opportunity', 'route' => 'pipeline.create', 'permission' => 'opportunities.create', 'priority' => 20, 'group' => 'primary'],
            ['label' => 'Create Customer', 'route' => 'customers.create', 'permission' => 'customers.create', 'priority' => 30, 'group' => 'primary'],
            ['label' => 'Create Contact', 'route' => 'contacts.index', 'permission' => 'customers.update', 'priority' => 35, 'group' => 'primary'],
            ['label' => 'New Quotation', 'route' => 'quotations.create', 'permission' => 'quotations.create', 'priority' => 40, 'group' => 'primary'],
            ['label' => 'New Sales Order', 'route' => 'sales-orders.create', 'permission' => 'sales_orders.create', 'priority' => 45, 'group' => 'primary'],
            ['label' => 'New Invoice', 'route' => 'invoices.create', 'permission' => 'invoices.create', 'priority' => 50, 'group' => 'secondary'],
            ['label' => 'Record Payment', 'route' => 'payments.create', 'permission' => 'payments.create', 'priority' => 60, 'group' => 'secondary'],
            ['label' => 'New Credit Note', 'route' => 'credit-notes.create', 'permission' => 'adjustment_notes.create', 'priority' => 65, 'group' => 'secondary'],
            ['label' => 'Import Leads', 'route' => 'leads.import.create', 'permission' => 'imports.create', 'priority' => 70, 'group' => 'secondary'],
        ],
        'hr' => [
            ['label' => 'Mark Attendance', 'route' => 'ess.attendance.index', 'permission' => 'ess.access', 'variant' => 'primary', 'priority' => 10, 'group' => 'primary'],
            ['label' => 'Apply Leave', 'route' => 'ess.leave.index', 'permission' => 'ess.access', 'priority' => 20, 'group' => 'primary'],
            ['label' => 'Employees', 'route' => 'hrms.employees.index', 'any_permissions' => ['hrms.view', 'employee.directory'], 'priority' => 30, 'group' => 'primary'],
            ['label' => 'Attendance', 'route' => 'hrms.attendance.index', 'permission' => 'attendance.view', 'priority' => 40, 'group' => 'primary'],
            ['label' => 'Add Employee', 'route' => 'hrms.employees.create', 'permission' => 'hrms.view', 'priority' => 50, 'group' => 'secondary'],
            ['label' => 'Leave Dashboard', 'route' => 'hrms.leave.dashboard', 'permission' => 'leave.view', 'priority' => 60, 'group' => 'secondary'],
            ['label' => 'View Payslip', 'route' => 'ess.payroll.payslips', 'permission' => 'ess.access', 'priority' => 70, 'group' => 'secondary'],
        ],
        'recruitment' => [
            ['label' => 'Recruitment Home', 'route' => 'hrms.recruitment.dashboard', 'permission' => 'recruitment.view', 'variant' => 'primary', 'priority' => 10, 'group' => 'primary'],
            ['label' => 'Candidates', 'route' => 'hrms.recruitment.candidates.index', 'permission' => 'recruitment.view', 'priority' => 20, 'group' => 'primary'],
            ['label' => 'Job Openings', 'route' => 'hrms.recruitment.openings.index', 'permission' => 'recruitment.view', 'priority' => 30, 'group' => 'primary'],
            ['label' => 'Post Opening', 'route' => 'hrms.recruitment.openings.create', 'permission' => 'recruitment.view', 'priority' => 40, 'group' => 'secondary'],
        ],
        'projects' => [
            ['label' => 'Create Project', 'route' => 'projects.create', 'permission' => 'projects.create', 'variant' => 'primary', 'priority' => 10, 'group' => 'primary'],
            ['label' => 'Create Task', 'route' => 'tasks.create', 'permission' => 'tasks.create', 'priority' => 20, 'group' => 'primary'],
            ['label' => 'Project Calendar', 'route' => 'projects.calendar', 'permission' => 'projects.view', 'priority' => 30, 'group' => 'primary'],
            ['label' => 'Task Board', 'route' => 'tasks.board', 'permission' => 'tasks.view', 'priority' => 40, 'group' => 'secondary'],
            ['label' => 'Resource Planner', 'route' => 'resources.planner', 'permission' => 'resources.view', 'priority' => 50, 'group' => 'secondary'],
            ['label' => 'Portfolios', 'route' => 'portfolios.index', 'permission' => 'projects.portfolios.view', 'priority' => 60, 'group' => 'secondary'],
            ['label' => 'Programs', 'route' => 'programs.index', 'permission' => 'projects.programs.view', 'priority' => 70, 'group' => 'secondary'],
        ],
        'operations' => [
            ['label' => 'Create Task', 'route' => 'tasks.create', 'permission' => 'tasks.create', 'variant' => 'primary', 'priority' => 10, 'group' => 'primary'],
            ['label' => 'Task Board', 'route' => 'tasks.board', 'permission' => 'tasks.view', 'priority' => 20, 'group' => 'primary'],
            ['label' => 'Task List', 'route' => 'tasks.list', 'permission' => 'tasks.view', 'priority' => 30, 'group' => 'primary'],
        ],
        'marketing' => [
            ['label' => 'Marketing Home', 'route' => 'marketing.home', 'any_permissions' => ['marketing.view', 'marketing.manage'], 'variant' => 'primary', 'priority' => 10, 'group' => 'primary'],
            ['label' => 'Campaigns', 'route' => 'marketing.campaigns.index', 'any_permissions' => ['marketing.view', 'marketing.manage'], 'priority' => 20, 'group' => 'primary'],
        ],
        'analytics' => [
            ['label' => 'Generate Report', 'route' => 'analytics.reports.index', 'permission' => 'reports.view', 'variant' => 'primary', 'priority' => 10, 'group' => 'primary'],
            ['label' => 'Analytics', 'route' => 'analytics.home', 'any_permissions' => ['reports.view', 'finance.view'], 'priority' => 20, 'group' => 'primary'],
            ['label' => 'Finance Report', 'route' => 'reports.finance', 'permission' => 'reports.view', 'priority' => 30, 'group' => 'secondary'],
            ['label' => 'CRM Reports', 'route' => 'crm.reports', 'permission' => 'reports.view', 'priority' => 40, 'group' => 'secondary'],
        ],
        'administration' => [
            ['label' => 'Invite User', 'route' => 'team.index', 'permission' => 'users.create', 'variant' => 'primary', 'priority' => 10, 'group' => 'primary'],
            ['label' => 'Manage Roles', 'route' => 'rbac.roles.index', 'any_permissions' => ['rbac.manage', 'rbac.view'], 'priority' => 20, 'group' => 'primary'],
            ['label' => 'Configuration Hub', 'route' => 'organization.settings.hub', 'permission' => 'settings.manage', 'priority' => 30, 'group' => 'primary'],
        ],
    ],

    'favorites' => [
        'max_display' => 5,
    ],
];
