<?php

/**
 * Workspace navigation configuration (Phase 13.1 / 14.1).
 *
 * Items are filtered at runtime by MenuBuilder using permissions.
 * Routes must exist; missing routes are skipped safely.
 */
return [
    'workspaces' => [
        'home' => [
            'id' => 'home',
            'label' => 'Home',
            'icon' => 'home',
            'order' => 10,
            'route' => 'dashboard',
            'match' => ['dashboard', 'dashboard.*'],
        ],
        'crm' => [
            'id' => 'crm',
            'label' => 'CRM',
            'icon' => 'users',
            'order' => 20,
            'route' => 'crm.home',
            'match' => ['crm.*', 'leads.*', 'customers.*', 'pipeline.*', 'products.*', 'quotations.*', 'invoices.*', 'payments.*'],
            'any_permissions' => [
                'leads.view', 'customers.view', 'opportunities.view', 'products.view',
                'quotations.view', 'invoices.view', 'payments.view',
            ],
        ],
        'projects' => [
            'id' => 'projects',
            'label' => 'Projects',
            'icon' => 'task',
            'order' => 30,
            'route' => 'projects.home',
            'match' => [
                'projects.*', 'project-*', 'portfolios.*', 'programs.*', 'resources.*',
                'risks.*', 'issues.*', 'portfolio-reports.*', 'tasks.*',
            ],
            'any_permissions' => ['projects.view', 'resources.view', 'projects.portfolios.view', 'projects.programs.view', 'tasks.view'],
        ],
        'hr' => [
            'id' => 'hr',
            'label' => 'HR',
            'icon' => 'hr',
            'order' => 40,
            'route' => 'hrms.home',
            'match' => ['hrms.*', 'ess.*'],
            'any_permissions' => [
                'hrms.view', 'ess.access', 'hr.dashboard', 'manager.dashboard',
                'employee.directory', 'attendance.view', 'leave.view',
                'recruitment.view', 'payroll.view', 'performance.view',
            ],
        ],
        'marketing' => [
            'id' => 'marketing',
            'label' => 'Marketing',
            'icon' => 'chart',
            'order' => 50,
            'route' => 'marketing.home',
            'any_permissions' => ['marketing.view', 'marketing.manage', 'integrations.view', 'integrations.manage'],
            'hide_when_empty' => true,
            'match' => ['marketing.*'],
        ],
        'operations' => [
            'id' => 'operations',
            'label' => 'Operations',
            'icon' => 'task',
            'order' => 60,
            'any_permissions' => ['tasks.view'],
        ],
        'analytics' => [
            'id' => 'analytics',
            'label' => 'Analytics',
            'icon' => 'chart',
            'order' => 70,
            'route' => 'analytics.home',
            'any_permissions' => ['reports.view', 'finance.view', 'audit.view', 'projects.reports.view', 'recruitment.reports.view'],
            'match' => ['analytics.*', 'reports.*'],
        ],
        'administration' => [
            'id' => 'administration',
            'label' => 'Administration',
            'icon' => 'cog',
            'order' => 80,
            'route' => 'administration.home',
            'match' => [
                'administration.*',
                'organization.settings.*',
                'organization.edit',
                'team.*',
                'rbac.*',
                'workflows.*',
                'metadata-fields.*',
                'integrations.*',
                'api-tokens.*',
                'audit-logs.*',
            ],
            'any_permissions' => [
                'settings.manage', 'users.view', 'rbac.view', 'workflows.view',
                'metadata.view', 'metadata.manage', 'integrations.view', 'integrations.manage',
                'api.tokens', 'audit.view',
            ],
            'footer' => true,
        ],
    ],

    'menus' => [
        'home' => [
            [
                'label' => 'Dashboard',
                'route' => 'dashboard',
                'match' => ['dashboard'],
                'icon' => 'home',
                'permission' => null,
            ],
        ],
        'crm' => [
            [
                'label' => 'CRM Home',
                'route' => 'crm.home',
                'match' => ['crm.home'],
                'icon' => 'home',
                'any_permissions' => [
                    'leads.view', 'customers.view', 'opportunities.view', 'products.view',
                    'quotations.view', 'invoices.view', 'payments.view',
                ],
            ],
            [
                'label' => 'Leads',
                'route' => 'leads.index',
                'match' => ['leads.*'],
                'icon' => 'users',
                'permission' => 'leads.view',
                'term' => 'leads',
            ],
            [
                'label' => 'Customers',
                'route' => 'customers.index',
                'match' => ['customers.*'],
                'icon' => 'building',
                'permission' => 'customers.view',
                'term' => 'customers',
            ],
            [
                'label' => 'Opportunities',
                'route' => 'pipeline.index',
                'match' => ['pipeline.*'],
                'icon' => 'chart',
                'permission' => 'opportunities.view',
                'term' => 'pipeline',
            ],
            [
                'label' => 'Revenue',
                'icon' => 'receipt',
                'children' => [
                    [
                        'label' => 'Revenue Dashboard',
                        'route' => 'crm.revenue',
                        'match' => ['crm.revenue'],
                        'any_permissions' => ['quotations.view', 'invoices.view', 'payments.view'],
                    ],
                    [
                        'label' => 'Quotations',
                        'route' => 'quotations.index',
                        'match' => ['quotations.*'],
                        'permission' => 'quotations.view',
                        'term' => 'quotations',
                    ],
                    [
                        'label' => 'Invoices',
                        'route' => 'invoices.index',
                        'match' => ['invoices.*'],
                        'permission' => 'invoices.view',
                        'term' => 'invoices',
                    ],
                    [
                        'label' => 'Payments',
                        'route' => 'payments.index',
                        'match' => ['payments.*'],
                        'permission' => 'payments.view',
                        'term' => 'payments',
                    ],
                ],
            ],
            [
                'label' => 'Activities',
                'route' => 'crm.activities',
                'match' => ['crm.activities'],
                'icon' => 'task',
                'permission' => 'leads.view',
            ],
            [
                'label' => 'Reports',
                'route' => 'crm.reports',
                'match' => ['crm.reports', 'reports.index', 'reports.finance', 'reports.export.*'],
                'icon' => 'chart',
                'permission' => 'reports.view',
                'tier' => 'extended',
            ],
            [
                'label' => 'Imports',
                'route' => 'leads.import.create',
                'match' => ['leads.import.*', 'customers.import.*'],
                'icon' => 'box',
                'permission' => 'imports.create',
                'tier' => 'extended',
            ],
            [
                'label' => 'Exports',
                'route' => 'crm.exports',
                'match' => ['crm.exports'],
                'icon' => 'box',
                'any_permissions' => ['reports.view', 'invoices.view', 'customers.view'],
                'tier' => 'extended',
            ],
            [
                'label' => 'Saved Views',
                'route' => 'crm.saved-views',
                'match' => ['crm.saved-views'],
                'icon' => 'fields',
                'any_permissions' => ['leads.view', 'customers.view', 'opportunities.view'],
                'tier' => 'extended',
            ],
            [
                'label' => 'Products',
                'route' => 'products.index',
                'match' => ['products.*'],
                'icon' => 'box',
                'permission' => 'products.view',
                'term' => 'products',
                'tier' => 'extended',
            ],
        ],
        'projects' => [
            [
                'label' => 'Projects Home',
                'route' => 'projects.home',
                'match' => ['projects.home'],
                'icon' => 'home',
                'any_permissions' => [
                    'projects.view', 'resources.view', 'projects.portfolios.view', 'projects.programs.view', 'tasks.view',
                ],
            ],
            [
                'label' => 'Projects',
                'route' => 'projects.index',
                'match' => ['projects.index', 'projects.create', 'projects.store', 'projects.show', 'projects.edit', 'projects.update', 'projects.destroy', 'projects.archive', 'projects.restore', 'projects.dashboard', 'projects.executive', 'projects.watching', 'projects.automation', 'project-*'],
                'icon' => 'task',
                'permission' => 'projects.view',
            ],
            [
                'label' => 'Tasks',
                'route' => 'tasks.index',
                'match' => ['tasks.*'],
                'icon' => 'task',
                'permission' => 'tasks.view',
            ],
            [
                'label' => 'Milestones',
                'route' => 'projects.milestones.hub',
                'match' => ['projects.milestones.hub', 'projects.milestones.*'],
                'icon' => 'chart',
                'permission' => 'projects.view',
            ],
            [
                'label' => 'Resources',
                'icon' => 'chart',
                'permission' => 'resources.view',
                'children' => [
                    [
                        'label' => 'Planner',
                        'route' => 'resources.planner',
                        'match' => ['resources.planner'],
                        'permission' => 'resources.view',
                    ],
                    [
                        'label' => 'Capacity',
                        'route' => 'resources.capacity',
                        'match' => ['resources.capacity'],
                        'permission' => 'resources.view',
                    ],
                    [
                        'label' => 'Workload',
                        'route' => 'resources.timeline',
                        'match' => ['resources.timeline', 'resources.employees.workload'],
                        'permission' => 'resources.view',
                    ],
                    [
                        'label' => 'Allocations',
                        'route' => 'resources.allocations.index',
                        'match' => ['resources.allocations.*'],
                        'permission' => 'resources.view',
                    ],
                    [
                        'label' => 'Calendars',
                        'route' => 'resources.calendars.index',
                        'match' => ['resources.calendars.*', 'projects.calendar', 'projects.calendar.*'],
                        'permission' => 'resources.view',
                    ],
                ],
            ],
            [
                'label' => 'Portfolios',
                'route' => 'portfolios.index',
                'match' => ['portfolios.*'],
                'icon' => 'chart',
                'permission' => 'projects.portfolios.view',
            ],
            [
                'label' => 'Programs',
                'route' => 'programs.index',
                'match' => ['programs.*'],
                'icon' => 'chart',
                'permission' => 'projects.programs.view',
            ],
            [
                'label' => 'Risks',
                'route' => 'risks.index',
                'match' => ['risks.*', 'projects.risks.*'],
                'icon' => 'shield',
                'permission' => 'projects.view',
                'tier' => 'extended',
            ],
            [
                'label' => 'Issues',
                'route' => 'issues.index',
                'match' => ['issues.*', 'projects.issues.*'],
                'icon' => 'shield',
                'permission' => 'projects.view',
                'tier' => 'extended',
            ],
            [
                'label' => 'Budgets',
                'route' => 'projects.budgets.hub',
                'match' => ['projects.budgets.hub', 'projects.budgets.*'],
                'icon' => 'receipt',
                'permission' => 'projects.view',
                'tier' => 'extended',
            ],
            [
                'label' => 'Forecasts',
                'route' => 'portfolios.forecasts.index',
                'match' => ['portfolios.forecasts.*', 'resources.forecast'],
                'icon' => 'chart',
                'any_permissions' => ['projects.portfolios.view', 'resources.view'],
                'tier' => 'extended',
            ],
            [
                'label' => 'Reports',
                'route' => 'projects.reports.hub',
                'match' => ['projects.reports.hub', 'portfolio-reports.*', 'projects.reports.*'],
                'icon' => 'chart',
                'any_permissions' => ['projects.view', 'reports.view', 'projects.portfolios.view'],
                'tier' => 'extended',
            ],
        ],
        'hr' => [
            [
                'label' => 'HR Home',
                'route' => 'hrms.home',
                'match' => ['hrms.home', 'hrms.dashboard'],
                'icon' => 'home',
                'any_permissions' => [
                    'hrms.view', 'ess.access', 'hr.dashboard', 'manager.dashboard',
                    'employee.directory', 'attendance.view', 'leave.view',
                    'recruitment.view', 'payroll.view', 'performance.view',
                ],
            ],
            [
                'label' => 'Employees',
                'route' => 'hrms.employees.index',
                'match' => ['hrms.employees.*', 'hrms.directory.*'],
                'icon' => 'users',
                'any_permissions' => ['hrms.view', 'employee.directory'],
                'children' => [
                    [
                        'label' => 'Directory',
                        'route' => 'hrms.directory.index',
                        'match' => ['hrms.directory.*'],
                        'permission' => 'employee.directory',
                    ],
                    [
                        'label' => 'Employees',
                        'route' => 'hrms.employees.index',
                        'match' => ['hrms.employees.*'],
                        'permission' => 'hrms.view',
                    ],
                    [
                        'label' => 'Teams',
                        'route' => 'hrms.teams.index',
                        'match' => ['hrms.teams.*'],
                        'permission' => 'hrms.view',
                    ],
                    [
                        'label' => 'Departments',
                        'route' => 'hrms.departments.index',
                        'match' => ['hrms.departments.*'],
                        'permission' => 'hrms.view',
                    ],
                    [
                        'label' => 'Branches',
                        'route' => 'hrms.branches.index',
                        'match' => ['hrms.branches.*'],
                        'permission' => 'hrms.view',
                    ],
                    [
                        'label' => 'Designations',
                        'route' => 'hrms.designations.index',
                        'match' => ['hrms.designations.*'],
                        'permission' => 'hrms.view',
                    ],
                ],
            ],
            [
                'label' => 'Attendance',
                'route' => 'hrms.attendance.index',
                'match' => ['hrms.attendance.*'],
                'icon' => 'hr',
                'permission' => 'attendance.view',
            ],
            [
                'label' => 'Leave',
                'route' => 'hrms.leave.dashboard',
                'match' => ['hrms.leave.*', 'hrms.leave-applications.*', 'hrms.leave-balances.*', 'hrms.leave-types.*', 'hrms.holidays.*'],
                'icon' => 'hr',
                'permission' => 'leave.view',
                'children' => [
                    [
                        'label' => 'Leave Dashboard',
                        'route' => 'hrms.leave.dashboard',
                        'match' => ['hrms.leave.dashboard'],
                        'permission' => 'leave.view',
                    ],
                    [
                        'label' => 'Leave Requests',
                        'route' => 'hrms.leave-applications.index',
                        'match' => ['hrms.leave-applications.*'],
                        'permission' => 'leave.view',
                    ],
                    [
                        'label' => 'Approval Queue',
                        'route' => 'hrms.leave-applications.approval-queue',
                        'match' => ['hrms.leave-applications.approval-queue'],
                        'permission' => 'leave.approve',
                    ],
                    [
                        'label' => 'Leave Balances',
                        'route' => 'hrms.leave-balances.index',
                        'match' => ['hrms.leave-balances.*'],
                        'permission' => 'leave.view',
                    ],
                    [
                        'label' => 'Leave Types',
                        'route' => 'hrms.leave-types.index',
                        'match' => ['hrms.leave-types.*'],
                        'permission' => 'leave.view',
                    ],
                    [
                        'label' => 'Holidays',
                        'route' => 'hrms.holidays.index',
                        'match' => ['hrms.holidays.*'],
                        'permission' => 'leave.view',
                    ],
                ],
            ],
            [
                'label' => 'Shifts',
                'route' => 'hrms.shifts.index',
                'match' => ['hrms.shifts.*', 'hrms.shift-assignments.*'],
                'icon' => 'hr',
                'permission' => 'attendance.view',
                'children' => [
                    [
                        'label' => 'Shifts',
                        'route' => 'hrms.shifts.index',
                        'match' => ['hrms.shifts.*'],
                        'permission' => 'attendance.view',
                    ],
                    [
                        'label' => 'Shift Assignments',
                        'route' => 'hrms.shift-assignments.index',
                        'match' => ['hrms.shift-assignments.*'],
                        'permission' => 'attendance.view',
                    ],
                ],
            ],
            [
                'label' => 'Payroll',
                'route' => 'hrms.payroll.index',
                'match' => ['hrms.payroll.*'],
                'icon' => 'payment',
                'permission' => 'payroll.view',
            ],
            [
                'label' => 'Performance',
                'route' => 'hrms.performance.index',
                'match' => ['hrms.performance.*'],
                'icon' => 'hr',
                'any_permissions' => ['performance.view', 'performance.goal.view', 'performance.review.view'],
            ],
            [
                'label' => 'Recruitment',
                'route' => 'hrms.recruitment.dashboard',
                'match' => ['hrms.recruitment.*'],
                'icon' => 'hr',
                'permission' => 'recruitment.view',
                'children' => [
                    [
                        'label' => 'Recruitment Dashboard',
                        'route' => 'hrms.recruitment.dashboard',
                        'match' => ['hrms.recruitment.dashboard', 'hrms.recruitment.executive', 'hrms.recruitment.analytics'],
                        'permission' => 'recruitment.view',
                    ],
                    [
                        'label' => 'Job Openings',
                        'route' => 'hrms.recruitment.openings.index',
                        'match' => ['hrms.recruitment.openings.*'],
                        'permission' => 'recruitment.view',
                    ],
                    [
                        'label' => 'Candidates',
                        'route' => 'hrms.recruitment.candidates.index',
                        'match' => ['hrms.recruitment.candidates.*'],
                        'permission' => 'recruitment.view',
                    ],
                    [
                        'label' => 'Applications',
                        'route' => 'hrms.recruitment.applications.index',
                        'match' => ['hrms.recruitment.applications.*'],
                        'permission' => 'recruitment.view',
                    ],
                    [
                        'label' => 'Interviews',
                        'route' => 'hrms.recruitment.interview-rounds.index',
                        'match' => ['hrms.recruitment.interview-rounds.*'],
                        'permission' => 'recruitment.view',
                    ],
                    [
                        'label' => 'Reports',
                        'route' => 'hrms.recruitment.reports.index',
                        'match' => ['hrms.recruitment.reports.*', 'hrms.recruitment.exports.*'],
                        'permission' => 'recruitment.view',
                        'tier' => 'extended',
                    ],
                ],
            ],
            [
                'label' => 'Assets',
                'route' => 'hrms.assets.index',
                'match' => ['hrms.assets.*'],
                'icon' => 'box',
                'permission' => 'assets.view',
            ],
            [
                'label' => 'Documents',
                'route' => 'hrms.employees.index',
                'match' => ['hrms.employees.documents.*'],
                'icon' => 'fields',
                'permission' => 'hrms.view',
                'tier' => 'extended',
            ],
            [
                'label' => 'Reports',
                'route' => 'hrms.recruitment.reports.index',
                'match' => ['hrms.recruitment.reports.*', 'hrms.payroll.reports.*'],
                'icon' => 'chart',
                'any_permissions' => ['recruitment.view', 'payroll.view', 'reports.view'],
                'tier' => 'extended',
            ],
            [
                'label' => 'Configuration',
                'icon' => 'settings',
                'tier' => 'extended',
                'any_permissions' => ['hrms.view', 'leave.view', 'attendance.view'],
                'children' => [
                    [
                        'label' => 'Departments',
                        'route' => 'hrms.departments.index',
                        'match' => ['hrms.departments.*'],
                        'permission' => 'hrms.view',
                    ],
                    [
                        'label' => 'Branches',
                        'route' => 'hrms.branches.index',
                        'match' => ['hrms.branches.*'],
                        'permission' => 'hrms.view',
                    ],
                    [
                        'label' => 'Designations',
                        'route' => 'hrms.designations.index',
                        'match' => ['hrms.designations.*'],
                        'permission' => 'hrms.view',
                    ],
                    [
                        'label' => 'Holiday Calendar',
                        'route' => 'hrms.holidays.index',
                        'match' => ['hrms.holidays.*'],
                        'permission' => 'leave.view',
                    ],
                    [
                        'label' => 'Leave Types',
                        'route' => 'hrms.leave-types.index',
                        'match' => ['hrms.leave-types.*'],
                        'permission' => 'leave.view',
                    ],
                    [
                        'label' => 'Shift Management',
                        'route' => 'hrms.shifts.index',
                        'match' => ['hrms.shifts.*'],
                        'permission' => 'attendance.view',
                    ],
                ],
            ],
            [
                'label' => 'My HR',
                'icon' => 'user',
                'any_permissions' => ['ess.access'],
                'children' => [
                    [
                        'label' => 'My Dashboard',
                        'route' => 'ess.dashboard',
                        'match' => ['ess.dashboard'],
                        'permission' => 'ess.access',
                    ],
                    [
                        'label' => 'My Profile',
                        'route' => 'ess.profile',
                        'match' => ['ess.profile*'],
                        'permission' => 'ess.access',
                    ],
                    [
                        'label' => 'My Documents',
                        'route' => 'ess.documents.index',
                        'match' => ['ess.documents.*'],
                        'permission' => 'ess.access',
                    ],
                    [
                        'label' => 'My Attendance',
                        'route' => 'ess.attendance.index',
                        'match' => ['ess.attendance.*'],
                        'permission' => 'ess.access',
                    ],
                    [
                        'label' => 'My Leave',
                        'route' => 'ess.leave.index',
                        'match' => ['ess.leave.*'],
                        'permission' => 'ess.access',
                    ],
                    [
                        'label' => 'My Payroll',
                        'route' => 'ess.payroll.index',
                        'match' => ['ess.payroll.*'],
                        'permission' => 'ess.access',
                    ],
                ],
            ],
            [
                'label' => 'More',
                'icon' => 'hr',
                'tier' => 'extended',
                'children' => [
                    [
                        'label' => 'Announcements',
                        'route' => 'hrms.announcements.index',
                        'match' => ['hrms.announcements.*'],
                        'permission' => 'announcements.manage',
                    ],
                    [
                        'label' => 'Exit Processes',
                        'route' => 'hrms.exit-processes.index',
                        'match' => ['hrms.exit-processes.*'],
                        'permission' => 'employee.exit.manage',
                    ],
                    [
                        'label' => 'Calendar',
                        'route' => 'hrms.calendar',
                        'match' => ['hrms.calendar'],
                        'permission' => 'organization.calendar',
                    ],
                    [
                        'label' => 'Manager Dashboard',
                        'route' => 'hrms.manager.dashboard',
                        'match' => ['hrms.manager.dashboard'],
                        'permission' => 'manager.dashboard',
                    ],
                    [
                        'label' => 'Legacy HR Dashboard',
                        'route' => 'hrms.dashboard',
                        'match' => ['hrms.dashboard'],
                        'permission' => 'hr.dashboard',
                    ],
                ],
            ],
        ],
        'marketing' => [
            [
                'label' => 'Overview',
                'route' => 'marketing.home',
                'match' => ['marketing.home'],
                'icon' => 'home',
                'any_permissions' => ['marketing.view', 'marketing.manage', 'integrations.view', 'integrations.manage'],
            ],
            [
                'label' => 'Campaigns',
                'route' => 'marketing.campaigns.index',
                'match' => ['marketing.campaigns.*'],
                'icon' => 'chart',
                'any_permissions' => ['marketing.view', 'marketing.manage', 'integrations.view', 'integrations.manage'],
            ],
            [
                'label' => 'Attribution',
                'route' => 'marketing.attribution.index',
                'match' => ['marketing.attribution.*'],
                'icon' => 'chart',
                'any_permissions' => ['marketing.view', 'marketing.manage', 'integrations.view', 'integrations.manage'],
            ],
            [
                'label' => 'Providers',
                'route' => 'marketing.providers.index',
                'match' => ['marketing.providers.*'],
                'icon' => 'shield',
                'any_permissions' => ['marketing.view', 'marketing.manage', 'integrations.view', 'integrations.manage'],
            ],
            [
                'label' => 'Integrations',
                'route' => 'integrations.index',
                'match' => ['integrations.*'],
                'icon' => 'shield',
                'any_permissions' => ['integrations.view', 'integrations.manage', 'marketing.view'],
            ],
        ],
        'operations' => [
            [
                'label' => 'Tasks',
                'route' => 'tasks.index',
                'match' => ['tasks.*'],
                'icon' => 'task',
                'permission' => 'tasks.view',
            ],
        ],
        'analytics' => [
            [
                'label' => 'Overview',
                'route' => 'analytics.home',
                'match' => ['analytics.home'],
                'icon' => 'home',
                'any_permissions' => ['reports.view', 'finance.view', 'audit.view', 'projects.reports.view', 'recruitment.reports.view'],
            ],
            [
                'label' => 'Executive',
                'route' => 'analytics.executive',
                'match' => ['analytics.executive'],
                'icon' => 'chart',
                'any_permissions' => ['reports.view', 'projects.executive.view', 'finance.view'],
            ],
            [
                'label' => 'CRM Analytics',
                'route' => 'analytics.crm',
                'match' => ['analytics.crm'],
                'icon' => 'chart',
                'permission' => 'reports.view',
            ],
            [
                'label' => 'Project Analytics',
                'route' => 'analytics.projects',
                'match' => ['analytics.projects'],
                'icon' => 'chart',
                'any_permissions' => ['reports.view', 'projects.reports.view'],
            ],
            [
                'label' => 'HR Analytics',
                'route' => 'analytics.hr',
                'match' => ['analytics.hr'],
                'icon' => 'chart',
                'any_permissions' => ['reports.view', 'recruitment.reports.view', 'hrms.view'],
            ],
            [
                'label' => 'AI Insights',
                'route' => 'analytics.ai-insights',
                'match' => ['analytics.ai-insights'],
                'icon' => 'chart',
                'any_permissions' => ['reports.view', 'finance.view'],
            ],
            [
                'label' => 'Dashboards',
                'route' => 'analytics.dashboards.index',
                'match' => ['analytics.dashboards.*'],
                'icon' => 'chart',
                'permission' => 'reports.view',
            ],
            [
                'label' => 'KPI Library',
                'route' => 'analytics.kpis.index',
                'match' => ['analytics.kpis.*'],
                'icon' => 'chart',
                'permission' => 'reports.view',
            ],
            [
                'label' => 'Reports Center',
                'route' => 'analytics.reports.index',
                'match' => ['analytics.reports.*'],
                'icon' => 'chart',
                'permission' => 'reports.view',
            ],
            [
                'label' => 'Sales Reports',
                'route' => 'reports.index',
                'match' => ['reports.index'],
                'icon' => 'chart',
                'permission' => 'reports.view',
            ],
            [
                'label' => 'Finance',
                'route' => 'reports.finance',
                'match' => ['reports.finance'],
                'icon' => 'chart',
                'any_permissions' => ['reports.view', 'finance.view'],
            ],
            [
                'label' => 'Audit Log',
                'route' => 'audit-logs.index',
                'match' => ['audit-logs.*'],
                'icon' => 'shield',
                'permission' => 'audit.view',
            ],
        ],
        'administration' => [
            [
                'label' => 'Overview',
                'route' => 'administration.home',
                'match' => ['administration.home'],
                'icon' => 'home',
                'any_permissions' => [
                    'settings.manage', 'users.view', 'rbac.view', 'workflows.view',
                    'metadata.view', 'metadata.manage', 'integrations.view', 'integrations.manage',
                    'api.tokens', 'audit.view',
                ],
            ],
            [
                'label' => 'Users',
                'route' => 'team.index',
                'match' => ['team.*'],
                'icon' => 'users',
                'permission' => 'users.view',
            ],
            [
                'label' => 'Roles',
                'route' => 'rbac.roles.index',
                'match' => ['rbac.*'],
                'icon' => 'shield',
                'permission' => 'rbac.view',
            ],
            [
                'label' => 'Configuration Hub',
                'route' => 'organization.settings.hub',
                'match' => ['organization.settings.*', 'organization.edit'],
                'icon' => 'cog',
                'permission' => 'settings.manage',
            ],
            [
                'label' => 'Modules',
                'route' => 'administration.modules.index',
                'match' => ['administration.modules.*'],
                'icon' => 'fields',
                'permission' => 'settings.manage',
            ],
            [
                'label' => 'Branding',
                'route' => 'administration.branding.edit',
                'match' => ['administration.branding.*'],
                'icon' => 'cog',
                'permission' => 'settings.manage',
            ],
            [
                'label' => 'Notifications',
                'route' => 'organization.settings.notifications.edit',
                'match' => ['organization.settings.notifications.*'],
                'icon' => 'cog',
                'permission' => 'settings.manage',
            ],
            [
                'label' => 'Integrations',
                'route' => 'integrations.index',
                'match' => ['integrations.*'],
                'icon' => 'shield',
                'any_permissions' => ['integrations.view', 'integrations.manage'],
            ],
            [
                'label' => 'Developer',
                'route' => 'administration.developer.index',
                'match' => ['administration.developer.*', 'api-tokens.*'],
                'icon' => 'shield',
                'any_permissions' => ['settings.manage', 'api.tokens'],
            ],
            [
                'label' => 'Security',
                'route' => 'administration.security.index',
                'match' => ['administration.security.*'],
                'icon' => 'shield',
                'permission' => 'settings.manage',
            ],
            [
                'label' => 'Audit Logs',
                'route' => 'audit-logs.index',
                'match' => ['audit-logs.*'],
                'icon' => 'shield',
                'permission' => 'audit.view',
            ],
            [
                'label' => 'Workflows',
                'route' => 'workflows.index',
                'match' => ['workflows.*'],
                'icon' => 'workflow',
                'permission' => 'workflows.view',
            ],
            [
                'label' => 'Metadata Fields',
                'route' => 'metadata-fields.index',
                'match' => ['metadata-fields.*'],
                'icon' => 'fields',
                'any_permissions' => ['metadata.view', 'metadata.manage'],
            ],
        ],
    ],

    'route_workspace_map' => [
        'dashboard' => 'home',
        'dashboard.*' => 'home',
        'crm.*' => 'crm',
        'leads.*' => 'crm',
        'customers.*' => 'crm',
        'pipeline.*' => 'crm',
        'products.*' => 'crm',
        'quotations.*' => 'crm',
        'invoices.*' => 'crm',
        'payments.*' => 'crm',
        'projects.*' => 'projects',
        'project-*' => 'projects',
        'portfolios.*' => 'projects',
        'programs.*' => 'projects',
        'resources.*' => 'projects',
        'project-risks.*' => 'projects',
        'project-issues.*' => 'projects',
        'risks.*' => 'projects',
        'issues.*' => 'projects',
        'portfolio-reports.*' => 'projects',
        'hrms.*' => 'hr',
        'ess.*' => 'hr',
        'tasks.*' => 'projects',
        'reports.*' => 'analytics',
        'analytics.*' => 'analytics',
        'marketing.*' => 'marketing',
        'audit-logs.*' => 'administration',
        'administration.*' => 'administration',
        'organization.settings.*' => 'administration',
        'organization.edit' => 'administration',
        'team.*' => 'administration',
        'rbac.*' => 'administration',
        'workflows.*' => 'administration',
        'metadata-fields.*' => 'administration',
        'integrations.*' => 'administration',
        'api-tokens.*' => 'administration',
        'knowledge.*' => 'home',
        'profile.*' => 'home',
        'notifications.*' => 'home',
        'search.*' => 'home',
    ],

    'recents' => [
        'max' => 10,
    ],

    'favorites' => [
        'max_display' => 5,
    ],
];
