<?php

return [

    'session_cookie' => env('PLATFORM_SESSION_COOKIE', 'nova_crm_platform_session'),

    'roles' => [
        'platform-owner' => [
            'name' => 'Platform Owner',
            'permissions' => '*',
        ],
        'platform-administrator' => [
            'name' => 'Platform Administrator',
            'permissions' => [
                'platform.dashboard',
                'platform.organizations.view',
                'platform.organizations.manage',
                'platform.users.manage',
                'platform.global_users.view',
                'platform.global_users.manage',
                'platform.subscriptions.view',
                'platform.subscriptions.manage',
                'platform.licensing.view',
                'platform.licensing.manage',
                'platform.providers.view',
                'platform.providers.manage',
                'platform.monitoring.view',
                'platform.security.view',
                'platform.security.manage',
                'platform.support.view',
                'platform.support.manage',
                'platform.configuration.view',
                'platform.configuration.manage',
                'platform.industry_templates.view',
                'platform.industry_templates.create',
                'platform.industry_templates.update',
                'platform.industry_templates.publish',
                'platform.industry_templates.archive',
                'platform.industry_templates.apply',
                'platform.reports.view',
                'platform.audit.view',
                'platform.impersonate',
            ],
        ],
        'platform-support' => [
            'name' => 'Platform Support',
            'permissions' => [
                'platform.dashboard',
                'platform.organizations.view',
                'platform.global_users.view',
                'platform.subscriptions.view',
                'platform.licensing.view',
                'platform.providers.view',
                'platform.monitoring.view',
                'platform.security.view',
                'platform.support.view',
                'platform.support.manage',
                'platform.industry_templates.view',
                'platform.reports.view',
                'platform.audit.view',
                'platform.impersonate',
            ],
        ],
        'platform-finance' => [
            'name' => 'Platform Finance',
            'permissions' => [
                'platform.dashboard',
                'platform.organizations.view',
                'platform.subscriptions.view',
                'platform.subscriptions.manage',
                'platform.licensing.view',
                'platform.reports.view',
                'platform.audit.view',
            ],
        ],
        'platform-read-only' => [
            'name' => 'Platform Read Only',
            'permissions' => [
                'platform.dashboard',
                'platform.organizations.view',
                'platform.global_users.view',
                'platform.subscriptions.view',
                'platform.licensing.view',
                'platform.providers.view',
                'platform.monitoring.view',
                'platform.security.view',
                'platform.support.view',
                'platform.configuration.view',
                'platform.industry_templates.view',
                'platform.reports.view',
                'platform.audit.view',
            ],
        ],
    ],

    'permissions' => [
        'platform.dashboard' => 'View platform dashboard',
        'platform.organizations.view' => 'View organizations',
        'platform.organizations.manage' => 'Manage organizations',
        'platform.users.manage' => 'Manage platform users',
        'platform.global_users.view' => 'View tenant users across organizations',
        'platform.global_users.manage' => 'Manage tenant users across organizations',
        'platform.subscriptions.view' => 'View subscriptions and billing',
        'platform.subscriptions.manage' => 'Manage subscriptions and billing',
        'platform.licensing.view' => 'View licensing and modules',
        'platform.licensing.manage' => 'Manage licensing and modules',
        'platform.providers.view' => 'View provider center',
        'platform.providers.manage' => 'Manage provider configuration',
        'platform.monitoring.view' => 'View platform monitoring',
        'platform.security.view' => 'View security center',
        'platform.security.manage' => 'Manage security policies',
        'platform.support.view' => 'View support center',
        'platform.support.manage' => 'Manage support tickets and notices',
        'platform.configuration.view' => 'View platform configuration',
        'platform.configuration.manage' => 'Manage platform configuration',
        'platform.industry_templates.view' => 'View industry templates',
        'platform.industry_templates.create' => 'Create industry templates',
        'platform.industry_templates.update' => 'Update industry template drafts',
        'platform.industry_templates.publish' => 'Publish industry templates',
        'platform.industry_templates.archive' => 'Archive industry templates',
        'platform.industry_templates.apply' => 'Apply industry templates during organization onboarding',
        'platform.reports.view' => 'View platform reports',
        'platform.audit.view' => 'View platform audit logs',
        'platform.impersonate' => 'Impersonate organization users',
    ],

    'navigation' => [
        [
            'label' => 'Dashboard',
            'route' => 'platform.dashboard',
            'permission' => 'platform.dashboard',
            'match' => ['platform.dashboard'],
        ],
        [
            'label' => 'Organizations',
            'route' => 'platform.organizations.index',
            'permission' => 'platform.organizations.view',
            'match' => ['platform.organizations.*'],
        ],
        [
            'label' => 'Subscriptions',
            'route' => 'platform.subscriptions.index',
            'permission' => 'platform.subscriptions.view',
            'match' => ['platform.subscriptions.*', 'platform.plans.*', 'platform.coupons.*', 'platform.invoices.*', 'platform.transactions.*'],
        ],
        [
            'label' => 'Licensing',
            'route' => 'platform.licensing.index',
            'permission' => 'platform.licensing.view',
            'match' => ['platform.licensing.*'],
        ],
        [
            'label' => 'Users',
            'route' => 'platform.global-users.index',
            'permission' => 'platform.global_users.view',
            'match' => ['platform.global-users.*', 'platform.users.*'],
        ],
        [
            'label' => 'Providers',
            'route' => 'platform.providers.index',
            'permission' => 'platform.providers.view',
            'match' => ['platform.providers.*'],
        ],
        [
            'label' => 'Monitoring',
            'route' => 'platform.monitoring.index',
            'permission' => 'platform.monitoring.view',
            'match' => ['platform.monitoring.*'],
        ],
        [
            'label' => 'Security',
            'route' => 'platform.security.index',
            'permission' => 'platform.security.view',
            'match' => ['platform.security.*'],
        ],
        [
            'label' => 'Audit',
            'route' => 'platform.audit.index',
            'permission' => 'platform.audit.view',
            'match' => ['platform.audit.*'],
        ],
        [
            'label' => 'Support',
            'route' => 'platform.support.index',
            'permission' => 'platform.support.view',
            'match' => ['platform.support.*'],
        ],
        [
            'label' => 'Configuration',
            'route' => 'platform.configuration.index',
            'permission' => 'platform.configuration.view',
            'match' => ['platform.configuration.*'],
        ],
        [
            'label' => 'Industry Templates',
            'route' => 'platform.industry-templates.index',
            'permission' => 'platform.industry_templates.view',
            'match' => ['platform.industry-templates.*', 'platform.industry-template-versions.*'],
        ],
        [
            'label' => 'Reports',
            'route' => 'platform.reports.index',
            'permission' => 'platform.reports.view',
            'match' => ['platform.reports.*'],
        ],
    ],

    'organization_statuses' => [
        'active' => 'Active',
        'suspended' => 'Suspended',
        'archived' => 'Archived',
    ],

    'plans' => [
        'starter' => 'Starter',
        'professional' => 'Professional',
        'enterprise' => 'Enterprise',
    ],

    'plan_definitions' => (static function () {
        $registry = require __DIR__.'/modules.php';
        $planModules = $registry['plan_modules'] ?? [];

        return [
            'starter' => [
                'name' => 'Starter',
                'description' => 'Core CRM for growing teams',
                'modules' => $planModules['starter'] ?? ['common', 'crm', 'tasks', 'notifications', 'calendar'],
                'limits' => [
                    'users' => 10,
                    'storage_mb' => 1024,
                    'api_requests_per_day' => 5000,
                ],
                'features' => [
                    'crm' => true,
                    'projects' => false,
                    'hrms' => false,
                    'recruitment' => false,
                    'marketing' => false,
                    'analytics' => false,
                    'advanced_reporting' => false,
                ],
            ],
            'professional' => [
                'name' => 'Professional',
                'description' => 'CRM, HR, Projects, Marketing, Analytics, and finance for mid-market',
                'modules' => $planModules['professional'] ?? [],
                'limits' => [
                    'users' => 100,
                    'storage_mb' => 10240,
                    'api_requests_per_day' => 50000,
                ],
                'features' => [
                    'crm' => true,
                    'projects' => true,
                    'hrms' => true,
                    'recruitment' => true,
                    'marketing' => true,
                    'analytics' => true,
                    'advanced_reporting' => true,
                ],
            ],
            'enterprise' => [
                'name' => 'Enterprise',
                'description' => 'Full platform with unlimited module access',
                'modules' => $planModules['enterprise'] ?? '*',
                'limits' => [
                    'users' => null,
                    'storage_mb' => null,
                    'api_requests_per_day' => null,
                ],
                'features' => [
                    'crm' => true,
                    'projects' => true,
                    'hrms' => true,
                    'recruitment' => true,
                    'marketing' => true,
                    'analytics' => true,
                    'advanced_reporting' => true,
                    'sso' => true,
                    'dedicated_support' => true,
                ],
            ],
        ];
    })(),

    'providers' => [
        'google' => [
            'label' => 'Google',
            'category' => 'identity',
            'env_keys' => ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
        ],
        'microsoft' => [
            'label' => 'Microsoft',
            'category' => 'identity',
            'env_keys' => ['MICROSOFT_CLIENT_ID', 'MICROSOFT_CLIENT_SECRET'],
        ],
        'meta' => [
            'label' => 'Meta',
            'category' => 'social',
            'env_keys' => ['META_APP_ID', 'META_APP_SECRET'],
        ],
        'smtp' => [
            'label' => 'SMTP',
            'category' => 'email',
            'env_keys' => ['MAIL_HOST', 'MAIL_USERNAME', 'MAIL_PASSWORD'],
        ],
        'whatsapp' => [
            'label' => 'WhatsApp',
            'category' => 'messaging',
            'env_keys' => ['WHATSAPP_TOKEN', 'WHATSAPP_PHONE_NUMBER_ID'],
        ],
        'sms' => [
            'label' => 'SMS',
            'category' => 'messaging',
            'env_keys' => ['SMS_API_KEY', 'SMS_FROM'],
        ],
        'payment' => [
            'label' => 'Payment Gateways',
            'category' => 'billing',
            'env_keys' => ['STRIPE_KEY', 'STRIPE_SECRET', 'RAZORPAY_KEY'],
        ],
        'ai' => [
            'label' => 'AI Providers',
            'category' => 'ai',
            'env_keys' => ['OPENAI_API_KEY', 'ANTHROPIC_API_KEY'],
        ],
    ],

    'security_defaults' => [
        'mfa_required_for_platform' => false,
        'mfa_required_for_tenants' => false,
        'password_min_length' => 8,
        'password_require_special' => true,
        'session_lifetime_minutes' => 120,
        'max_failed_logins' => 5,
        'ip_allowlist' => [],
        'trusted_devices_enabled' => true,
    ],

    'configuration_defaults' => [
        'branding' => [
            'product_name' => 'NovaCRM',
            'primary_color' => '#2563eb',
            'accent_color' => '#0ea5e9',
        ],
        'domains' => [
            'app_url' => null,
            'platform_url' => null,
        ],
        'regional' => [
            'default_timezone' => 'UTC',
            'default_currency' => 'USD',
            'default_locale' => 'en',
        ],
        'ai' => [
            'enabled' => false,
            'default_provider' => null,
        ],
        'organization_defaults' => [
            'plan' => 'starter',
            'status' => 'active',
        ],
    ],

    'dashboard_cache_ttl' => (int) env('PLATFORM_DASHBOARD_CACHE_TTL', 300),

    'dashboard_widgets' => [
        'org_totals',
        'org_active',
        'org_trial',
        'org_expired',
        'users_active',
        'users_mau',
        'revenue_summary',
        'subscription_overview',
        'storage_usage',
        'queue_health',
        'background_jobs',
        'api_requests',
        'email_delivery',
        'provider_health',
        'platform_alerts',
        'recent_activity',
        'quick_actions',
    ],

];
