<?php

return [
    'modules' => [
        'users',
        'leads',
        'customers',
        'opportunities',
        'quotations',
        'invoices',
        'payments',
        'products',
        'reports',
        'finance',
        'tasks',
        'projects',
        'resources',
        'audit',
        'attachments',
        'api',
        'metadata',
        'settings',
        'imports',
        'assignments',
        'workflows',
        'dashboard',
        'hrms',
        'attendance',
        'leave',
        'ess',
        'payroll',
        'recruitment',
    ],

    'actions' => [
        'view',
        'create',
        'update',
        'delete',
        'manage',
    ],

    'permissions' => [
        'users.view' => ['Users', 'View team members'],
        'users.create' => ['Users', 'Invite new users'],
        'users.update' => ['Users', 'Edit user profiles and roles'],
        'users.delete' => ['Users', 'Remove users from organization'],
        'users.manage' => ['Users', 'Full user management'],

        'leads.view' => ['Leads', 'View leads'],
        'leads.create' => ['Leads', 'Create leads'],
        'leads.update' => ['Leads', 'Edit leads'],
        'leads.delete' => ['Leads', 'Delete leads'],
        'leads.manage' => ['Leads', 'Full lead management'],

        'customers.view' => ['Customers', 'View customers'],
        'customers.create' => ['Customers', 'Create customers'],
        'customers.update' => ['Customers', 'Edit customers'],
        'customers.delete' => ['Customers', 'Delete customers'],
        'customers.manage' => ['Customers', 'Full customer management'],

        'opportunities.view' => ['Pipeline', 'View opportunities'],
        'opportunities.create' => ['Pipeline', 'Create opportunities'],
        'opportunities.update' => ['Pipeline', 'Edit opportunities'],
        'opportunities.delete' => ['Pipeline', 'Delete opportunities'],
        'opportunities.manage' => ['Pipeline', 'Full pipeline management'],

        'quotations.view' => ['Quotations', 'View quotations'],
        'quotations.create' => ['Quotations', 'Create quotations'],
        'quotations.update' => ['Quotations', 'Edit quotations'],
        'quotations.delete' => ['Quotations', 'Delete quotations'],
        'quotations.manage' => ['Quotations', 'Full quotation management'],

        'invoices.view' => ['Invoices', 'View invoices'],
        'invoices.create' => ['Invoices', 'Create invoices'],
        'invoices.update' => ['Invoices', 'Edit invoices'],
        'invoices.delete' => ['Invoices', 'Delete invoices'],
        'invoices.manage' => ['Invoices', 'Full invoice management'],

        'payments.view' => ['Payments', 'View payments'],
        'payments.create' => ['Payments', 'Record payments'],
        'payments.update' => ['Payments', 'Edit payments'],
        'payments.delete' => ['Payments', 'Delete payments'],
        'payments.manage' => ['Payments', 'Full payment management'],

        'products.view' => ['Products', 'View products'],
        'products.create' => ['Products', 'Create products'],
        'products.update' => ['Products', 'Edit products'],
        'products.delete' => ['Products', 'Delete products'],
        'products.manage' => ['Products', 'Full product management'],

        'reports.view' => ['Reports', 'View reports and analytics'],
        'reports.manage' => ['Reports', 'Manage reports and exports'],

        'finance.view' => ['Finance', 'View revenue and accounts receivable reports'],

        'tasks.view' => ['Tasks', 'View tasks and follow-ups'],
        'tasks.create' => ['Tasks', 'Create tasks'],
        'tasks.edit' => ['Tasks', 'Edit tasks'],
        'tasks.update' => ['Tasks', 'Edit tasks'],
        'tasks.delete' => ['Tasks', 'Delete tasks'],
        'tasks.archive' => ['Tasks', 'Archive tasks'],
        'tasks.restore' => ['Tasks', 'Restore archived tasks'],
        'tasks.assign' => ['Tasks', 'Assign tasks to users'],
        'tasks.comment' => ['Tasks', 'Add and manage task comments'],
        'tasks.attachments' => ['Tasks', 'Upload and manage task attachments'],
        'tasks.time-log' => ['Tasks', 'Log time against tasks'],
        'tasks.manage-status' => ['Tasks', 'Manage task status catalog'],
        'tasks.manage-priority' => ['Tasks', 'Manage task priority catalog'],
        'tasks.manage-dependencies' => ['Tasks', 'Manage task dependencies'],
        'tasks.manage-checklists' => ['Tasks', 'Manage task checklists'],
        'tasks.export' => ['Tasks', 'Export tasks'],
        'tasks.import' => ['Tasks', 'Import tasks'],
        'tasks.labels.manage' => ['Tasks', 'Attach and detach task labels'],
        'tasks.manage' => ['Tasks', 'Full task management'],

        'projects.view' => ['Projects', 'View projects'],
        'projects.create' => ['Projects', 'Create projects'],
        'projects.edit' => ['Projects', 'Edit projects'],
        'projects.delete' => ['Projects', 'Delete projects'],
        'projects.archive' => ['Projects', 'Archive projects'],
        'projects.restore' => ['Projects', 'Restore archived projects'],
        'projects.manage' => ['Projects', 'Full project management including catalogs'],
        'projects.assign-members' => ['Projects', 'Assign and manage project members'],
        'projects.manage-milestones' => ['Projects', 'Create and manage project milestones'],
        'projects.view-budget' => ['Projects', 'View project budget information'],
        'projects.manage-budget' => ['Projects', 'Manage project budget information'],
        'projects.export' => ['Projects', 'Export projects'],
        'projects.import' => ['Projects', 'Import projects'],
        'projects.progress.view' => ['Projects', 'View project progress updates'],
        'projects.progress.create' => ['Projects', 'Create project progress updates'],
        'projects.progress.update' => ['Projects', 'Update project progress updates'],
        'projects.progress.delete' => ['Projects', 'Delete project progress updates'],
        'projects.health.view' => ['Projects', 'View project health metrics'],
        'projects.reports.view' => ['Projects', 'View project reports'],
        'projects.reports.generate' => ['Projects', 'Generate project reports'],
        'projects.timeline.view' => ['Projects', 'View project timeline'],
        'projects.gantt.view' => ['Projects', 'View project Gantt chart'],
        'projects.statistics.view' => ['Projects', 'View project statistics'],
        'projects.labels.view' => ['Projects', 'View project labels'],
        'projects.labels.create' => ['Projects', 'Create project labels'],
        'projects.labels.update' => ['Projects', 'Update project labels'],
        'projects.labels.delete' => ['Projects', 'Delete project labels'],
        'projects.labels.manage' => ['Projects', 'Manage project labels'],
        'projects.watchers.view' => ['Projects', 'View project and task watchers'],
        'projects.watchers.manage' => ['Projects', 'Watch and unwatch projects and tasks'],
        'projects.mentions.view' => ['Projects', 'View mention history'],
        'projects.templates.view' => ['Projects', 'View project templates'],
        'projects.templates.create' => ['Projects', 'Create project templates'],
        'projects.templates.update' => ['Projects', 'Update project templates'],
        'projects.templates.delete' => ['Projects', 'Delete project templates'],
        'projects.templates.manage' => ['Projects', 'Full project template management'],
        'projects.recurrence.view' => ['Projects', 'View recurring tasks'],
        'projects.recurrence.manage' => ['Projects', 'Manage recurring tasks'],
        'projects.collaboration.view' => ['Projects', 'View project collaboration center'],
        'projects.collaboration.manage' => ['Projects', 'Manage collaboration pins and discussion'],
        'portal.view' => ['Client Portal', 'View client portal administration'],
        'portal.manage' => ['Client Portal', 'Manage client portal access and settings'],
        'client.approve' => ['Client Portal', 'Act on client approvals on behalf of staff'],
        'deliverable.manage' => ['Client Portal', 'Manage project deliverables'],
        'projects.automation.view' => ['Projects', 'View project automation'],
        'projects.automation.manage' => ['Projects', 'Manage project automation rules'],
        'projects.calendar.view' => ['Projects', 'View project calendar sync'],
        'projects.calendar.manage' => ['Projects', 'Manage project calendar sync'],
        'projects.notifications.manage' => ['Projects', 'Manage project notification preferences'],
        'projects.portfolios.view' => ['Projects', 'View portfolios'],
        'projects.portfolios.create' => ['Projects', 'Create portfolios'],
        'projects.portfolios.update' => ['Projects', 'Update portfolios'],
        'projects.portfolios.delete' => ['Projects', 'Delete portfolios'],
        'projects.portfolios.manage' => ['Projects', 'Full portfolio management'],
        'projects.programs.view' => ['Projects', 'View programs'],
        'projects.programs.create' => ['Projects', 'Create programs'],
        'projects.programs.update' => ['Projects', 'Update programs'],
        'projects.programs.delete' => ['Projects', 'Delete programs'],
        'projects.programs.manage' => ['Projects', 'Full program management'],
        'projects.dependencies.view' => ['Projects', 'View project dependencies'],
        'projects.dependencies.manage' => ['Projects', 'Manage project dependencies'],
        'projects.risks.view' => ['Projects', 'View project risks'],
        'projects.risks.create' => ['Projects', 'Create project risks'],
        'projects.risks.update' => ['Projects', 'Update project risks'],
        'projects.risks.delete' => ['Projects', 'Delete project risks'],
        'projects.risks.manage' => ['Projects', 'Full project risk management'],
        'projects.issues.view' => ['Projects', 'View project issues'],
        'projects.issues.create' => ['Projects', 'Create project issues'],
        'projects.issues.update' => ['Projects', 'Update project issues'],
        'projects.issues.delete' => ['Projects', 'Delete project issues'],
        'projects.issues.manage' => ['Projects', 'Full project issue management'],
        'projects.baselines.view' => ['Projects', 'View project baselines'],
        'projects.baselines.create' => ['Projects', 'Create project baselines'],
        'projects.baselines.manage' => ['Projects', 'Full project baseline management'],
        'projects.budgets.view' => ['Projects', 'View project budgets'],
        'projects.budgets.create' => ['Projects', 'Create project budgets'],
        'projects.budgets.update' => ['Projects', 'Update project budgets'],
        'projects.budgets.manage' => ['Projects', 'Full project budget management'],
        'projects.forecasts.view' => ['Projects', 'View portfolio and project forecasts'],
        'projects.executive.view' => ['Projects', 'View executive portfolio dashboard'],
        'projects.portfolio_reports.view' => ['Projects', 'View portfolio reports'],
        'projects.portfolio_reports.generate' => ['Projects', 'Generate portfolio reports'],

        'resources.view' => ['Resources', 'View resource planning and workload'],
        'resources.allocate' => ['Resources', 'Create and manage resource allocations'],
        'resources.manage' => ['Resources', 'Full resource planning administration'],
        'resources.export' => ['Resources', 'Export resource and workload reports'],

        'audit.view' => ['Audit Log', 'View organization activity and audit trail'],

        'attachments.view' => ['Attachments', 'View file attachments'],
        'attachments.create' => ['Attachments', 'Upload file attachments'],
        'attachments.delete' => ['Attachments', 'Delete file attachments'],

        'api.access' => ['API', 'Access REST API endpoints'],
        'api.tokens' => ['API', 'Manage personal API tokens'],

        'metadata.view' => ['Metadata Platform', 'View dynamic field metadata'],
        'metadata.create' => ['Metadata Platform', 'Create dynamic field definitions'],
        'metadata.update' => ['Metadata Platform', 'Edit dynamic field definitions'],
        'metadata.delete' => ['Metadata Platform', 'Archive dynamic field definitions'],
        'metadata.manage' => ['Metadata Platform', 'Manage metadata platform settings'],

        'settings.view' => ['Settings', 'View organization settings'],
        'settings.manage' => ['Settings', 'Manage organization settings'],

        'integrations.view' => ['Integrations', 'View organization integrations'],
        'integrations.manage' => ['Integrations', 'Connect and manage organization integrations'],

        'marketing.view' => ['Marketing', 'View marketing workspace, campaigns, and attribution'],
        'marketing.manage' => ['Marketing', 'Create and manage marketing campaigns and providers'],

        'imports.view' => ['Imports', 'View import sessions and previews'],
        'imports.create' => ['Imports', 'Upload files for import'],
        'imports.manage' => ['Imports', 'Full import management'],
        'imports.crm' => ['Imports', 'Import CRM entities (leads, customers, opportunities)'],
        'imports.hrms' => ['Imports', 'Import HRMS entities (employees, departments, and related masters)'],
        'imports.projects' => ['Imports', 'Import project entities (projects, milestones, tasks)'],
        'imports.administration' => ['Imports', 'Import administration entities (users)'],

        'exports.view' => ['Exports', 'View export catalog, history, and downloads'],
        'exports.create' => ['Exports', 'Generate data exports'],
        'exports.manage' => ['Exports', 'Full export management including revoke and delete'],
        'exports.crm' => ['Exports', 'Export CRM entities (leads, customers, opportunities)'],
        'exports.hrms' => ['Exports', 'Export HRMS entities (employees and related masters)'],
        'exports.projects' => ['Exports', 'Export project entities (projects, milestones, tasks)'],
        'exports.marketing' => ['Exports', 'Export marketing entities (campaigns)'],
        'exports.administration' => ['Exports', 'Export administration entities (users, roles)'],

        'bulk.crm' => ['Bulk Operations', 'Run bulk actions on CRM records'],
        'bulk.hrms' => ['Bulk Operations', 'Run bulk actions on HRMS records'],
        'bulk.projects' => ['Bulk Operations', 'Run bulk actions on project records'],
        'bulk.administration' => ['Bulk Operations', 'Run bulk actions on administration records'],
        'bulk.marketing' => ['Bulk Operations', 'Run bulk actions on marketing records'],
        'bulk.view' => ['Bulk Operations', 'View bulk operation history and progress'],
        'bulk.manage' => ['Bulk Operations', 'Full bulk operations management'],

        'assignments.view' => ['Assignments', 'View assignment pools and rules'],
        'assignments.manage' => ['Assignments', 'Manage assignment pools and rules'],

        'workflows.view' => ['Workflows', 'View workflow definitions and execution history'],
        'workflows.create' => ['Workflows', 'Create workflow definitions'],
        'workflows.update' => ['Workflows', 'Edit workflow definitions'],
        'workflows.delete' => ['Workflows', 'Delete workflow definitions'],
        'workflows.manage' => ['Workflows', 'Enable, disable, and fully manage workflows'],

        'dashboard.view' => ['Dashboard', 'View personalized workspace dashboard'],
        'dashboard.customize' => ['Dashboard', 'Customize personal dashboard layout'],
        'dashboard.manage' => ['Dashboard', 'Manage organization dashboard widgets and quick actions'],

        'hrms.view' => ['HRMS', 'View HR organization structure and employees'],
        'hrms.create' => ['HRMS', 'Create HR records'],
        'hrms.update' => ['HRMS', 'Update HR records'],
        'hrms.manage' => ['HRMS', 'Full HRMS administration'],
        'hrms.documents.manage' => ['HRMS', 'Manage employee documents'],

        'organization.branches.view' => ['Organization Settings', 'View organization branches'],
        'organization.branches.manage' => ['Organization Settings', 'Manage organization branches'],
        'organization.shifts.view' => ['Organization Settings', 'View organization shifts'],
        'organization.shifts.manage' => ['Organization Settings', 'Manage organization shifts'],
        'organization.hr_config.manage' => ['Organization Settings', 'Manage HR configuration (working days, leave policies, attendance rules)'],
        'recruitment.meeting.manage' => ['Recruitment', 'Manage recruitment meeting providers and interview links'],

        'attendance.view' => ['Attendance', 'View attendance records'],
        'attendance.manage' => ['Attendance', 'Manage attendance and shifts'],
        'attendance.correct' => ['Attendance', 'Review attendance correction requests'],
        'attendance.approve' => ['Attendance', 'Approve or reject overtime and attendance exceptions'],
        'attendance.lock' => ['Attendance', 'Freeze, lock, and reopen attendance periods'],
        'attendance.export' => ['Attendance', 'Export attendance reports and snapshots'],

        'leave.view' => ['Leave', 'View leave types, balances, and applications'],
        'leave.manage' => ['Leave', 'Manage leave configuration and applications'],
        'leave.approve' => ['Leave', 'Approve or reject leave applications'],

        'payroll.view' => ['Payroll', 'View salary structures, assignments, and payroll periods'],
        'payroll.manage' => ['Payroll', 'Manage salary components, structures, assignments, and periods'],
        'payroll.configuration' => ['Payroll', 'Manage organization payroll configuration'],
        'payroll.calculate' => ['Payroll', 'Create and execute payroll calculation runs'],
        'payroll.approve' => ['Payroll', 'Approve calculated payroll runs'],
        'payroll.publish' => ['Payroll', 'Publish approved payroll and distribute payslips'],
        'payroll.pay' => ['Payroll', 'Confirm salary payment and mark payroll as paid'],
        'payroll.lock' => ['Payroll', 'Lock payroll periods'],
        'payroll.adjustment.manage' => ['Payroll', 'Create and manage payroll adjustments'],
        'payroll.adjustment.approve' => ['Payroll', 'Approve payroll adjustments'],
        'payslip.view' => ['Payroll', 'View payslips'],
        'payslip.download' => ['Payroll', 'Download payslip PDFs'],
        'payroll.statutory.view' => ['Payroll', 'View statutory profiles, rules, and compliance validation'],
        'payroll.statutory.manage' => ['Payroll', 'Manage employee statutory profiles and run compliance validation'],
        'payroll.statutory.configuration' => ['Payroll', 'Manage statutory rule sets and versions'],
        'payroll.finance.view' => ['Payroll Finance', 'View payroll ledger, journals, and financial reports'],
        'payroll.finance.manage' => ['Payroll Finance', 'Manage payroll ledger generation, journals, and reversals'],
        'payroll.bank.export' => ['Payroll Finance', 'Generate salary bank payment export files'],
        'payroll.settlement.manage' => ['Payroll Finance', 'Manage employee final settlements'],
        'payroll.loan.manage' => ['Payroll Finance', 'Manage employee loans, advances, and reimbursements'],

        'tax.view' => ['Income Tax', 'View tax financial years, projections, declarations, and TDS'],
        'tax.manage' => ['Income Tax', 'Manage tax financial years, regimes, declarations, and configuration'],
        'tax.verify' => ['Income Tax', 'Verify investment declarations and proofs'],
        'tax.calculate' => ['Income Tax', 'Calculate tax projections and monthly TDS'],
        'form16.generate' => ['Income Tax', 'Generate Form 16 foundation records'],

        'performance.view' => ['Performance', 'View performance cycles, competencies, and review templates'],
        'performance.manage' => ['Performance', 'Manage performance cycles, competencies, rating scales, and templates'],
        'performance.configuration' => ['Performance', 'Manage organization performance configuration'],
        'performance.goal.view' => ['Performance Goals', 'View goals, KPIs, progress, and check-ins'],
        'performance.goal.manage' => ['Performance Goals', 'Manage goal library, KPI library, and goal assignments'],
        'performance.goal.update' => ['Performance Goals', 'Update goal progress and record check-ins'],
        'performance.review.view' => ['Performance Reviews', 'View performance review assignments and reviews'],
        'performance.review.manage' => ['Performance Reviews', 'Manage review assignments and close reviews'],
        'performance.review.submit' => ['Performance Reviews', 'Save drafts and submit self or manager reviews'],
        'performance.feedback.view' => ['360° Feedback', 'View feedback campaigns, requests, and reports'],
        'performance.feedback.manage' => ['360° Feedback', 'Manage feedback campaigns, participants, and templates'],
        'performance.feedback.submit' => ['360° Feedback', 'Submit assigned feedback requests'],
        'performance.appraisal.view' => ['Appraisals', 'View appraisal sessions, employee appraisals, and development plans'],
        'performance.appraisal.manage' => ['Appraisals', 'Manage appraisal sessions, ratings, and recommendations'],
        'performance.calibration.manage' => ['Appraisals', 'Manage calibration sessions and rating adjustments'],
        'performance.talent.manage' => ['Appraisals', 'Manage talent matrix classifications'],

        'ess.access' => ['Employee Self-Service', 'Access the employee self-service portal'],
        'hr.dashboard' => ['HRMS', 'View the HR organization dashboard'],
        'manager.dashboard' => ['HRMS', 'View the manager team dashboard'],
        'announcements.manage' => ['HRMS', 'Manage HR announcements'],

        'assets.view' => ['HR Operations', 'View employee assets'],
        'assets.manage' => ['HR Operations', 'Manage employee assets'],
        'employee.exit.manage' => ['HR Operations', 'Manage employee exit processes'],
        'employee.directory' => ['HR Operations', 'View employee directory'],
        'organization.calendar' => ['HR Operations', 'View organization calendar'],

        'recruitment.view' => ['Recruitment', 'View job requisitions, openings, candidates, and applications'],
        'recruitment.create' => ['Recruitment', 'Create recruitment records'],
        'recruitment.edit' => ['Recruitment', 'Edit recruitment records'],
        'recruitment.delete' => ['Recruitment', 'Delete recruitment records'],
        'recruitment.manage' => ['Recruitment', 'Full recruitment administration including approvals and publishing'],

        'recruitment.interview.view' => ['Recruitment', 'View interview stages, rounds, templates, and evaluations'],
        'recruitment.interview.create' => ['Recruitment', 'Create interview records and evaluation templates'],
        'recruitment.interview.edit' => ['Recruitment', 'Edit interview schedules and pipeline stages'],
        'recruitment.interview.delete' => ['Recruitment', 'Delete interview records and templates'],
        'recruitment.evaluate' => ['Recruitment', 'Submit structured candidate evaluations'],

        'recruitment.offer.view' => ['Recruitment', 'View offer templates, offers, approvals, negotiations, and hiring decisions'],
        'recruitment.offer.create' => ['Recruitment', 'Create offer templates and generate offers'],
        'recruitment.offer.edit' => ['Recruitment', 'Edit offers and record negotiations'],
        'recruitment.offer.delete' => ['Recruitment', 'Delete offer templates and draft offers'],
        'recruitment.offer.approve' => ['Recruitment', 'Approve or reject offer letters'],

        'recruitment.careers.manage' => ['Recruitment', 'Manage public careers site content and branding'],
        'recruitment.portal.manage' => ['Recruitment', 'View and manage candidate portal accounts'],
        'recruitment.portal.settings' => ['Recruitment', 'Configure candidate portal access rules'],

        'recruitment.analytics.view' => ['Recruitment', 'View recruitment analytics dashboards and KPIs'],
        'recruitment.reports.view' => ['Recruitment', 'View recruitment executive and operational reports'],
        'recruitment.reports.export' => ['Recruitment', 'Export recruitment reports to CSV or Excel'],
        'recruitment.reports.manage' => ['Recruitment', 'Create, share, and manage saved recruitment reports'],

        'recruitment.integration.view' => ['Recruitment', 'View recruitment provider integrations and diagnostics'],
        'recruitment.integration.manage' => ['Recruitment', 'Connect and manage recruitment external providers'],
        'recruitment.communication.manage' => ['Recruitment', 'Manage recruitment communication templates'],
        'recruitment.api.manage' => ['Recruitment', 'Manage recruitment API access documentation and tokens guidance'],
        'recruitment.webhook.view' => ['Recruitment', 'View recruitment outbound webhook endpoints and delivery logs'],
    ],

    'roles' => [
        'organization-owner' => [
            'name' => 'Organization Owner',
            'description' => 'Full access to all organization features and settings.',
            'permissions' => '*',
        ],
        'manager' => [
            'name' => 'Manager',
            'description' => 'Manage sales, team, and day-to-day operations.',
            'permissions' => [
                'users.view', 'users.create', 'users.update', 'users.delete',
                'leads.view', 'leads.create', 'leads.update', 'leads.delete', 'leads.manage',
                'customers.view', 'customers.create', 'customers.update', 'customers.delete', 'customers.manage',
                'opportunities.view', 'opportunities.create', 'opportunities.update', 'opportunities.delete', 'opportunities.manage',
                'quotations.view', 'quotations.create', 'quotations.update', 'quotations.delete', 'quotations.manage',
                'invoices.view', 'invoices.create', 'invoices.update',
                'payments.view', 'payments.create', 'payments.delete', 'payments.manage',
                'products.view', 'products.create', 'products.update', 'products.delete', 'products.manage',
                'reports.view', 'reports.manage',
                'finance.view',
                'tasks.view', 'tasks.create', 'tasks.edit', 'tasks.update', 'tasks.delete',
                'tasks.archive', 'tasks.restore', 'tasks.assign', 'tasks.comment', 'tasks.attachments',
                'tasks.time-log', 'tasks.manage-status', 'tasks.manage-priority',
                'tasks.manage-dependencies', 'tasks.manage-checklists',
                'tasks.export', 'tasks.import', 'tasks.labels.manage', 'tasks.manage',
                'projects.view', 'projects.create', 'projects.edit', 'projects.delete', 'projects.archive',
                'projects.restore', 'projects.manage', 'projects.assign-members', 'projects.manage-milestones',
                'projects.view-budget', 'projects.manage-budget', 'projects.export', 'projects.import',
                'projects.progress.view', 'projects.progress.create', 'projects.progress.update', 'projects.progress.delete',
                'projects.health.view', 'projects.reports.view', 'projects.reports.generate',
                'projects.timeline.view', 'projects.gantt.view', 'projects.statistics.view',
                'projects.labels.view', 'projects.labels.create', 'projects.labels.update', 'projects.labels.delete', 'projects.labels.manage',
                'projects.watchers.view', 'projects.watchers.manage',
                'projects.mentions.view',
                'projects.templates.view', 'projects.templates.create', 'projects.templates.update', 'projects.templates.delete', 'projects.templates.manage',
                'projects.recurrence.view', 'projects.recurrence.manage',
                'projects.collaboration.view', 'projects.collaboration.manage',
                'portal.view', 'portal.manage', 'client.approve', 'deliverable.manage',
                'projects.automation.view', 'projects.automation.manage',
                'projects.calendar.view', 'projects.calendar.manage',
                'projects.notifications.manage',
                'projects.portfolios.view', 'projects.portfolios.create', 'projects.portfolios.update', 'projects.portfolios.delete', 'projects.portfolios.manage',
                'projects.programs.view', 'projects.programs.create', 'projects.programs.update', 'projects.programs.delete', 'projects.programs.manage',
                'projects.dependencies.view', 'projects.dependencies.manage',
                'projects.risks.view', 'projects.risks.create', 'projects.risks.update', 'projects.risks.delete', 'projects.risks.manage',
                'projects.issues.view', 'projects.issues.create', 'projects.issues.update', 'projects.issues.delete', 'projects.issues.manage',
                'projects.baselines.view', 'projects.baselines.create', 'projects.baselines.manage',
                'projects.budgets.view', 'projects.budgets.create', 'projects.budgets.update', 'projects.budgets.manage',
                'projects.forecasts.view',
                'projects.executive.view',
                'projects.portfolio_reports.view', 'projects.portfolio_reports.generate',
                'resources.view', 'resources.allocate', 'resources.manage', 'resources.export',
                'audit.view',
                'attachments.view', 'attachments.create', 'attachments.delete',
                'api.tokens', 'api.access',
                'metadata.view', 'metadata.create', 'metadata.update', 'metadata.delete', 'metadata.manage',
                'settings.view',
                'integrations.view', 'integrations.manage',
                'marketing.view', 'marketing.manage',
                'imports.view', 'imports.create', 'imports.manage',
                'imports.crm', 'imports.hrms', 'imports.projects', 'imports.administration',
                'exports.view', 'exports.create', 'exports.manage',
                'exports.crm', 'exports.hrms', 'exports.projects', 'exports.marketing', 'exports.administration',
                'bulk.view', 'bulk.manage', 'bulk.crm', 'bulk.hrms', 'bulk.projects', 'bulk.administration', 'bulk.marketing',
                'assignments.view', 'assignments.manage',
                'workflows.view', 'workflows.create', 'workflows.update', 'workflows.delete', 'workflows.manage',
                'dashboard.view', 'dashboard.customize', 'dashboard.manage',
                'hrms.view',
                'manager.dashboard',
                'attendance.view', 'attendance.correct',
                'leave.view', 'leave.approve',
                'performance.view',
                'performance.goal.view', 'performance.goal.update',
                'performance.review.view', 'performance.review.submit',
                'performance.feedback.view', 'performance.feedback.submit',
                'performance.appraisal.view',
                'ess.access',
                'employee.directory', 'organization.calendar',
                'recruitment.view',
                'recruitment.analytics.view',
                'recruitment.reports.view',
            ],
        ],
        'sales-executive' => [

            'name' => 'Sales Executive',
            'description' => 'Manage leads, customers, and sales documents.',
            'permissions' => [
                'leads.view', 'leads.create', 'leads.update', 'leads.delete',
                'customers.view', 'customers.create', 'customers.update',
                'opportunities.view', 'opportunities.create', 'opportunities.update', 'opportunities.delete',
                'quotations.view', 'quotations.create', 'quotations.update',
                'products.view',
                'reports.view',
                // Bulk CRM actions remain scoped by LeadVisibilityService / entity adapters.
                'bulk.view', 'bulk.crm',
                'tasks.view', 'tasks.create', 'tasks.edit', 'tasks.update', 'tasks.delete',
                'tasks.assign', 'tasks.comment', 'tasks.attachments', 'tasks.time-log',
                'tasks.manage-checklists', 'tasks.manage-dependencies',
                'tasks.labels.manage',
                'projects.view', 'projects.create', 'projects.edit',
                'projects.progress.view', 'projects.progress.create',
                'projects.health.view', 'projects.reports.view',
                'projects.timeline.view', 'projects.gantt.view', 'projects.statistics.view',
                'projects.labels.view',
                'projects.watchers.view', 'projects.watchers.manage',
                'projects.mentions.view',
                'projects.templates.view',
                'projects.recurrence.view',
                'projects.collaboration.view',
                'portal.view',
                'projects.automation.view',
                'projects.calendar.view',
                'projects.notifications.manage',
                'projects.portfolios.view', 'projects.portfolios.create',
                'projects.programs.view', 'projects.programs.create',
                'projects.dependencies.view',
                'projects.risks.view', 'projects.risks.create',
                'projects.issues.view', 'projects.issues.create',
                'projects.baselines.view', 'projects.baselines.create',
                'projects.budgets.view', 'projects.budgets.create',
                'projects.forecasts.view',
                'projects.executive.view',
                'projects.portfolio_reports.view',
                'resources.view', 'resources.allocate',
                'audit.view',
                'attachments.view', 'attachments.create',
                'dashboard.view', 'dashboard.customize',
            ],
        ],
        'hr' => [
            'name' => 'HR',
            'description' => 'Manage team members and HR-related reports.',
            'permissions' => [
                'users.view', 'users.create', 'users.update',
                'reports.view',
                'audit.view',
                'hrms.view', 'hrms.create', 'hrms.update', 'hrms.manage', 'hrms.documents.manage',
                'organization.branches.view', 'organization.branches.manage',
                'organization.shifts.view', 'organization.shifts.manage',
                'organization.hr_config.manage',
                'hr.dashboard', 'announcements.manage',
                'attendance.view', 'attendance.manage', 'attendance.correct', 'attendance.approve',
                'attendance.lock', 'attendance.export',
                'leave.view', 'leave.manage', 'leave.approve',
                'payroll.view', 'payroll.manage', 'payroll.configuration', 'payroll.calculate',
                'payroll.approve', 'payroll.publish', 'payroll.pay', 'payroll.lock',
                'payroll.adjustment.manage', 'payroll.adjustment.approve',
                'payslip.view', 'payslip.download',
                'payroll.statutory.view', 'payroll.statutory.manage', 'payroll.statutory.configuration',
                'payroll.finance.view', 'payroll.finance.manage', 'payroll.bank.export',
                'payroll.settlement.manage', 'payroll.loan.manage',
                'tax.view', 'tax.manage', 'tax.verify', 'tax.calculate', 'form16.generate',
                'performance.view', 'performance.manage', 'performance.configuration',
                'performance.goal.view', 'performance.goal.manage', 'performance.goal.update',
                'performance.review.view', 'performance.review.manage', 'performance.review.submit',
                'performance.feedback.view', 'performance.feedback.manage', 'performance.feedback.submit',
                'performance.appraisal.view', 'performance.appraisal.manage',
                'performance.calibration.manage', 'performance.talent.manage',
                'ess.access',
                'assets.view', 'assets.manage',
                'employee.exit.manage',
                'employee.directory', 'organization.calendar',
                'recruitment.view', 'recruitment.create', 'recruitment.edit',
                'recruitment.delete', 'recruitment.manage',
                'recruitment.interview.view', 'recruitment.interview.create',
                'recruitment.interview.edit', 'recruitment.interview.delete',
                'recruitment.evaluate',
                'recruitment.offer.view', 'recruitment.offer.create',
                'recruitment.offer.edit', 'recruitment.offer.delete',
                'recruitment.offer.approve',
                'recruitment.careers.manage', 'recruitment.portal.manage',
                'recruitment.portal.settings',
                'recruitment.analytics.view',
                'recruitment.reports.view',
                'recruitment.reports.export',
                'recruitment.reports.manage',
                'recruitment.integration.view',
                'recruitment.integration.manage',
                'recruitment.meeting.manage',
                'recruitment.communication.manage',
                'recruitment.api.manage',
                'recruitment.webhook.view',
                'imports.view', 'imports.create', 'imports.manage', 'imports.hrms',
                'exports.view', 'exports.create', 'exports.manage', 'exports.hrms',
                'bulk.view', 'bulk.manage', 'bulk.hrms',
                'dashboard.view', 'dashboard.customize', 'dashboard.manage',
            ],
        ],
        'support' => [

            'name' => 'Support',
            'description' => 'View and assist with customer records.',
            'permissions' => [
                'customers.view', 'customers.update',
                'leads.view',
                'opportunities.view',
                'invoices.view',
                'payments.view',
                'finance.view',
                'reports.view',
                'tasks.view', 'tasks.create', 'tasks.edit', 'tasks.update',
                'tasks.assign', 'tasks.comment', 'tasks.attachments', 'tasks.time-log',
                'tasks.manage-checklists',
                'projects.view',
                'projects.progress.view', 'projects.health.view',
                'projects.timeline.view', 'projects.gantt.view', 'projects.statistics.view',
                'projects.labels.view',
                'projects.watchers.view',
                'projects.mentions.view',
                'projects.templates.view',
                'projects.recurrence.view',
                'projects.collaboration.view',
                'projects.automation.view',
                'projects.calendar.view',
                'projects.portfolios.view',
                'projects.programs.view',
                'projects.dependencies.view',
                'projects.risks.view',
                'projects.issues.view',
                'projects.baselines.view',
                'projects.budgets.view',
                'projects.forecasts.view',
                'projects.executive.view',
                'projects.portfolio_reports.view',
                'resources.view',
                'audit.view',
                'attachments.view',
                'dashboard.view', 'dashboard.customize',
            ],
        ],
        'employee' => [
            'name' => 'Employee',
            'description' => 'Basic read access to CRM data.',
            'permissions' => [
                'leads.view',
                'customers.view',
                'products.view',
                'tasks.view',
                'projects.view',
                'projects.progress.view', 'projects.health.view',
                'projects.timeline.view', 'projects.statistics.view',
                'projects.labels.view',
                'projects.watchers.view',
                'projects.mentions.view',
                'projects.templates.view',
                'projects.recurrence.view',
                'projects.collaboration.view',
                'projects.automation.view',
                'projects.calendar.view',
                'projects.portfolios.view',
                'projects.programs.view',
                'projects.dependencies.view',
                'projects.risks.view',
                'projects.issues.view',
                'projects.baselines.view',
                'projects.budgets.view',
                'projects.forecasts.view',
                'projects.executive.view',
                'projects.portfolio_reports.view',
                'resources.view',
                'ess.access',
                'payslip.view', 'payslip.download',
                'employee.directory', 'organization.calendar',
                'performance.goal.view', 'performance.goal.update',
                'performance.review.view', 'performance.review.submit',
                'performance.feedback.view', 'performance.feedback.submit',
                'performance.appraisal.view',
                'dashboard.view', 'dashboard.customize',
            ],
        ],

    ],

    'legacy_role_map' => [
        'owner' => 'organization-owner',
        'organization-owner' => 'organization-owner',
        'manager' => 'manager',
        'sales-executive' => 'sales-executive',
        'sales_executive' => 'sales-executive',
        'hr' => 'hr',
        'support' => 'support',
        'employee' => 'employee',
    ],
];
