<?php

return [
    'defaults' => [
        'lead' => 'Lead',
        'leads' => 'Leads',
        'customer' => 'Customer',
        'customers' => 'Customers',
        'pipeline' => 'Pipeline',
        'deal' => 'Deal',
        'deals' => 'Deals',
        'product' => 'Product',
        'products' => 'Products',
        'quotation' => 'Quotation',
        'quotations' => 'Quotations',
        'invoice' => 'Invoice',
        'invoices' => 'Invoices',
        'payment' => 'Payment',
        'payments' => 'Payments',
    ],

    'industries' => [
        'general' => [
            'name' => 'General / Sales',
            'description' => 'Standard CRM terminology for most businesses.',
            'terms' => [],
        ],
        'real_estate' => [
            'name' => 'Real Estate',
            'description' => 'Property sales, rentals, and brokerage.',
            'terms' => [
                'lead' => 'Prospect',
                'leads' => 'Prospects',
                'customer' => 'Client',
                'customers' => 'Clients',
                'pipeline' => 'Transactions',
                'deal' => 'Transaction',
                'deals' => 'Transactions',
                'product' => 'Property',
                'products' => 'Properties',
                'quotation' => 'Proposal',
                'quotations' => 'Proposals',
            ],
        ],
        'healthcare' => [
            'name' => 'Healthcare',
            'description' => 'Clinics, hospitals, and patient services.',
            'terms' => [
                'lead' => 'Referral',
                'leads' => 'Referrals',
                'customer' => 'Patient',
                'customers' => 'Patients',
                'pipeline' => 'Care Pipeline',
                'deal' => 'Case',
                'deals' => 'Cases',
                'product' => 'Service',
                'products' => 'Services',
                'quotation' => 'Estimate',
                'quotations' => 'Estimates',
            ],
        ],
        'software_saas' => [
            'name' => 'Software & SaaS',
            'description' => 'Technology products and subscription sales.',
            'terms' => [
                'customer' => 'Account',
                'customers' => 'Accounts',
                'pipeline' => 'Sales Pipeline',
                'deal' => 'Opportunity',
                'deals' => 'Opportunities',
                'product' => 'Plan',
                'products' => 'Plans',
                'quotation' => 'Proposal',
                'quotations' => 'Proposals',
            ],
        ],
        'consulting' => [
            'name' => 'Consulting & Services',
            'description' => 'Professional services and project work.',
            'terms' => [
                'lead' => 'Inquiry',
                'leads' => 'Inquiries',
                'customer' => 'Client',
                'customers' => 'Clients',
                'pipeline' => 'Engagements',
                'deal' => 'Project',
                'deals' => 'Projects',
                'product' => 'Service',
                'products' => 'Services',
                'quotation' => 'Proposal',
                'quotations' => 'Proposals',
            ],
        ],
        'manufacturing' => [
            'name' => 'Manufacturing',
            'description' => 'Production, distribution, and B2B sales.',
            'terms' => [
                'lead' => 'Inquiry',
                'leads' => 'Inquiries',
                'customer' => 'Buyer',
                'customers' => 'Buyers',
                'pipeline' => 'Sales Pipeline',
                'deal' => 'Order',
                'deals' => 'Orders',
                'quotation' => 'Quote',
                'quotations' => 'Quotes',
            ],
        ],
        'retail' => [
            'name' => 'Retail & E-commerce',
            'description' => 'Storefront and online retail sales.',
            'terms' => [
                'lead' => 'Shopper',
                'leads' => 'Shoppers',
                'customer' => 'Buyer',
                'customers' => 'Buyers',
                'pipeline' => 'Sales Funnel',
                'deal' => 'Sale',
                'deals' => 'Sales',
                'product' => 'Item',
                'products' => 'Items',
                'quotation' => 'Offer',
                'quotations' => 'Offers',
                'invoice' => 'Receipt',
                'invoices' => 'Receipts',
            ],
        ],
        'education' => [
            'name' => 'Education & Training',
            'description' => 'Schools, courses, and training providers.',
            'terms' => [
                'lead' => 'Applicant',
                'leads' => 'Applicants',
                'customer' => 'Student',
                'customers' => 'Students',
                'pipeline' => 'Admissions',
                'deal' => 'Enrollment',
                'deals' => 'Enrollments',
                'product' => 'Course',
                'products' => 'Courses',
                'quotation' => 'Fee Quote',
                'quotations' => 'Fee Quotes',
            ],
        ],
        'immigration' => [
            'name' => 'Immigration & Visa Consultancy',
            'description' => 'Visa applications, immigration cases, documentation, and travel consultancy.',
            'terms' => [
                'lead' => 'Enquiry',
                'leads' => 'Enquiries',
                'customer' => 'Applicant',
                'customers' => 'Applicants',
                'pipeline' => 'Visa Pipeline',
                'deal' => 'Application',
                'deals' => 'Applications',
                'product' => 'Visa Service',
                'products' => 'Visa Services',
                'quotation' => 'Quote',
                'quotations' => 'Quotes',
            ],
        ],
    ],

    'labels' => [
        'lead' => 'Singular — top of funnel contact',
        'leads' => 'Plural — module name',
        'customer' => 'Singular — converted contact',
        'customers' => 'Plural — module name',
        'pipeline' => 'Pipeline module name',
        'deal' => 'Singular — pipeline record',
        'deals' => 'Plural — pipeline records',
        'product' => 'Singular — catalog item',
        'products' => 'Plural — module name',
        'quotation' => 'Singular — sales document',
        'quotations' => 'Plural — module name',
        'invoice' => 'Singular — billing document',
        'invoices' => 'Plural — module name',
        'payment' => 'Singular — payment record',
        'payments' => 'Plural — module name',
    ],
];
