<?php

use App\Workflow\Actions\AddNoteAction;
use App\Workflow\Actions\AssignOwnerAction;
use App\Workflow\Actions\ChangeCustomerLifecycleAction;
use App\Workflow\Actions\ChangeLeadStatusAction;
use App\Workflow\Actions\CreateActivityAction;
use App\Workflow\Actions\CreateTaskAction;
use App\Workflow\Actions\NotifyUserAction;
use App\Workflow\Actions\ReassignOwnerAction;
use App\Workflow\Actions\SendCrmEmailAction;
use App\Workflow\Actions\UpdateMetadataAction;

$hrmsTriggers = require __DIR__.'/hrms_workflow_triggers.php';
$hrmsEntities = array_values(array_unique(array_column($hrmsTriggers, 'entity')));

return [
    'max_depth' => 10,

    'triggers' => array_merge([
        'lead.created' => ['entity' => 'lead', 'label' => 'Lead created', 'description' => 'Runs when a lead is created.'],
        'lead.updated' => ['entity' => 'lead', 'label' => 'Lead updated', 'description' => 'Runs after lead details change.'],
        'lead.assigned' => ['entity' => 'lead', 'label' => 'Lead assigned', 'description' => 'Runs when a lead owner changes.'],
        'lead.converted' => ['entity' => 'lead', 'label' => 'Lead converted', 'description' => 'Runs when a lead is converted to a customer.'],
        'customer.created' => ['entity' => 'customer', 'label' => 'Customer created', 'description' => 'Runs when a customer is created.'],
        'customer.updated' => ['entity' => 'customer', 'label' => 'Customer updated', 'description' => 'Runs after customer details change.'],
        'opportunity.created' => ['entity' => 'opportunity', 'label' => 'Opportunity created', 'description' => 'Runs when an opportunity is created.'],
        'opportunity.stage_changed' => ['entity' => 'opportunity', 'label' => 'Opportunity stage changed', 'description' => 'Runs when an opportunity moves stage.'],
        'opportunity.won' => ['entity' => 'opportunity', 'label' => 'Opportunity won', 'description' => 'Runs when an opportunity is marked closed won.'],
        'opportunity.lost' => ['entity' => 'opportunity', 'label' => 'Opportunity lost', 'description' => 'Runs when an opportunity is marked closed lost.'],
        'quotation.accepted' => ['entity' => 'quotation', 'label' => 'Quotation accepted', 'description' => 'Runs when a quotation is accepted.'],
        'sales_order.confirmed' => ['entity' => 'sales_order', 'label' => 'Sales order confirmed', 'description' => 'Runs when a sales order is confirmed.'],
        'customer.first_invoice' => ['entity' => 'invoice', 'label' => 'Customer first invoice', 'description' => 'Runs when a customer receives their first issued invoice.'],
        'customer.first_payment' => ['entity' => 'payment', 'label' => 'Customer first payment', 'description' => 'Runs when the first payment is recorded for a customer.'],
        'ticket.created' => ['entity' => 'ticket', 'label' => 'Ticket created', 'description' => 'Runs when a customer ticket is created.'],
        'ticket.status_changed' => ['entity' => 'ticket', 'label' => 'Ticket status changed', 'description' => 'Runs when a ticket moves between Open, Pending, Resolved, or Closed.'],
        'ticket.assigned' => ['entity' => 'ticket', 'label' => 'Ticket assigned', 'description' => 'Runs when a ticket assignee changes.'],
        'ticket.escalated' => ['entity' => 'ticket', 'label' => 'Ticket escalated', 'description' => 'Runs when a ticket priority is raised to high or urgent.'],
        'customer.lifecycle_changed' => ['entity' => 'customer', 'label' => 'Customer lifecycle changed', 'description' => 'Runs when a customer lifecycle stage changes.'],
        'invoice.created' => ['entity' => 'invoice', 'label' => 'Invoice created', 'description' => 'Runs when an invoice is created.'],
        'invoice.issued' => ['entity' => 'invoice', 'label' => 'Invoice issued', 'description' => 'Runs when an invoice is issued.'],
        'invoice.due_soon' => ['entity' => 'invoice', 'label' => 'Invoice due soon', 'description' => 'Runs when an invoice is approaching its due date.'],
        'invoice.overdue' => ['entity' => 'invoice', 'label' => 'Invoice overdue', 'description' => 'Runs when an invoice is past due with a remaining balance.'],
        'payment.received' => ['entity' => 'payment', 'label' => 'Payment received', 'description' => 'Runs when a payment is recorded.'],
        'payment.confirmed' => ['entity' => 'payment', 'label' => 'Payment confirmed', 'description' => 'Runs after a payment confirmation is sent to the customer.'],
        'quotation.created' => ['entity' => 'quotation', 'label' => 'Quotation created', 'description' => 'Runs when a quotation is created.'],
        'quotation.sent' => ['entity' => 'quotation', 'label' => 'Quotation sent', 'description' => 'Runs when a quotation is emailed or marked sent.'],
        'quotation.expiring' => ['entity' => 'quotation', 'label' => 'Quotation expiring', 'description' => 'Runs when a quotation is approaching its valid-until date.'],
        'sales_order.created' => ['entity' => 'sales_order', 'label' => 'Sales order created', 'description' => 'Runs when a sales order is created.'],
        'sales_order.status_changed' => ['entity' => 'sales_order', 'label' => 'Sales order status changed', 'description' => 'Runs when a sales order status changes.'],
        'adjustment_note.created' => ['entity' => 'adjustment_note', 'label' => 'Credit/debit note created', 'description' => 'Runs when a credit or debit note is created.'],
        'adjustment_note.applied' => ['entity' => 'adjustment_note', 'label' => 'Credit/debit note applied', 'description' => 'Runs when a credit or debit note is applied to an invoice.'],
        'marketing.lead_imported' => ['entity' => 'lead', 'label' => 'Marketing lead imported', 'description' => 'Runs when a marketing provider imports a lead.'],
        'project.created' => ['entity' => 'project', 'label' => 'Project created', 'description' => 'Runs when a project is created.'],
        'project.updated' => ['entity' => 'project', 'label' => 'Project updated', 'description' => 'Runs after project details change.'],
        'project.archived' => ['entity' => 'project', 'label' => 'Project archived', 'description' => 'Runs when a project is archived.'],
        'project.restored' => ['entity' => 'project', 'label' => 'Project restored', 'description' => 'Runs when an archived project is restored.'],
        'project.member_assigned' => ['entity' => 'project', 'label' => 'Project member assigned', 'description' => 'Runs when a member is assigned to a project.'],
        'project.member_removed' => ['entity' => 'project', 'label' => 'Project member removed', 'description' => 'Runs when a member is removed from a project.'],
        'project.milestone_created' => ['entity' => 'project', 'label' => 'Project milestone created', 'description' => 'Runs when a project milestone is created.'],
        'project.milestone_completed' => ['entity' => 'project', 'label' => 'Project milestone completed', 'description' => 'Runs when a project milestone is completed.'],
        'project.lifecycle_changed' => ['entity' => 'project', 'label' => 'Project lifecycle changed', 'description' => 'Runs when a project lifecycle stage changes.'],
        'project.health.changed' => ['entity' => 'project', 'label' => 'Project health changed', 'description' => 'Runs when calculated project health status changes.'],
        'project.progress.updated' => ['entity' => 'project', 'label' => 'Project progress updated', 'description' => 'Runs when a manual progress update is submitted.'],
        'project.milestone.completed' => ['entity' => 'project', 'label' => 'Milestone completed (progress)', 'description' => 'Runs when milestone progress tracking marks a milestone complete.'],
        'project.milestone.delayed' => ['entity' => 'project', 'label' => 'Milestone delayed', 'description' => 'Runs when a milestone is detected as delayed.'],
        'project.completed' => ['entity' => 'project', 'label' => 'Project completed', 'description' => 'Runs when project health transitions to completed.'],
        'project.delayed' => ['entity' => 'project', 'label' => 'Project delayed', 'description' => 'Runs when project health transitions to delayed.'],
        'project.timeline.updated' => ['entity' => 'project', 'label' => 'Project timeline updated', 'description' => 'Runs when the project timeline is republished.'],
        'project.report.generated' => ['entity' => 'project', 'label' => 'Project report generated', 'description' => 'Runs when a project report is generated.'],
        'project.label.created' => ['entity' => 'project_label', 'label' => 'Project label created', 'description' => 'Runs when a project label is created.'],
        'project.label.updated' => ['entity' => 'project_label', 'label' => 'Project label updated', 'description' => 'Runs when a project label is updated.'],
        'project.label.deleted' => ['entity' => 'project_label', 'label' => 'Project label deleted', 'description' => 'Runs when a project label is deleted.'],
        'task.label.attached' => ['entity' => 'task', 'label' => 'Task label attached', 'description' => 'Runs when a label is attached to a task.'],
        'task.label.detached' => ['entity' => 'task', 'label' => 'Task label detached', 'description' => 'Runs when a label is detached from a task.'],
        'project.watcher.added' => ['entity' => 'project', 'label' => 'Project watcher added', 'description' => 'Runs when a user starts watching a project.'],
        'project.watcher.removed' => ['entity' => 'project', 'label' => 'Project watcher removed', 'description' => 'Runs when a user stops watching a project.'],
        'task.watcher.added' => ['entity' => 'task', 'label' => 'Task watcher added', 'description' => 'Runs when a user starts watching a task.'],
        'task.watcher.removed' => ['entity' => 'task', 'label' => 'Task watcher removed', 'description' => 'Runs when a user stops watching a task.'],
        'comment.mentioned' => ['entity' => 'project_mention', 'label' => 'User mentioned in comment', 'description' => 'Runs when a user is mentioned in a comment.'],
        'task.recurrence.created' => ['entity' => 'task_recurrence', 'label' => 'Task recurrence created', 'description' => 'Runs when a recurring task rule is created.'],
        'task.recurrence.generated' => ['entity' => 'task_recurrence', 'label' => 'Recurring task generated', 'description' => 'Runs when a recurring task occurrence is generated.'],
        'task.recurrence.deleted' => ['entity' => 'task_recurrence', 'label' => 'Task recurrence deleted', 'description' => 'Runs when a recurring task rule is deleted.'],
        'project.template.created' => ['entity' => 'project_template', 'label' => 'Project template created', 'description' => 'Runs when a project template is created.'],
        'project.template.updated' => ['entity' => 'project_template', 'label' => 'Project template updated', 'description' => 'Runs when a project template is updated.'],
        'project.template.deleted' => ['entity' => 'project_template', 'label' => 'Project template deleted', 'description' => 'Runs when a project template is deleted.'],
        'project.created_from_template' => ['entity' => 'project', 'label' => 'Project created from template', 'description' => 'Runs when a project is created from a template.'],
        'project.collaboration.updated' => ['entity' => 'project', 'label' => 'Project collaboration updated', 'description' => 'Runs when collaboration pins or discussion change.'],
        'deliverable.created' => ['entity' => 'deliverable', 'label' => 'Deliverable created', 'description' => 'Runs when a project deliverable is created.'],
        'deliverable.submitted' => ['entity' => 'deliverable', 'label' => 'Deliverable submitted', 'description' => 'Runs when a deliverable is submitted for client review.'],
        'client.approved' => ['entity' => 'client_approval', 'label' => 'Client approved', 'description' => 'Runs when a client approves a deliverable or approval request.'],
        'client.rejected' => ['entity' => 'client_approval', 'label' => 'Client rejected', 'description' => 'Runs when a client rejects a deliverable or approval request.'],
        'discussion.created' => ['entity' => 'client_discussion', 'label' => 'Client discussion created', 'description' => 'Runs when a client-visible discussion message is posted.'],
        'portal.accessed' => ['entity' => 'client_user', 'label' => 'Portal accessed', 'description' => 'Runs when a client user accesses the portal.'],
        'notification.preference.updated' => ['entity' => 'project', 'label' => 'Notification preference updated', 'description' => 'Runs when project notification preferences change.'],
        'portfolio.created' => ['entity' => 'portfolio', 'label' => 'Portfolio created', 'description' => 'Runs when a portfolio is created.'],
        'portfolio.updated' => ['entity' => 'portfolio', 'label' => 'Portfolio updated', 'description' => 'Runs when a portfolio is updated.'],
        'portfolio.deleted' => ['entity' => 'portfolio', 'label' => 'Portfolio deleted', 'description' => 'Runs when a portfolio is deleted.'],
        'program.created' => ['entity' => 'program', 'label' => 'Program created', 'description' => 'Runs when a program is created.'],
        'program.updated' => ['entity' => 'program', 'label' => 'Program updated', 'description' => 'Runs when a program is updated.'],
        'project.dependency.created' => ['entity' => 'project', 'label' => 'Project dependency created', 'description' => 'Runs when a cross-project dependency is created.'],
        'project.dependency.updated' => ['entity' => 'project', 'label' => 'Project dependency updated', 'description' => 'Runs when a cross-project dependency is updated.'],
        'project.risk.created' => ['entity' => 'project_risk', 'label' => 'Project risk created', 'description' => 'Runs when a project risk is created.'],
        'project.risk.updated' => ['entity' => 'project_risk', 'label' => 'Project risk updated', 'description' => 'Runs when a project risk is updated.'],
        'project.risk.escalated' => ['entity' => 'project_risk', 'label' => 'Project risk escalated', 'description' => 'Runs when a project risk is escalated.'],
        'project.issue.created' => ['entity' => 'project_issue', 'label' => 'Project issue created', 'description' => 'Runs when a project issue is created.'],
        'project.issue.resolved' => ['entity' => 'project_issue', 'label' => 'Project issue resolved', 'description' => 'Runs when a project issue is resolved.'],
        'project.baseline.created' => ['entity' => 'project_baseline', 'label' => 'Project baseline created', 'description' => 'Runs when a project baseline is captured.'],
        'project.budget.updated' => ['entity' => 'project_budget', 'label' => 'Project budget updated', 'description' => 'Runs when a project budget is created or updated.'],
        'portfolio.health.updated' => ['entity' => 'portfolio', 'label' => 'Portfolio health updated', 'description' => 'Runs when portfolio health rollup is recalculated.'],
        'portfolio.report.generated' => ['entity' => 'portfolio_report', 'label' => 'Portfolio report generated', 'description' => 'Runs when a portfolio report is generated.'],
        'forecast.generated' => ['entity' => 'portfolio', 'label' => 'Forecast generated', 'description' => 'Runs when a project or portfolio forecast is generated.'],
        'task.created' => ['entity' => 'task', 'label' => 'Task created', 'description' => 'Runs when a task is created.'],
        'task.updated' => ['entity' => 'task', 'label' => 'Task updated', 'description' => 'Runs after task details change.'],
        'task.assigned' => ['entity' => 'task', 'label' => 'Task assigned', 'description' => 'Runs when a task is assigned to a user.'],
        'task.reassigned' => ['entity' => 'task', 'label' => 'Task reassigned', 'description' => 'Runs when a task is reassigned to another user.'],
        'task.started' => ['entity' => 'task', 'label' => 'Task started', 'description' => 'Runs when a task moves to in progress.'],
        'task.completed' => ['entity' => 'task', 'label' => 'Task completed', 'description' => 'Runs when a task is completed.'],
        'task.archived' => ['entity' => 'task', 'label' => 'Task archived', 'description' => 'Runs when a task is archived.'],
        'task.restored' => ['entity' => 'task', 'label' => 'Task restored', 'description' => 'Runs when an archived task is restored.'],
        'task.dependency_created' => ['entity' => 'task', 'label' => 'Task dependency created', 'description' => 'Runs when a task dependency is created.'],
        'task.dependency_removed' => ['entity' => 'task', 'label' => 'Task dependency removed', 'description' => 'Runs when a task dependency is removed.'],
        'task.checklist_completed' => ['entity' => 'task', 'label' => 'Task checklist completed', 'description' => 'Runs when a checklist item is completed.'],
        'task.comment_added' => ['entity' => 'task', 'label' => 'Task comment added', 'description' => 'Runs when a comment is added to a task.'],
        'task.time_logged' => ['entity' => 'task', 'label' => 'Task time logged', 'description' => 'Runs when time is logged against a task.'],
        'resource.allocated' => ['entity' => 'resource_allocation', 'label' => 'Resource allocated', 'description' => 'Runs when a resource allocation is created.'],
        'resource.allocation_updated' => ['entity' => 'resource_allocation', 'label' => 'Resource allocation updated', 'description' => 'Runs when a resource allocation is updated.'],
        'resource.released' => ['entity' => 'resource_allocation', 'label' => 'Resource released', 'description' => 'Runs when a resource allocation is deleted/released.'],
        'resource.capacity_exceeded' => ['entity' => 'resource_allocation', 'label' => 'Capacity exceeded', 'description' => 'Runs when an allocation pushes an employee over capacity.'],
        'resource.overallocation_detected' => ['entity' => 'resource_allocation', 'label' => 'Overallocation detected', 'description' => 'Runs when overallocation is detected for an employee.'],
    ], $hrmsTriggers),

    'operators' => [
        'equals', 'not_equals', 'contains', 'does_not_contain', 'starts_with',
        'ends_with', 'greater_than', 'greater_than_equal', 'less_than',
        'less_than_equal', 'between', 'in_list', 'not_in_list', 'empty', 'not_empty',
    ],

    'operator_definitions' => [
        'equals' => ['label' => 'Equals', 'value_type' => 'single'],
        'not_equals' => ['label' => 'Does not equal', 'value_type' => 'single'],
        'contains' => ['label' => 'Contains', 'value_type' => 'single'],
        'does_not_contain' => ['label' => 'Does not contain', 'value_type' => 'single'],
        'starts_with' => ['label' => 'Starts with', 'value_type' => 'single'],
        'ends_with' => ['label' => 'Ends with', 'value_type' => 'single'],
        'greater_than' => ['label' => 'Greater than', 'value_type' => 'single'],
        'greater_than_equal' => ['label' => 'Greater than or equal', 'value_type' => 'single'],
        'less_than' => ['label' => 'Less than', 'value_type' => 'single'],
        'less_than_equal' => ['label' => 'Less than or equal', 'value_type' => 'single'],
        'between' => ['label' => 'Between', 'value_type' => 'between'],
        'in_list' => ['label' => 'In list', 'value_type' => 'list'],
        'not_in_list' => ['label' => 'Not in list', 'value_type' => 'list'],
        'empty' => ['label' => 'Is empty', 'value_type' => 'none'],
        'not_empty' => ['label' => 'Is not empty', 'value_type' => 'none'],
    ],

    'actions' => [
        'assign_owner' => [
            'label' => 'Assign owner automatically', 'description' => 'Uses the configured assignment rules.',
            'handler' => AssignOwnerAction::class, 'entities' => ['lead', 'customer', 'opportunity'], 'fields' => [], 'form_fields' => [],
        ],
        'reassign_owner' => [
            'label' => 'Assign a specific owner', 'description' => 'Assigns the record to an organization member.',
            'handler' => ReassignOwnerAction::class, 'entities' => ['lead', 'customer', 'opportunity'], 'fields' => ['user_id'],
            'form_fields' => ['user_id' => ['label' => 'Owner', 'type' => 'user', 'required' => true]],
        ],
        'create_task' => [
            'label' => 'Create task', 'description' => 'Creates a task related to the triggering record.',
            'handler' => CreateTaskAction::class, 'entities' => ['lead', 'customer', 'opportunity', 'project', 'task', 'ticket', 'quotation', 'sales_order', 'invoice', 'payment'], 'fields' => ['title'],
            'form_fields' => [
                'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
                'priority' => ['label' => 'Priority', 'type' => 'select', 'options' => ['low' => 'Low', 'medium' => 'Medium', 'high' => 'High']],
                'due_at' => ['label' => 'Due date/time', 'type' => 'datetime-local'],
                'assigned_to' => ['label' => 'Assignee', 'type' => 'user'],
            ],
        ],
        'create_activity' => [
            'label' => 'Create activity', 'description' => 'Adds an activity entry to the record timeline.',
            'handler' => CreateActivityAction::class, 'entities' => ['lead', 'customer', 'opportunity', 'invoice', 'payment', 'quotation', 'sales_order', 'adjustment_note', 'ticket'], 'fields' => ['event'],
            'form_fields' => [
                'event' => ['label' => 'Event name', 'type' => 'text', 'required' => true],
                'properties' => ['label' => 'Properties', 'type' => 'key_value'],
            ],
        ],
        'add_note' => [
            'label' => 'Add note', 'description' => 'Adds an internal note to the record.',
            'handler' => AddNoteAction::class, 'entities' => ['lead', 'customer', 'opportunity', 'ticket'], 'fields' => ['body'],
            'form_fields' => ['body' => ['label' => 'Note', 'type' => 'textarea', 'required' => true]],
        ],
        'change_lead_status' => [
            'label' => 'Change lead status', 'description' => 'Moves a lead to another status.',
            'handler' => ChangeLeadStatusAction::class, 'entities' => ['lead'], 'fields' => ['status'],
            'form_fields' => ['status' => ['label' => 'Status', 'type' => 'select', 'required' => true, 'options' => [
                'new' => 'New', 'contacted' => 'Contacted', 'qualified' => 'Qualified',
                'converted' => 'Converted', 'won' => 'Won', 'lost' => 'Lost',
            ]]],
        ],
        'change_customer_lifecycle' => [
            'label' => 'Change customer lifecycle stage', 'description' => 'Advances the related customer lifecycle stage.',
            'handler' => ChangeCustomerLifecycleAction::class,
            'entities' => ['customer', 'opportunity', 'quotation', 'sales_order', 'invoice', 'payment'],
            'fields' => ['lifecycle_stage'],
            'form_fields' => ['lifecycle_stage' => ['label' => 'Lifecycle stage', 'type' => 'select', 'required' => true, 'options' => [
                'subscriber' => 'Subscriber',
                'lead' => 'Lead',
                'marketing_qualified' => 'Marketing qualified',
                'sales_qualified' => 'Sales qualified',
                'opportunity' => 'Opportunity',
                'customer' => 'Customer',
                'evangelist' => 'Evangelist',
            ]]],
        ],
        'update_metadata' => [
            'label' => 'Update metadata', 'description' => 'Sets one or more dynamic metadata values.',
            'handler' => UpdateMetadataAction::class, 'entities' => ['lead', 'customer', 'opportunity'], 'fields' => ['values'],
            'form_fields' => ['values' => ['label' => 'Metadata values', 'type' => 'key_value', 'required' => true]],
        ],
        'send_crm_email' => [
            'label' => 'Send CRM email',
            'description' => 'Sends an email through organization mail using the CRM email service.',
            'handler' => SendCrmEmailAction::class,
            'entities' => ['lead', 'customer', 'opportunity', 'invoice', 'payment', 'quotation', 'sales_order', 'adjustment_note', 'ticket'],
            'fields' => ['recipient'],
            'form_fields' => [
                'recipient' => ['label' => 'Recipient', 'type' => 'select', 'required' => true, 'options' => [
                    'customer' => 'Customer',
                    'contact' => 'Primary contact',
                    'record_owner' => 'Record owner',
                ]],
                'subject' => ['label' => 'Subject', 'type' => 'text'],
                'message' => ['label' => 'Message', 'type' => 'textarea'],
                'template_id' => ['label' => 'Template ID', 'type' => 'text'],
                'cc' => ['label' => 'CC', 'type' => 'text'],
                'bcc' => ['label' => 'BCC', 'type' => 'text'],
            ],
        ],
        'send_crm_email_template' => [
            'label' => 'Send CRM email template',
            'description' => 'Sends an organization CRM email template through the CRM email service.',
            'handler' => SendCrmEmailAction::class,
            'entities' => ['lead', 'customer', 'opportunity', 'invoice', 'payment', 'quotation', 'sales_order', 'adjustment_note', 'ticket'],
            'fields' => ['recipient', 'template_id'],
            'form_fields' => [
                'recipient' => ['label' => 'Recipient', 'type' => 'select', 'required' => true, 'options' => [
                    'customer' => 'Customer',
                    'contact' => 'Primary contact',
                    'record_owner' => 'Record owner',
                ]],
                'template_id' => ['label' => 'Template ID', 'type' => 'text', 'required' => true],
                'cc' => ['label' => 'CC', 'type' => 'text'],
                'bcc' => ['label' => 'BCC', 'type' => 'text'],
            ],
        ],
        'notify_user' => [
            'label' => 'Notify user', 'description' => 'Sends an in-app notification to an organization member.',
            'handler' => NotifyUserAction::class,
            // Entity-agnostic notification action — CRM + HRMS subject entities.
            'entities' => array_values(array_unique(array_merge(
                ['lead', 'customer', 'opportunity', 'invoice', 'payment', 'quotation', 'sales_order', 'adjustment_note', 'ticket'],
                $hrmsEntities,
            ))),
            'fields' => ['user_id', 'title', 'message'],
            'form_fields' => [
                'user_id' => ['label' => 'Recipient', 'type' => 'user', 'required' => true],
                'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
                'message' => ['label' => 'Message', 'type' => 'textarea', 'required' => true],
                'action_url' => ['label' => 'Action URL', 'type' => 'url'],
            ],
        ],
    ],
];
