<x-app-layout>
    <x-flash-messages />

    <x-layouts.entity-listing
        :title="__('Export #:id', ['id' => $session->id])"
        :subtitle="__(':entity · :format', ['entity' => $entityLabel, 'format' => $formatLabel])"
    >
        <x-slot:breadcrumbs>
            <x-nav.breadcrumbs :items="[
                ['label' => __('Administration'), 'href' => route('administration.home')],
                ['label' => __('Export Center'), 'href' => route('administration.exports.index')],
                ['label' => __('Export #:id', ['id' => $session->id]), 'current' => true],
            ]" />
        </x-slot:breadcrumbs>

        <x-slot:actions>
            @if ($session->isDownloadable())
                <x-ui.button :href="route('administration.exports.download', $session)" variant="primary" size="sm">
                    {{ __('Download') }}
                </x-ui.button>
            @endif
            <x-ui.button :href="route('administration.exports.history')" variant="secondary" size="sm">
                {{ __('History') }}
            </x-ui.button>
        </x-slot:actions>

        <div class="mx-auto max-w-3xl space-y-6">
            <x-entity.section :title="__('Status')">
                <dl class="grid gap-3 sm:grid-cols-2 text-sm">
                    <div>
                        <dt class="text-ink-muted">{{ __('Status') }}</dt>
                        <dd class="font-medium text-ink-heading">{{ ucfirst($session->status) }}</dd>
                    </div>
                    <div>
                        <dt class="text-ink-muted">{{ __('Progress') }}</dt>
                        <dd class="font-medium text-ink-heading">{{ $session->progressPercent() }}% ({{ $session->processed_count }}/{{ $session->total_count }})</dd>
                    </div>
                    <div>
                        <dt class="text-ink-muted">{{ __('Selection') }}</dt>
                        <dd class="font-medium text-ink-heading">{{ $session->selection_mode }}</dd>
                    </div>
                    <div>
                        <dt class="text-ink-muted">{{ __('Generated by') }}</dt>
                        <dd class="font-medium text-ink-heading">{{ $session->initiator?->name ?? '—' }}</dd>
                    </div>
                    <div>
                        <dt class="text-ink-muted">{{ __('Started') }}</dt>
                        <dd class="font-medium text-ink-heading">{{ $session->started_at?->format('Y-m-d H:i:s') ?? '—' }}</dd>
                    </div>
                    <div>
                        <dt class="text-ink-muted">{{ __('Completed') }}</dt>
                        <dd class="font-medium text-ink-heading">{{ $session->completed_at?->format('Y-m-d H:i:s') ?? '—' }}</dd>
                    </div>
                    <div>
                        <dt class="text-ink-muted">{{ __('File size') }}</dt>
                        <dd class="font-medium text-ink-heading">{{ $session->formattedFileSize() }}</dd>
                    </div>
                    <div>
                        <dt class="text-ink-muted">{{ __('Download expires') }}</dt>
                        <dd class="font-medium text-ink-heading">{{ $session->download_expires_at?->format('Y-m-d H:i') ?? '—' }}</dd>
                    </div>
                </dl>

                @if ($session->last_error)
                    <x-ui.alert variant="danger" class="mt-4">{{ $session->last_error }}</x-ui.alert>
                @endif

                @if (in_array($session->status, ['queued', 'running', 'pending'], true))
                    <p class="mt-4 text-sm text-ink-muted">{{ __('This page refreshes automatically while the export is processing.') }}</p>
                    <meta http-equiv="refresh" content="3">
                @endif
            </x-entity.section>

            <x-entity.section :title="__('Actions')">
                <div class="flex flex-wrap gap-2">
                    @if ($session->isDownloadable())
                        <x-ui.button :href="route('administration.exports.download', $session)" variant="primary" size="sm">
                            {{ __('Download file') }}
                        </x-ui.button>
                    @endif

                    <form method="post" action="{{ route('administration.exports.regenerate', $session) }}">
                        @csrf
                        <x-ui.button type="submit" variant="secondary" size="sm">{{ __('Regenerate') }}</x-ui.button>
                    </form>

                    @if ($session->status === 'completed' && ! $session->revoked_at)
                        <form method="post" action="{{ route('administration.exports.revoke', $session) }}">
                            @csrf
                            <x-ui.button type="submit" variant="secondary" size="sm">{{ __('Revoke download') }}</x-ui.button>
                        </form>
                    @endif

                    <form method="post" action="{{ route('administration.exports.destroy', $session) }}" onsubmit="return confirm(@js(__('Delete this export permanently?')))">
                        @csrf
                        @method('DELETE')
                        <x-ui.button type="submit" variant="danger" size="sm">{{ __('Delete') }}</x-ui.button>
                    </form>
                </div>
            </x-entity.section>
        </div>
    </x-layouts.entity-listing>
</x-app-layout>
